/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.patients.requests;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.resources.patients.types.UpdatePatientRequestAddress;
import com.affinity.api.resources.patients.types.UpdatePatientRequestAddressesItem;
import com.affinity.api.resources.patients.types.UpdatePatientRequestClinicalProfile;
import com.affinity.api.resources.patients.types.UpdatePatientRequestEncountersItem;
import com.affinity.api.resources.patients.types.UpdatePatientRequestExternalIdentitiesItem;
import com.affinity.api.resources.patients.types.UpdatePatientRequestGender;
import com.affinity.api.resources.patients.types.UpdatePatientRequestMeasurementsItem;
import com.affinity.api.resources.patients.types.UpdatePatientRequestName;
import com.affinity.api.resources.patients.types.UpdatePatientRequestProgramsItem;
import com.affinity.api.resources.patients.types.UpdatePatientRequestStatus;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdatePatientRequest.Builder.class
)
public final class UpdatePatientRequest {
  private final String idempotencyKey;

  private final Optional<String> affinityActorId;

  private final Optional<String> affinityActorType;

  private final Optional<UpdatePatientRequestAddress> address;

  private final Optional<UpdatePatientRequestClinicalProfile> clinicalProfile;

  private final Optional<String> dateOfBirth;

  private final Optional<String> email;

  private final Optional<String> externalId;

  private final Optional<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities;

  private final Optional<List<UpdatePatientRequestAddressesItem>> addresses;

  private final Optional<List<UpdatePatientRequestEncountersItem>> encounters;

  private final Optional<UpdatePatientRequestGender> gender;

  private final Optional<String> locationId;

  private final Optional<Map<String, Object>> metadata;

  private final Optional<String> medicalRecordNumber;

  private final Optional<List<UpdatePatientRequestMeasurementsItem>> measurements;

  private final Optional<UpdatePatientRequestName> name;

  private final Optional<List<UpdatePatientRequestProgramsItem>> programs;

  private final Optional<String> phone;

  private final Optional<UpdatePatientRequestStatus> status;

  private final Map<String, Object> additionalProperties;

  private UpdatePatientRequest(String idempotencyKey, Optional<String> affinityActorId,
      Optional<String> affinityActorType, Optional<UpdatePatientRequestAddress> address,
      Optional<UpdatePatientRequestClinicalProfile> clinicalProfile, Optional<String> dateOfBirth,
      Optional<String> email, Optional<String> externalId,
      Optional<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities,
      Optional<List<UpdatePatientRequestAddressesItem>> addresses,
      Optional<List<UpdatePatientRequestEncountersItem>> encounters,
      Optional<UpdatePatientRequestGender> gender, Optional<String> locationId,
      Optional<Map<String, Object>> metadata, Optional<String> medicalRecordNumber,
      Optional<List<UpdatePatientRequestMeasurementsItem>> measurements,
      Optional<UpdatePatientRequestName> name,
      Optional<List<UpdatePatientRequestProgramsItem>> programs, Optional<String> phone,
      Optional<UpdatePatientRequestStatus> status, Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.affinityActorId = affinityActorId;
    this.affinityActorType = affinityActorType;
    this.address = address;
    this.clinicalProfile = clinicalProfile;
    this.dateOfBirth = dateOfBirth;
    this.email = email;
    this.externalId = externalId;
    this.externalIdentities = externalIdentities;
    this.addresses = addresses;
    this.encounters = encounters;
    this.gender = gender;
    this.locationId = locationId;
    this.metadata = metadata;
    this.medicalRecordNumber = medicalRecordNumber;
    this.measurements = measurements;
    this.name = name;
    this.programs = programs;
    this.phone = phone;
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public String getIdempotencyKey() {
    return idempotencyKey;
  }

  /**
   * @return Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.
   */
  @JsonIgnore
  public Optional<String> getAffinityActorId() {
    return affinityActorId;
  }

  /**
   * @return Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.
   */
  @JsonIgnore
  public Optional<String> getAffinityActorType() {
    return affinityActorType;
  }

  @JsonIgnore
  public Optional<UpdatePatientRequestAddress> getAddress() {
    if (address == null) {
      return Optional.empty();
    }
    return address;
  }

  @JsonIgnore
  public Optional<UpdatePatientRequestClinicalProfile> getClinicalProfile() {
    if (clinicalProfile == null) {
      return Optional.empty();
    }
    return clinicalProfile;
  }

  @JsonIgnore
  public Optional<String> getDateOfBirth() {
    if (dateOfBirth == null) {
      return Optional.empty();
    }
    return dateOfBirth;
  }

  @JsonIgnore
  public Optional<String> getEmail() {
    if (email == null) {
      return Optional.empty();
    }
    return email;
  }

  @JsonIgnore
  public Optional<String> getExternalId() {
    if (externalId == null) {
      return Optional.empty();
    }
    return externalId;
  }

  @JsonIgnore
  public Optional<List<UpdatePatientRequestExternalIdentitiesItem>> getExternalIdentities() {
    if (externalIdentities == null) {
      return Optional.empty();
    }
    return externalIdentities;
  }

  @JsonIgnore
  public Optional<List<UpdatePatientRequestAddressesItem>> getAddresses() {
    if (addresses == null) {
      return Optional.empty();
    }
    return addresses;
  }

  @JsonIgnore
  public Optional<List<UpdatePatientRequestEncountersItem>> getEncounters() {
    if (encounters == null) {
      return Optional.empty();
    }
    return encounters;
  }

  @JsonIgnore
  public Optional<UpdatePatientRequestGender> getGender() {
    if (gender == null) {
      return Optional.empty();
    }
    return gender;
  }

  @JsonIgnore
  public Optional<String> getLocationId() {
    if (locationId == null) {
      return Optional.empty();
    }
    return locationId;
  }

  @JsonIgnore
  public Optional<Map<String, Object>> getMetadata() {
    if (metadata == null) {
      return Optional.empty();
    }
    return metadata;
  }

  @JsonIgnore
  public Optional<String> getMedicalRecordNumber() {
    if (medicalRecordNumber == null) {
      return Optional.empty();
    }
    return medicalRecordNumber;
  }

  @JsonIgnore
  public Optional<List<UpdatePatientRequestMeasurementsItem>> getMeasurements() {
    if (measurements == null) {
      return Optional.empty();
    }
    return measurements;
  }

  @JsonIgnore
  public Optional<UpdatePatientRequestName> getName() {
    if (name == null) {
      return Optional.empty();
    }
    return name;
  }

  @JsonIgnore
  public Optional<List<UpdatePatientRequestProgramsItem>> getPrograms() {
    if (programs == null) {
      return Optional.empty();
    }
    return programs;
  }

  @JsonIgnore
  public Optional<String> getPhone() {
    if (phone == null) {
      return Optional.empty();
    }
    return phone;
  }

  @JsonIgnore
  public Optional<UpdatePatientRequestStatus> getStatus() {
    if (status == null) {
      return Optional.empty();
    }
    return status;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("address")
  private Optional<UpdatePatientRequestAddress> _getAddress() {
    return address;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("clinicalProfile")
  private Optional<UpdatePatientRequestClinicalProfile> _getClinicalProfile() {
    return clinicalProfile;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("dateOfBirth")
  private Optional<String> _getDateOfBirth() {
    return dateOfBirth;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("email")
  private Optional<String> _getEmail() {
    return email;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("externalId")
  private Optional<String> _getExternalId() {
    return externalId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("externalIdentities")
  private Optional<List<UpdatePatientRequestExternalIdentitiesItem>> _getExternalIdentities() {
    return externalIdentities;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("addresses")
  private Optional<List<UpdatePatientRequestAddressesItem>> _getAddresses() {
    return addresses;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("encounters")
  private Optional<List<UpdatePatientRequestEncountersItem>> _getEncounters() {
    return encounters;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("gender")
  private Optional<UpdatePatientRequestGender> _getGender() {
    return gender;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("locationId")
  private Optional<String> _getLocationId() {
    return locationId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("metadata")
  private Optional<Map<String, Object>> _getMetadata() {
    return metadata;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("medicalRecordNumber")
  private Optional<String> _getMedicalRecordNumber() {
    return medicalRecordNumber;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("measurements")
  private Optional<List<UpdatePatientRequestMeasurementsItem>> _getMeasurements() {
    return measurements;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("name")
  private Optional<UpdatePatientRequestName> _getName() {
    return name;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("programs")
  private Optional<List<UpdatePatientRequestProgramsItem>> _getPrograms() {
    return programs;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("phone")
  private Optional<String> _getPhone() {
    return phone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("status")
  private Optional<UpdatePatientRequestStatus> _getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdatePatientRequest && equalTo((UpdatePatientRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdatePatientRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && affinityActorId.equals(other.affinityActorId) && affinityActorType.equals(other.affinityActorType) && address.equals(other.address) && clinicalProfile.equals(other.clinicalProfile) && dateOfBirth.equals(other.dateOfBirth) && email.equals(other.email) && externalId.equals(other.externalId) && externalIdentities.equals(other.externalIdentities) && addresses.equals(other.addresses) && encounters.equals(other.encounters) && gender.equals(other.gender) && locationId.equals(other.locationId) && metadata.equals(other.metadata) && medicalRecordNumber.equals(other.medicalRecordNumber) && measurements.equals(other.measurements) && name.equals(other.name) && programs.equals(other.programs) && phone.equals(other.phone) && status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.affinityActorId, this.affinityActorType, this.address, this.clinicalProfile, this.dateOfBirth, this.email, this.externalId, this.externalIdentities, this.addresses, this.encounters, this.gender, this.locationId, this.metadata, this.medicalRecordNumber, this.measurements, this.name, this.programs, this.phone, this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdempotencyKeyStage builder() {
    return new Builder();
  }

  public interface IdempotencyKeyStage {
    _FinalStage idempotencyKey(@NotNull String idempotencyKey);

    Builder from(UpdatePatientRequest other);
  }

  public interface _FinalStage {
    UpdatePatientRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.</p>
     */
    _FinalStage affinityActorId(Optional<String> affinityActorId);

    _FinalStage affinityActorId(String affinityActorId);

    /**
     * <p>Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.</p>
     */
    _FinalStage affinityActorType(Optional<String> affinityActorType);

    _FinalStage affinityActorType(String affinityActorType);

    _FinalStage address(Optional<UpdatePatientRequestAddress> address);

    _FinalStage address(UpdatePatientRequestAddress address);

    _FinalStage address(Nullable<UpdatePatientRequestAddress> address);

    _FinalStage clinicalProfile(Optional<UpdatePatientRequestClinicalProfile> clinicalProfile);

    _FinalStage clinicalProfile(UpdatePatientRequestClinicalProfile clinicalProfile);

    _FinalStage clinicalProfile(Nullable<UpdatePatientRequestClinicalProfile> clinicalProfile);

    _FinalStage dateOfBirth(Optional<String> dateOfBirth);

    _FinalStage dateOfBirth(String dateOfBirth);

    _FinalStage dateOfBirth(Nullable<String> dateOfBirth);

    _FinalStage email(Optional<String> email);

    _FinalStage email(String email);

    _FinalStage email(Nullable<String> email);

    _FinalStage externalId(Optional<String> externalId);

    _FinalStage externalId(String externalId);

    _FinalStage externalId(Nullable<String> externalId);

    _FinalStage externalIdentities(
        Optional<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities);

    _FinalStage externalIdentities(
        List<UpdatePatientRequestExternalIdentitiesItem> externalIdentities);

    _FinalStage externalIdentities(
        Nullable<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities);

    _FinalStage addresses(Optional<List<UpdatePatientRequestAddressesItem>> addresses);

    _FinalStage addresses(List<UpdatePatientRequestAddressesItem> addresses);

    _FinalStage addresses(Nullable<List<UpdatePatientRequestAddressesItem>> addresses);

    _FinalStage encounters(Optional<List<UpdatePatientRequestEncountersItem>> encounters);

    _FinalStage encounters(List<UpdatePatientRequestEncountersItem> encounters);

    _FinalStage encounters(Nullable<List<UpdatePatientRequestEncountersItem>> encounters);

    _FinalStage gender(Optional<UpdatePatientRequestGender> gender);

    _FinalStage gender(UpdatePatientRequestGender gender);

    _FinalStage gender(Nullable<UpdatePatientRequestGender> gender);

    _FinalStage locationId(Optional<String> locationId);

    _FinalStage locationId(String locationId);

    _FinalStage locationId(Nullable<String> locationId);

    _FinalStage metadata(Optional<Map<String, Object>> metadata);

    _FinalStage metadata(Map<String, Object> metadata);

    _FinalStage metadata(Nullable<Map<String, Object>> metadata);

    _FinalStage medicalRecordNumber(Optional<String> medicalRecordNumber);

    _FinalStage medicalRecordNumber(String medicalRecordNumber);

    _FinalStage medicalRecordNumber(Nullable<String> medicalRecordNumber);

    _FinalStage measurements(Optional<List<UpdatePatientRequestMeasurementsItem>> measurements);

    _FinalStage measurements(List<UpdatePatientRequestMeasurementsItem> measurements);

    _FinalStage measurements(Nullable<List<UpdatePatientRequestMeasurementsItem>> measurements);

    _FinalStage name(Optional<UpdatePatientRequestName> name);

    _FinalStage name(UpdatePatientRequestName name);

    _FinalStage name(Nullable<UpdatePatientRequestName> name);

    _FinalStage programs(Optional<List<UpdatePatientRequestProgramsItem>> programs);

    _FinalStage programs(List<UpdatePatientRequestProgramsItem> programs);

    _FinalStage programs(Nullable<List<UpdatePatientRequestProgramsItem>> programs);

    _FinalStage phone(Optional<String> phone);

    _FinalStage phone(String phone);

    _FinalStage phone(Nullable<String> phone);

    _FinalStage status(Optional<UpdatePatientRequestStatus> status);

    _FinalStage status(UpdatePatientRequestStatus status);

    _FinalStage status(Nullable<UpdatePatientRequestStatus> status);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdempotencyKeyStage, _FinalStage {
    private String idempotencyKey;

    private Optional<UpdatePatientRequestStatus> status = Optional.empty();

    private Optional<String> phone = Optional.empty();

    private Optional<List<UpdatePatientRequestProgramsItem>> programs = Optional.empty();

    private Optional<UpdatePatientRequestName> name = Optional.empty();

    private Optional<List<UpdatePatientRequestMeasurementsItem>> measurements = Optional.empty();

    private Optional<String> medicalRecordNumber = Optional.empty();

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private Optional<String> locationId = Optional.empty();

    private Optional<UpdatePatientRequestGender> gender = Optional.empty();

    private Optional<List<UpdatePatientRequestEncountersItem>> encounters = Optional.empty();

    private Optional<List<UpdatePatientRequestAddressesItem>> addresses = Optional.empty();

    private Optional<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities = Optional.empty();

    private Optional<String> externalId = Optional.empty();

    private Optional<String> email = Optional.empty();

    private Optional<String> dateOfBirth = Optional.empty();

    private Optional<UpdatePatientRequestClinicalProfile> clinicalProfile = Optional.empty();

    private Optional<UpdatePatientRequestAddress> address = Optional.empty();

    private Optional<String> affinityActorType = Optional.empty();

    private Optional<String> affinityActorId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdatePatientRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      affinityActorId(other.getAffinityActorId());
      affinityActorType(other.getAffinityActorType());
      address(other.getAddress());
      clinicalProfile(other.getClinicalProfile());
      dateOfBirth(other.getDateOfBirth());
      email(other.getEmail());
      externalId(other.getExternalId());
      externalIdentities(other.getExternalIdentities());
      addresses(other.getAddresses());
      encounters(other.getEncounters());
      gender(other.getGender());
      locationId(other.getLocationId());
      metadata(other.getMetadata());
      medicalRecordNumber(other.getMedicalRecordNumber());
      measurements(other.getMeasurements());
      name(other.getName());
      programs(other.getPrograms());
      phone(other.getPhone());
      status(other.getStatus());
      return this;
    }

    @java.lang.Override
    public _FinalStage idempotencyKey(@NotNull String idempotencyKey) {
      this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage status(Nullable<UpdatePatientRequestStatus> status) {
      if (status.isNull()) {
        this.status = null;
      }
      else if (status.isEmpty()) {
        this.status = Optional.empty();
      }
      else {
        this.status = Optional.of(status.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage status(UpdatePatientRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public _FinalStage status(Optional<UpdatePatientRequestStatus> status) {
      this.status = status;
      return this;
    }

    @java.lang.Override
    public _FinalStage phone(Nullable<String> phone) {
      if (phone.isNull()) {
        this.phone = null;
      }
      else if (phone.isEmpty()) {
        this.phone = Optional.empty();
      }
      else {
        this.phone = Optional.of(phone.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage phone(String phone) {
      this.phone = Optional.ofNullable(phone);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "phone",
        nulls = Nulls.SKIP
    )
    public _FinalStage phone(Optional<String> phone) {
      this.phone = phone;
      return this;
    }

    @java.lang.Override
    public _FinalStage programs(Nullable<List<UpdatePatientRequestProgramsItem>> programs) {
      if (programs.isNull()) {
        this.programs = null;
      }
      else if (programs.isEmpty()) {
        this.programs = Optional.empty();
      }
      else {
        this.programs = Optional.of(programs.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage programs(List<UpdatePatientRequestProgramsItem> programs) {
      this.programs = Optional.ofNullable(programs);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "programs",
        nulls = Nulls.SKIP
    )
    public _FinalStage programs(Optional<List<UpdatePatientRequestProgramsItem>> programs) {
      this.programs = programs;
      return this;
    }

    @java.lang.Override
    public _FinalStage name(Nullable<UpdatePatientRequestName> name) {
      if (name.isNull()) {
        this.name = null;
      }
      else if (name.isEmpty()) {
        this.name = Optional.empty();
      }
      else {
        this.name = Optional.of(name.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage name(UpdatePatientRequestName name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<UpdatePatientRequestName> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public _FinalStage measurements(
        Nullable<List<UpdatePatientRequestMeasurementsItem>> measurements) {
      if (measurements.isNull()) {
        this.measurements = null;
      }
      else if (measurements.isEmpty()) {
        this.measurements = Optional.empty();
      }
      else {
        this.measurements = Optional.of(measurements.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage measurements(List<UpdatePatientRequestMeasurementsItem> measurements) {
      this.measurements = Optional.ofNullable(measurements);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "measurements",
        nulls = Nulls.SKIP
    )
    public _FinalStage measurements(
        Optional<List<UpdatePatientRequestMeasurementsItem>> measurements) {
      this.measurements = measurements;
      return this;
    }

    @java.lang.Override
    public _FinalStage medicalRecordNumber(Nullable<String> medicalRecordNumber) {
      if (medicalRecordNumber.isNull()) {
        this.medicalRecordNumber = null;
      }
      else if (medicalRecordNumber.isEmpty()) {
        this.medicalRecordNumber = Optional.empty();
      }
      else {
        this.medicalRecordNumber = Optional.of(medicalRecordNumber.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage medicalRecordNumber(String medicalRecordNumber) {
      this.medicalRecordNumber = Optional.ofNullable(medicalRecordNumber);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "medicalRecordNumber",
        nulls = Nulls.SKIP
    )
    public _FinalStage medicalRecordNumber(Optional<String> medicalRecordNumber) {
      this.medicalRecordNumber = medicalRecordNumber;
      return this;
    }

    @java.lang.Override
    public _FinalStage metadata(Nullable<Map<String, Object>> metadata) {
      if (metadata.isNull()) {
        this.metadata = null;
      }
      else if (metadata.isEmpty()) {
        this.metadata = Optional.empty();
      }
      else {
        this.metadata = Optional.of(metadata.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    @java.lang.Override
    public _FinalStage locationId(Nullable<String> locationId) {
      if (locationId.isNull()) {
        this.locationId = null;
      }
      else if (locationId.isEmpty()) {
        this.locationId = Optional.empty();
      }
      else {
        this.locationId = Optional.of(locationId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage locationId(String locationId) {
      this.locationId = Optional.ofNullable(locationId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "locationId",
        nulls = Nulls.SKIP
    )
    public _FinalStage locationId(Optional<String> locationId) {
      this.locationId = locationId;
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(Nullable<UpdatePatientRequestGender> gender) {
      if (gender.isNull()) {
        this.gender = null;
      }
      else if (gender.isEmpty()) {
        this.gender = Optional.empty();
      }
      else {
        this.gender = Optional.of(gender.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage gender(UpdatePatientRequestGender gender) {
      this.gender = Optional.ofNullable(gender);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "gender",
        nulls = Nulls.SKIP
    )
    public _FinalStage gender(Optional<UpdatePatientRequestGender> gender) {
      this.gender = gender;
      return this;
    }

    @java.lang.Override
    public _FinalStage encounters(Nullable<List<UpdatePatientRequestEncountersItem>> encounters) {
      if (encounters.isNull()) {
        this.encounters = null;
      }
      else if (encounters.isEmpty()) {
        this.encounters = Optional.empty();
      }
      else {
        this.encounters = Optional.of(encounters.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage encounters(List<UpdatePatientRequestEncountersItem> encounters) {
      this.encounters = Optional.ofNullable(encounters);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "encounters",
        nulls = Nulls.SKIP
    )
    public _FinalStage encounters(Optional<List<UpdatePatientRequestEncountersItem>> encounters) {
      this.encounters = encounters;
      return this;
    }

    @java.lang.Override
    public _FinalStage addresses(Nullable<List<UpdatePatientRequestAddressesItem>> addresses) {
      if (addresses.isNull()) {
        this.addresses = null;
      }
      else if (addresses.isEmpty()) {
        this.addresses = Optional.empty();
      }
      else {
        this.addresses = Optional.of(addresses.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addresses(List<UpdatePatientRequestAddressesItem> addresses) {
      this.addresses = Optional.ofNullable(addresses);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "addresses",
        nulls = Nulls.SKIP
    )
    public _FinalStage addresses(Optional<List<UpdatePatientRequestAddressesItem>> addresses) {
      this.addresses = addresses;
      return this;
    }

    @java.lang.Override
    public _FinalStage externalIdentities(
        Nullable<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities) {
      if (externalIdentities.isNull()) {
        this.externalIdentities = null;
      }
      else if (externalIdentities.isEmpty()) {
        this.externalIdentities = Optional.empty();
      }
      else {
        this.externalIdentities = Optional.of(externalIdentities.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage externalIdentities(
        List<UpdatePatientRequestExternalIdentitiesItem> externalIdentities) {
      this.externalIdentities = Optional.ofNullable(externalIdentities);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "externalIdentities",
        nulls = Nulls.SKIP
    )
    public _FinalStage externalIdentities(
        Optional<List<UpdatePatientRequestExternalIdentitiesItem>> externalIdentities) {
      this.externalIdentities = externalIdentities;
      return this;
    }

    @java.lang.Override
    public _FinalStage externalId(Nullable<String> externalId) {
      if (externalId.isNull()) {
        this.externalId = null;
      }
      else if (externalId.isEmpty()) {
        this.externalId = Optional.empty();
      }
      else {
        this.externalId = Optional.of(externalId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage externalId(String externalId) {
      this.externalId = Optional.ofNullable(externalId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "externalId",
        nulls = Nulls.SKIP
    )
    public _FinalStage externalId(Optional<String> externalId) {
      this.externalId = externalId;
      return this;
    }

    @java.lang.Override
    public _FinalStage email(Nullable<String> email) {
      if (email.isNull()) {
        this.email = null;
      }
      else if (email.isEmpty()) {
        this.email = Optional.empty();
      }
      else {
        this.email = Optional.of(email.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage email(String email) {
      this.email = Optional.ofNullable(email);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "email",
        nulls = Nulls.SKIP
    )
    public _FinalStage email(Optional<String> email) {
      this.email = email;
      return this;
    }

    @java.lang.Override
    public _FinalStage dateOfBirth(Nullable<String> dateOfBirth) {
      if (dateOfBirth.isNull()) {
        this.dateOfBirth = null;
      }
      else if (dateOfBirth.isEmpty()) {
        this.dateOfBirth = Optional.empty();
      }
      else {
        this.dateOfBirth = Optional.of(dateOfBirth.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage dateOfBirth(String dateOfBirth) {
      this.dateOfBirth = Optional.ofNullable(dateOfBirth);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "dateOfBirth",
        nulls = Nulls.SKIP
    )
    public _FinalStage dateOfBirth(Optional<String> dateOfBirth) {
      this.dateOfBirth = dateOfBirth;
      return this;
    }

    @java.lang.Override
    public _FinalStage clinicalProfile(
        Nullable<UpdatePatientRequestClinicalProfile> clinicalProfile) {
      if (clinicalProfile.isNull()) {
        this.clinicalProfile = null;
      }
      else if (clinicalProfile.isEmpty()) {
        this.clinicalProfile = Optional.empty();
      }
      else {
        this.clinicalProfile = Optional.of(clinicalProfile.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage clinicalProfile(UpdatePatientRequestClinicalProfile clinicalProfile) {
      this.clinicalProfile = Optional.ofNullable(clinicalProfile);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "clinicalProfile",
        nulls = Nulls.SKIP
    )
    public _FinalStage clinicalProfile(
        Optional<UpdatePatientRequestClinicalProfile> clinicalProfile) {
      this.clinicalProfile = clinicalProfile;
      return this;
    }

    @java.lang.Override
    public _FinalStage address(Nullable<UpdatePatientRequestAddress> address) {
      if (address.isNull()) {
        this.address = null;
      }
      else if (address.isEmpty()) {
        this.address = Optional.empty();
      }
      else {
        this.address = Optional.of(address.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage address(UpdatePatientRequestAddress address) {
      this.address = Optional.ofNullable(address);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "address",
        nulls = Nulls.SKIP
    )
    public _FinalStage address(Optional<UpdatePatientRequestAddress> address) {
      this.address = address;
      return this;
    }

    /**
     * <p>Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage affinityActorType(String affinityActorType) {
      this.affinityActorType = Optional.ofNullable(affinityActorType);
      return this;
    }

    /**
     * <p>Use user when a person initiated the action and system for autonomous work. Omit both actor headers to default to system.</p>
     */
    @java.lang.Override
    public _FinalStage affinityActorType(Optional<String> affinityActorType) {
      this.affinityActorType = affinityActorType;
      return this;
    }

    /**
     * <p>Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage affinityActorId(String affinityActorId) {
      this.affinityActorId = Optional.ofNullable(affinityActorId);
      return this;
    }

    /**
     * <p>Required for user actors and optional for system actors. Omit both actor headers to use the authenticated service account as a system actor.</p>
     */
    @java.lang.Override
    public _FinalStage affinityActorId(Optional<String> affinityActorId) {
      this.affinityActorId = affinityActorId;
      return this;
    }

    @java.lang.Override
    public UpdatePatientRequest build() {
      return new UpdatePatientRequest(idempotencyKey, affinityActorId, affinityActorType, address, clinicalProfile, dateOfBirth, email, externalId, externalIdentities, addresses, encounters, gender, locationId, metadata, medicalRecordNumber, measurements, name, programs, phone, status, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
