/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.webhooks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class UpdateWebhookEndpointRequestStatus {
  public static final UpdateWebhookEndpointRequestStatus SUSPENDED = new UpdateWebhookEndpointRequestStatus(Value.SUSPENDED, "suspended");

  public static final UpdateWebhookEndpointRequestStatus DISABLED = new UpdateWebhookEndpointRequestStatus(Value.DISABLED, "disabled");

  public static final UpdateWebhookEndpointRequestStatus ACTIVE = new UpdateWebhookEndpointRequestStatus(Value.ACTIVE, "active");

  private final Value value;

  private final String string;

  UpdateWebhookEndpointRequestStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof UpdateWebhookEndpointRequestStatus && this.string.equals(((UpdateWebhookEndpointRequestStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SUSPENDED:
        return visitor.visitSuspended();
      case DISABLED:
        return visitor.visitDisabled();
      case ACTIVE:
        return visitor.visitActive();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static UpdateWebhookEndpointRequestStatus valueOf(String value) {
    switch (value) {
      case "suspended":
        return SUSPENDED;
      case "disabled":
        return DISABLED;
      case "active":
        return ACTIVE;
      default:
        return new UpdateWebhookEndpointRequestStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACTIVE,

    SUSPENDED,

    DISABLED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitActive();

    T visitSuspended();

    T visitDisabled();

    T visitUnknown(String unknownType);
  }
}
