/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.practices.requests;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.resources.practices.types.UpdatePracticeRequestAddress;
import com.affinity.api.resources.practices.types.UpdatePracticeRequestAttestations;
import com.affinity.api.resources.practices.types.UpdatePracticeRequestComplianceContact;
import com.affinity.api.resources.practices.types.UpdatePracticeRequestPrescribersItem;
import com.affinity.api.resources.practices.types.UpdatePracticeRequestPrimaryContact;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdatePracticeRequest.Builder.class
)
public final class UpdatePracticeRequest {
  private final Optional<String> idempotencyKey;

  private final Optional<Boolean> liveEnabled;

  private final Optional<UpdatePracticeRequestAddress> address;

  private final Optional<UpdatePracticeRequestAttestations> attestations;

  private final Optional<UpdatePracticeRequestComplianceContact> complianceContact;

  private final Optional<String> externalId;

  private final Optional<String> legalName;

  private final Optional<Map<String, Object>> metadata;

  private final Optional<String> name;

  private final Optional<List<UpdatePracticeRequestPrescribersItem>> prescribers;

  private final Optional<UpdatePracticeRequestPrimaryContact> primaryContact;

  private final Optional<String> supportEmail;

  private final Optional<String> supportPhone;

  private final Optional<String> timezone;

  private final Map<String, Object> additionalProperties;

  private UpdatePracticeRequest(Optional<String> idempotencyKey, Optional<Boolean> liveEnabled,
      Optional<UpdatePracticeRequestAddress> address,
      Optional<UpdatePracticeRequestAttestations> attestations,
      Optional<UpdatePracticeRequestComplianceContact> complianceContact,
      Optional<String> externalId, Optional<String> legalName,
      Optional<Map<String, Object>> metadata, Optional<String> name,
      Optional<List<UpdatePracticeRequestPrescribersItem>> prescribers,
      Optional<UpdatePracticeRequestPrimaryContact> primaryContact, Optional<String> supportEmail,
      Optional<String> supportPhone, Optional<String> timezone,
      Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.liveEnabled = liveEnabled;
    this.address = address;
    this.attestations = attestations;
    this.complianceContact = complianceContact;
    this.externalId = externalId;
    this.legalName = legalName;
    this.metadata = metadata;
    this.name = name;
    this.prescribers = prescribers;
    this.primaryContact = primaryContact;
    this.supportEmail = supportEmail;
    this.supportPhone = supportPhone;
    this.timezone = timezone;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  /**
   * @return Enable or disable Live access for an owned practice. Requires an approved platform and a Live request. Affinity Admin decisions take precedence.
   */
  @JsonProperty("liveEnabled")
  public Optional<Boolean> getLiveEnabled() {
    return liveEnabled;
  }

  @JsonIgnore
  public Optional<UpdatePracticeRequestAddress> getAddress() {
    if (address == null) {
      return Optional.empty();
    }
    return address;
  }

  @JsonIgnore
  public Optional<UpdatePracticeRequestAttestations> getAttestations() {
    if (attestations == null) {
      return Optional.empty();
    }
    return attestations;
  }

  @JsonIgnore
  public Optional<UpdatePracticeRequestComplianceContact> getComplianceContact() {
    if (complianceContact == null) {
      return Optional.empty();
    }
    return complianceContact;
  }

  @JsonIgnore
  public Optional<String> getExternalId() {
    if (externalId == null) {
      return Optional.empty();
    }
    return externalId;
  }

  @JsonIgnore
  public Optional<String> getLegalName() {
    if (legalName == null) {
      return Optional.empty();
    }
    return legalName;
  }

  @JsonIgnore
  public Optional<Map<String, Object>> getMetadata() {
    if (metadata == null) {
      return Optional.empty();
    }
    return metadata;
  }

  @JsonIgnore
  public Optional<String> getName() {
    if (name == null) {
      return Optional.empty();
    }
    return name;
  }

  @JsonIgnore
  public Optional<List<UpdatePracticeRequestPrescribersItem>> getPrescribers() {
    if (prescribers == null) {
      return Optional.empty();
    }
    return prescribers;
  }

  @JsonIgnore
  public Optional<UpdatePracticeRequestPrimaryContact> getPrimaryContact() {
    if (primaryContact == null) {
      return Optional.empty();
    }
    return primaryContact;
  }

  @JsonIgnore
  public Optional<String> getSupportEmail() {
    if (supportEmail == null) {
      return Optional.empty();
    }
    return supportEmail;
  }

  @JsonIgnore
  public Optional<String> getSupportPhone() {
    if (supportPhone == null) {
      return Optional.empty();
    }
    return supportPhone;
  }

  /**
   * @return Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.
   */
  @JsonIgnore
  public Optional<String> getTimezone() {
    if (timezone == null) {
      return Optional.empty();
    }
    return timezone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("address")
  private Optional<UpdatePracticeRequestAddress> _getAddress() {
    return address;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("attestations")
  private Optional<UpdatePracticeRequestAttestations> _getAttestations() {
    return attestations;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("complianceContact")
  private Optional<UpdatePracticeRequestComplianceContact> _getComplianceContact() {
    return complianceContact;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("externalId")
  private Optional<String> _getExternalId() {
    return externalId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("legalName")
  private Optional<String> _getLegalName() {
    return legalName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("metadata")
  private Optional<Map<String, Object>> _getMetadata() {
    return metadata;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("name")
  private Optional<String> _getName() {
    return name;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("prescribers")
  private Optional<List<UpdatePracticeRequestPrescribersItem>> _getPrescribers() {
    return prescribers;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("primaryContact")
  private Optional<UpdatePracticeRequestPrimaryContact> _getPrimaryContact() {
    return primaryContact;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("supportEmail")
  private Optional<String> _getSupportEmail() {
    return supportEmail;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("supportPhone")
  private Optional<String> _getSupportPhone() {
    return supportPhone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("timezone")
  private Optional<String> _getTimezone() {
    return timezone;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdatePracticeRequest && equalTo((UpdatePracticeRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdatePracticeRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && liveEnabled.equals(other.liveEnabled) && address.equals(other.address) && attestations.equals(other.attestations) && complianceContact.equals(other.complianceContact) && externalId.equals(other.externalId) && legalName.equals(other.legalName) && metadata.equals(other.metadata) && name.equals(other.name) && prescribers.equals(other.prescribers) && primaryContact.equals(other.primaryContact) && supportEmail.equals(other.supportEmail) && supportPhone.equals(other.supportPhone) && timezone.equals(other.timezone);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.liveEnabled, this.address, this.attestations, this.complianceContact, this.externalId, this.legalName, this.metadata, this.name, this.prescribers, this.primaryContact, this.supportEmail, this.supportPhone, this.timezone);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> idempotencyKey = Optional.empty();

    private Optional<Boolean> liveEnabled = Optional.empty();

    private Optional<UpdatePracticeRequestAddress> address = Optional.empty();

    private Optional<UpdatePracticeRequestAttestations> attestations = Optional.empty();

    private Optional<UpdatePracticeRequestComplianceContact> complianceContact = Optional.empty();

    private Optional<String> externalId = Optional.empty();

    private Optional<String> legalName = Optional.empty();

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private Optional<String> name = Optional.empty();

    private Optional<List<UpdatePracticeRequestPrescribersItem>> prescribers = Optional.empty();

    private Optional<UpdatePracticeRequestPrimaryContact> primaryContact = Optional.empty();

    private Optional<String> supportEmail = Optional.empty();

    private Optional<String> supportPhone = Optional.empty();

    private Optional<String> timezone = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdatePracticeRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      liveEnabled(other.getLiveEnabled());
      address(other.getAddress());
      attestations(other.getAttestations());
      complianceContact(other.getComplianceContact());
      externalId(other.getExternalId());
      legalName(other.getLegalName());
      metadata(other.getMetadata());
      name(other.getName());
      prescribers(other.getPrescribers());
      primaryContact(other.getPrimaryContact());
      supportEmail(other.getSupportEmail());
      supportPhone(other.getSupportPhone());
      timezone(other.getTimezone());
      return this;
    }

    public Builder idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    public Builder idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    /**
     * <p>Enable or disable Live access for an owned practice. Requires an approved platform and a Live request. Affinity Admin decisions take precedence.</p>
     */
    @JsonSetter(
        value = "liveEnabled",
        nulls = Nulls.SKIP
    )
    public Builder liveEnabled(Optional<Boolean> liveEnabled) {
      this.liveEnabled = liveEnabled;
      return this;
    }

    public Builder liveEnabled(Boolean liveEnabled) {
      this.liveEnabled = Optional.ofNullable(liveEnabled);
      return this;
    }

    @JsonSetter(
        value = "address",
        nulls = Nulls.SKIP
    )
    public Builder address(Optional<UpdatePracticeRequestAddress> address) {
      this.address = address;
      return this;
    }

    public Builder address(UpdatePracticeRequestAddress address) {
      this.address = Optional.ofNullable(address);
      return this;
    }

    public Builder address(Nullable<UpdatePracticeRequestAddress> address) {
      if (address.isNull()) {
        this.address = null;
      }
      else if (address.isEmpty()) {
        this.address = Optional.empty();
      }
      else {
        this.address = Optional.of(address.get());
      }
      return this;
    }

    @JsonSetter(
        value = "attestations",
        nulls = Nulls.SKIP
    )
    public Builder attestations(Optional<UpdatePracticeRequestAttestations> attestations) {
      this.attestations = attestations;
      return this;
    }

    public Builder attestations(UpdatePracticeRequestAttestations attestations) {
      this.attestations = Optional.ofNullable(attestations);
      return this;
    }

    public Builder attestations(Nullable<UpdatePracticeRequestAttestations> attestations) {
      if (attestations.isNull()) {
        this.attestations = null;
      }
      else if (attestations.isEmpty()) {
        this.attestations = Optional.empty();
      }
      else {
        this.attestations = Optional.of(attestations.get());
      }
      return this;
    }

    @JsonSetter(
        value = "complianceContact",
        nulls = Nulls.SKIP
    )
    public Builder complianceContact(
        Optional<UpdatePracticeRequestComplianceContact> complianceContact) {
      this.complianceContact = complianceContact;
      return this;
    }

    public Builder complianceContact(UpdatePracticeRequestComplianceContact complianceContact) {
      this.complianceContact = Optional.ofNullable(complianceContact);
      return this;
    }

    public Builder complianceContact(
        Nullable<UpdatePracticeRequestComplianceContact> complianceContact) {
      if (complianceContact.isNull()) {
        this.complianceContact = null;
      }
      else if (complianceContact.isEmpty()) {
        this.complianceContact = Optional.empty();
      }
      else {
        this.complianceContact = Optional.of(complianceContact.get());
      }
      return this;
    }

    @JsonSetter(
        value = "externalId",
        nulls = Nulls.SKIP
    )
    public Builder externalId(Optional<String> externalId) {
      this.externalId = externalId;
      return this;
    }

    public Builder externalId(String externalId) {
      this.externalId = Optional.ofNullable(externalId);
      return this;
    }

    public Builder externalId(Nullable<String> externalId) {
      if (externalId.isNull()) {
        this.externalId = null;
      }
      else if (externalId.isEmpty()) {
        this.externalId = Optional.empty();
      }
      else {
        this.externalId = Optional.of(externalId.get());
      }
      return this;
    }

    @JsonSetter(
        value = "legalName",
        nulls = Nulls.SKIP
    )
    public Builder legalName(Optional<String> legalName) {
      this.legalName = legalName;
      return this;
    }

    public Builder legalName(String legalName) {
      this.legalName = Optional.ofNullable(legalName);
      return this;
    }

    public Builder legalName(Nullable<String> legalName) {
      if (legalName.isNull()) {
        this.legalName = null;
      }
      else if (legalName.isEmpty()) {
        this.legalName = Optional.empty();
      }
      else {
        this.legalName = Optional.of(legalName.get());
      }
      return this;
    }

    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public Builder metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    public Builder metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    public Builder metadata(Nullable<Map<String, Object>> metadata) {
      if (metadata.isNull()) {
        this.metadata = null;
      }
      else if (metadata.isEmpty()) {
        this.metadata = Optional.empty();
      }
      else {
        this.metadata = Optional.of(metadata.get());
      }
      return this;
    }

    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public Builder name(Optional<String> name) {
      this.name = name;
      return this;
    }

    public Builder name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    public Builder name(Nullable<String> name) {
      if (name.isNull()) {
        this.name = null;
      }
      else if (name.isEmpty()) {
        this.name = Optional.empty();
      }
      else {
        this.name = Optional.of(name.get());
      }
      return this;
    }

    @JsonSetter(
        value = "prescribers",
        nulls = Nulls.SKIP
    )
    public Builder prescribers(Optional<List<UpdatePracticeRequestPrescribersItem>> prescribers) {
      this.prescribers = prescribers;
      return this;
    }

    public Builder prescribers(List<UpdatePracticeRequestPrescribersItem> prescribers) {
      this.prescribers = Optional.ofNullable(prescribers);
      return this;
    }

    public Builder prescribers(Nullable<List<UpdatePracticeRequestPrescribersItem>> prescribers) {
      if (prescribers.isNull()) {
        this.prescribers = null;
      }
      else if (prescribers.isEmpty()) {
        this.prescribers = Optional.empty();
      }
      else {
        this.prescribers = Optional.of(prescribers.get());
      }
      return this;
    }

    @JsonSetter(
        value = "primaryContact",
        nulls = Nulls.SKIP
    )
    public Builder primaryContact(Optional<UpdatePracticeRequestPrimaryContact> primaryContact) {
      this.primaryContact = primaryContact;
      return this;
    }

    public Builder primaryContact(UpdatePracticeRequestPrimaryContact primaryContact) {
      this.primaryContact = Optional.ofNullable(primaryContact);
      return this;
    }

    public Builder primaryContact(Nullable<UpdatePracticeRequestPrimaryContact> primaryContact) {
      if (primaryContact.isNull()) {
        this.primaryContact = null;
      }
      else if (primaryContact.isEmpty()) {
        this.primaryContact = Optional.empty();
      }
      else {
        this.primaryContact = Optional.of(primaryContact.get());
      }
      return this;
    }

    @JsonSetter(
        value = "supportEmail",
        nulls = Nulls.SKIP
    )
    public Builder supportEmail(Optional<String> supportEmail) {
      this.supportEmail = supportEmail;
      return this;
    }

    public Builder supportEmail(String supportEmail) {
      this.supportEmail = Optional.ofNullable(supportEmail);
      return this;
    }

    public Builder supportEmail(Nullable<String> supportEmail) {
      if (supportEmail.isNull()) {
        this.supportEmail = null;
      }
      else if (supportEmail.isEmpty()) {
        this.supportEmail = Optional.empty();
      }
      else {
        this.supportEmail = Optional.of(supportEmail.get());
      }
      return this;
    }

    @JsonSetter(
        value = "supportPhone",
        nulls = Nulls.SKIP
    )
    public Builder supportPhone(Optional<String> supportPhone) {
      this.supportPhone = supportPhone;
      return this;
    }

    public Builder supportPhone(String supportPhone) {
      this.supportPhone = Optional.ofNullable(supportPhone);
      return this;
    }

    public Builder supportPhone(Nullable<String> supportPhone) {
      if (supportPhone.isNull()) {
        this.supportPhone = null;
      }
      else if (supportPhone.isEmpty()) {
        this.supportPhone = Optional.empty();
      }
      else {
        this.supportPhone = Optional.of(supportPhone.get());
      }
      return this;
    }

    /**
     * <p>Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.</p>
     */
    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public Builder timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    public Builder timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    public Builder timezone(Nullable<String> timezone) {
      if (timezone.isNull()) {
        this.timezone = null;
      }
      else if (timezone.isEmpty()) {
        this.timezone = Optional.empty();
      }
      else {
        this.timezone = Optional.of(timezone.get());
      }
      return this;
    }

    public UpdatePracticeRequest build() {
      return new UpdatePracticeRequest(idempotencyKey, liveEnabled, address, attestations, complianceContact, externalId, legalName, metadata, name, prescribers, primaryContact, supportEmail, supportPhone, timezone, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
