/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.team.requests;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RevokePracticeTeamInvitationRequest.Builder.class
)
public final class RevokePracticeTeamInvitationRequest {
  private final String idempotencyKey;

  private final Map<String, Object> additionalProperties;

  private RevokePracticeTeamInvitationRequest(String idempotencyKey,
      Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public String getIdempotencyKey() {
    return idempotencyKey;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RevokePracticeTeamInvitationRequest && equalTo((RevokePracticeTeamInvitationRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RevokePracticeTeamInvitationRequest other) {
    return idempotencyKey.equals(other.idempotencyKey);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdempotencyKeyStage builder() {
    return new Builder();
  }

  public interface IdempotencyKeyStage {
    _FinalStage idempotencyKey(@NotNull String idempotencyKey);

    Builder from(RevokePracticeTeamInvitationRequest other);
  }

  public interface _FinalStage {
    RevokePracticeTeamInvitationRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdempotencyKeyStage, _FinalStage {
    private String idempotencyKey;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RevokePracticeTeamInvitationRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      return this;
    }

    @java.lang.Override
    public _FinalStage idempotencyKey(@NotNull String idempotencyKey) {
      this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
      return this;
    }

    @java.lang.Override
    public RevokePracticeTeamInvitationRequest build() {
      return new RevokePracticeTeamInvitationRequest(idempotencyKey, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
