/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class AffinityClientException extends RuntimeException {
  public AffinityClientException(String message) {
    super(message);
  }

  public AffinityClientException(String message, Exception e) {
    super(message, e);
  }
}
