/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.locations;

import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.resources.locations.requests.ArchivePracticeLocationRequest;
import com.affinity.api.resources.locations.requests.CreatePracticeLocationRequest;
import com.affinity.api.resources.locations.requests.GetPracticeLocationRequest;
import com.affinity.api.resources.locations.requests.ListPracticeLocationsRequest;
import com.affinity.api.resources.locations.requests.UpdatePracticeLocationRequest;
import com.affinity.api.types.ArchivePracticeLocationResponse;
import com.affinity.api.types.CreatePracticeLocationResponse;
import com.affinity.api.types.GetPracticeLocationResponse;
import com.affinity.api.types.ListPracticeLocationsResponse;
import com.affinity.api.types.UpdatePracticeLocationResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncLocationsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawLocationsClient rawClient;

  public AsyncLocationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawLocationsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawLocationsClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<ListPracticeLocationsResponse> listPracticeLocations(String practiceId) {
    return this.rawClient.listPracticeLocations(practiceId).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<ListPracticeLocationsResponse> listPracticeLocations(String practiceId,
      RequestOptions requestOptions) {
    return this.rawClient.listPracticeLocations(practiceId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<ListPracticeLocationsResponse> listPracticeLocations(String practiceId,
      ListPracticeLocationsRequest request) {
    return this.rawClient.listPracticeLocations(practiceId, request).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<ListPracticeLocationsResponse> listPracticeLocations(String practiceId,
      ListPracticeLocationsRequest request, RequestOptions requestOptions) {
    return this.rawClient.listPracticeLocations(practiceId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.
   */
  public CompletableFuture<CreatePracticeLocationResponse> createPracticeLocation(String practiceId,
      CreatePracticeLocationRequest request) {
    return this.rawClient.createPracticeLocation(practiceId, request).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.
   */
  public CompletableFuture<CreatePracticeLocationResponse> createPracticeLocation(String practiceId,
      CreatePracticeLocationRequest request, RequestOptions requestOptions) {
    return this.rawClient.createPracticeLocation(practiceId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read. Returns one active or archived location in the authorized practice.
   */
  public CompletableFuture<GetPracticeLocationResponse> getPracticeLocation(String practiceId,
      String locationId) {
    return this.rawClient.getPracticeLocation(practiceId, locationId).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read. Returns one active or archived location in the authorized practice.
   */
  public CompletableFuture<GetPracticeLocationResponse> getPracticeLocation(String practiceId,
      String locationId, RequestOptions requestOptions) {
    return this.rawClient.getPracticeLocation(practiceId, locationId, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read. Returns one active or archived location in the authorized practice.
   */
  public CompletableFuture<GetPracticeLocationResponse> getPracticeLocation(String practiceId,
      String locationId, GetPracticeLocationRequest request) {
    return this.rawClient.getPracticeLocation(practiceId, locationId, request).thenApply(response -> response.body());
  }

  /**
   * Requires locations:read. Returns one active or archived location in the authorized practice.
   */
  public CompletableFuture<GetPracticeLocationResponse> getPracticeLocation(String practiceId,
      String locationId, GetPracticeLocationRequest request, RequestOptions requestOptions) {
    return this.rawClient.getPracticeLocation(practiceId, locationId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.
   */
  public CompletableFuture<UpdatePracticeLocationResponse> updatePracticeLocation(String practiceId,
      String locationId, UpdatePracticeLocationRequest request) {
    return this.rawClient.updatePracticeLocation(practiceId, locationId, request).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.
   */
  public CompletableFuture<UpdatePracticeLocationResponse> updatePracticeLocation(String practiceId,
      String locationId, UpdatePracticeLocationRequest request, RequestOptions requestOptions) {
    return this.rawClient.updatePracticeLocation(practiceId, locationId, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.
   */
  public CompletableFuture<ArchivePracticeLocationResponse> archivePracticeLocation(
      String practiceId, String locationId, ArchivePracticeLocationRequest request) {
    return this.rawClient.archivePracticeLocation(practiceId, locationId, request).thenApply(response -> response.body());
  }

  /**
   * Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.
   */
  public CompletableFuture<ArchivePracticeLocationResponse> archivePracticeLocation(
      String practiceId, String locationId, ArchivePracticeLocationRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.archivePracticeLocation(practiceId, locationId, request, requestOptions).thenApply(response -> response.body());
  }
}
