/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.locations;

import com.affinity.api.core.AffinityClientApiException;
import com.affinity.api.core.AffinityClientException;
import com.affinity.api.core.AffinityClientHttpResponse;
import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.MediaTypes;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.core.QueryStringMapper;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.core.RetryInterceptor;
import com.affinity.api.errors.BadRequestError;
import com.affinity.api.errors.ConflictError;
import com.affinity.api.errors.ForbiddenError;
import com.affinity.api.errors.NotFoundError;
import com.affinity.api.errors.TooManyRequestsError;
import com.affinity.api.errors.UnauthorizedError;
import com.affinity.api.resources.locations.requests.ArchivePracticeLocationRequest;
import com.affinity.api.resources.locations.requests.CreatePracticeLocationRequest;
import com.affinity.api.resources.locations.requests.GetPracticeLocationRequest;
import com.affinity.api.resources.locations.requests.ListPracticeLocationsRequest;
import com.affinity.api.resources.locations.requests.UpdatePracticeLocationRequest;
import com.affinity.api.types.ArchivePracticeLocationResponse;
import com.affinity.api.types.CreatePracticeLocationResponse;
import com.affinity.api.types.GetPracticeLocationResponse;
import com.affinity.api.types.ListPracticeLocationsResponse;
import com.affinity.api.types.Problem;
import com.affinity.api.types.UpdatePracticeLocationResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawLocationsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawLocationsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<AffinityClientHttpResponse<ListPracticeLocationsResponse>> listPracticeLocations(
      String practiceId) {
    return listPracticeLocations(practiceId,ListPracticeLocationsRequest.builder().build());
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<AffinityClientHttpResponse<ListPracticeLocationsResponse>> listPracticeLocations(
      String practiceId, RequestOptions requestOptions) {
    return listPracticeLocations(practiceId,ListPracticeLocationsRequest.builder().build(),requestOptions);
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<AffinityClientHttpResponse<ListPracticeLocationsResponse>> listPracticeLocations(
      String practiceId, ListPracticeLocationsRequest request) {
    return listPracticeLocations(practiceId,request,null);
  }

  /**
   * Requires locations:read on a practice key or an authorized platform key. Lists active and archived locations by name, with cursor pagination. Use status to filter. Location records are shared between Test and Live for the same practice.
   */
  public CompletableFuture<AffinityClientHttpResponse<ListPracticeLocationsResponse>> listPracticeLocations(
      String practiceId, ListPracticeLocationsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/practices")
      .addPathSegment(practiceId)
      .addPathSegments("locations");if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getStartingAfter().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "startingAfter", request.getStartingAfter().get(), false);
      }
      if (request.getEndingBefore().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "endingBefore", request.getEndingBefore().get(), false);
      }
      if (request.getStatus().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      CompletableFuture<AffinityClientHttpResponse<ListPracticeLocationsResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListPracticeLocationsResponse.class), response));
              return;
            }
            try {
              switch (response.code()) {
                case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
                case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
                case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
                case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
                case 409:future.completeExceptionally(new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
                case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (JsonProcessingException e) {
            future.completeExceptionally(new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e));
          }
          catch (IOException e) {
            future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.
     */
    public CompletableFuture<AffinityClientHttpResponse<CreatePracticeLocationResponse>> createPracticeLocation(
        String practiceId, CreatePracticeLocationRequest request) {
      return createPracticeLocation(practiceId,request,null);
    }

    /**
     * Requires locations:write and Idempotency-Key for API keys. Creates an active location with a unique name in this practice. Locations are shared between Test and Live. Use the returned ID for Team location access.
     */
    public CompletableFuture<AffinityClientHttpResponse<CreatePracticeLocationResponse>> createPracticeLocation(
        String practiceId, CreatePracticeLocationRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("v1/practices")
        .addPathSegment(practiceId)
        .addPathSegments("locations");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(Exception e) {
          throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        CompletableFuture<AffinityClientHttpResponse<CreatePracticeLocationResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CreatePracticeLocationResponse.class), response));
                return;
              }
              try {
                switch (response.code()) {
                  case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                  case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                  case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                  case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                  case 409:future.completeExceptionally(new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                  case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                  return;
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (JsonProcessingException e) {
              future.completeExceptionally(new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e));
            }
            catch (IOException e) {
              future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Requires locations:read. Returns one active or archived location in the authorized practice.
       */
      public CompletableFuture<AffinityClientHttpResponse<GetPracticeLocationResponse>> getPracticeLocation(
          String practiceId, String locationId) {
        return getPracticeLocation(practiceId,locationId,GetPracticeLocationRequest.builder().build());
      }

      /**
       * Requires locations:read. Returns one active or archived location in the authorized practice.
       */
      public CompletableFuture<AffinityClientHttpResponse<GetPracticeLocationResponse>> getPracticeLocation(
          String practiceId, String locationId, RequestOptions requestOptions) {
        return getPracticeLocation(practiceId,locationId,GetPracticeLocationRequest.builder().build(),requestOptions);
      }

      /**
       * Requires locations:read. Returns one active or archived location in the authorized practice.
       */
      public CompletableFuture<AffinityClientHttpResponse<GetPracticeLocationResponse>> getPracticeLocation(
          String practiceId, String locationId, GetPracticeLocationRequest request) {
        return getPracticeLocation(practiceId,locationId,request,null);
      }

      /**
       * Requires locations:read. Returns one active or archived location in the authorized practice.
       */
      public CompletableFuture<AffinityClientHttpResponse<GetPracticeLocationResponse>> getPracticeLocation(
          String practiceId, String locationId, GetPracticeLocationRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("v1/practices")
          .addPathSegment(practiceId)
          .addPathSegments("locations")
          .addPathSegment(locationId);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          CompletableFuture<AffinityClientHttpResponse<GetPracticeLocationResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetPracticeLocationResponse.class), response));
                  return;
                }
                try {
                  switch (response.code()) {
                    case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                    case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                    case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                    case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                    case 409:future.completeExceptionally(new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                    case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (JsonProcessingException e) {
                future.completeExceptionally(new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e));
              }
              catch (IOException e) {
                future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.
         */
        public CompletableFuture<AffinityClientHttpResponse<UpdatePracticeLocationResponse>> updatePracticeLocation(
            String practiceId, String locationId, UpdatePracticeLocationRequest request) {
          return updatePracticeLocation(practiceId,locationId,request,null);
        }

        /**
         * Requires locations:write and Idempotency-Key for API keys. Updates only supplied fields; null clears optional contact and address fields. Archived locations cannot be updated. Changes apply to both Test and Live.
         */
        public CompletableFuture<AffinityClientHttpResponse<UpdatePracticeLocationResponse>> updatePracticeLocation(
            String practiceId, String locationId, UpdatePracticeLocationRequest request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("v1/practices")
            .addPathSegment(practiceId)
            .addPathSegments("locations")
            .addPathSegment(locationId);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(Exception e) {
              throw new RuntimeException(e);
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("PATCH", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json");
            _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
              okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
            }
            CompletableFuture<AffinityClientHttpResponse<UpdatePracticeLocationResponse>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdatePracticeLocationResponse.class), response));
                    return;
                  }
                  try {
                    switch (response.code()) {
                      case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                      case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                      case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                      case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                      case 409:future.completeExceptionally(new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                      case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (JsonProcessingException e) {
                  future.completeExceptionally(new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e));
                }
                catch (IOException e) {
                  future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.
           */
          public CompletableFuture<AffinityClientHttpResponse<ArchivePracticeLocationResponse>> archivePracticeLocation(
              String practiceId, String locationId, ArchivePracticeLocationRequest request) {
            return archivePracticeLocation(practiceId,locationId,request,null);
          }

          /**
           * Requires locations:write and Idempotency-Key for API keys. Retains the location and historical associations. Archived locations cannot receive new Team assignments. Repeating archive returns the archived location. Changes apply to both Test and Live.
           */
          public CompletableFuture<AffinityClientHttpResponse<ArchivePracticeLocationResponse>> archivePracticeLocation(
              String practiceId, String locationId, ArchivePracticeLocationRequest request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("v1/practices")
              .addPathSegment(practiceId)
              .addPathSegments("locations")
              .addPathSegment(locationId)
              .addPathSegments("archive");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
              _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
              }
              CompletableFuture<AffinityClientHttpResponse<ArchivePracticeLocationResponse>> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      future.complete(new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ArchivePracticeLocationResponse.class), response));
                      return;
                    }
                    try {
                      switch (response.code()) {
                        case 400:future.completeExceptionally(new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                        case 401:future.completeExceptionally(new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                        case 403:future.completeExceptionally(new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                        case 404:future.completeExceptionally(new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                        case 409:future.completeExceptionally(new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                        case 429:future.completeExceptionally(new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                  }
                  catch (JsonProcessingException e) {
                    future.completeExceptionally(new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e));
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new AffinityClientException("Network error executing HTTP request", e));
                }
              });
              return future;
            }
          }
