/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.locations.requests;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePracticeLocationRequest.Builder.class
)
public final class CreatePracticeLocationRequest {
  private final String idempotencyKey;

  private final Optional<String> city;

  private final Optional<String> country;

  private final Optional<String> line1;

  private final Optional<String> line2;

  private final String name;

  private final Optional<String> phone;

  private final Optional<String> postalCode;

  private final Optional<String> state;

  private final Optional<String> timezone;

  private final Map<String, Object> additionalProperties;

  private CreatePracticeLocationRequest(String idempotencyKey, Optional<String> city,
      Optional<String> country, Optional<String> line1, Optional<String> line2, String name,
      Optional<String> phone, Optional<String> postalCode, Optional<String> state,
      Optional<String> timezone, Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.city = city;
    this.country = country;
    this.line1 = line1;
    this.line2 = line2;
    this.name = name;
    this.phone = phone;
    this.postalCode = postalCode;
    this.state = state;
    this.timezone = timezone;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public String getIdempotencyKey() {
    return idempotencyKey;
  }

  @JsonIgnore
  public Optional<String> getCity() {
    if (city == null) {
      return Optional.empty();
    }
    return city;
  }

  @JsonIgnore
  public Optional<String> getCountry() {
    if (country == null) {
      return Optional.empty();
    }
    return country;
  }

  @JsonIgnore
  public Optional<String> getLine1() {
    if (line1 == null) {
      return Optional.empty();
    }
    return line1;
  }

  @JsonIgnore
  public Optional<String> getLine2() {
    if (line2 == null) {
      return Optional.empty();
    }
    return line2;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonIgnore
  public Optional<String> getPhone() {
    if (phone == null) {
      return Optional.empty();
    }
    return phone;
  }

  @JsonIgnore
  public Optional<String> getPostalCode() {
    if (postalCode == null) {
      return Optional.empty();
    }
    return postalCode;
  }

  @JsonIgnore
  public Optional<String> getState() {
    if (state == null) {
      return Optional.empty();
    }
    return state;
  }

  /**
   * @return Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.
   */
  @JsonIgnore
  public Optional<String> getTimezone() {
    if (timezone == null) {
      return Optional.empty();
    }
    return timezone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("city")
  private Optional<String> _getCity() {
    return city;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("country")
  private Optional<String> _getCountry() {
    return country;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("line1")
  private Optional<String> _getLine1() {
    return line1;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("line2")
  private Optional<String> _getLine2() {
    return line2;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("phone")
  private Optional<String> _getPhone() {
    return phone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("postalCode")
  private Optional<String> _getPostalCode() {
    return postalCode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("state")
  private Optional<String> _getState() {
    return state;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("timezone")
  private Optional<String> _getTimezone() {
    return timezone;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePracticeLocationRequest && equalTo((CreatePracticeLocationRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePracticeLocationRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && city.equals(other.city) && country.equals(other.country) && line1.equals(other.line1) && line2.equals(other.line2) && name.equals(other.name) && phone.equals(other.phone) && postalCode.equals(other.postalCode) && state.equals(other.state) && timezone.equals(other.timezone);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.city, this.country, this.line1, this.line2, this.name, this.phone, this.postalCode, this.state, this.timezone);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdempotencyKeyStage builder() {
    return new Builder();
  }

  public interface IdempotencyKeyStage {
    NameStage idempotencyKey(@NotNull String idempotencyKey);

    Builder from(CreatePracticeLocationRequest other);
  }

  public interface NameStage {
    _FinalStage name(@NotNull String name);
  }

  public interface _FinalStage {
    CreatePracticeLocationRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage city(Optional<String> city);

    _FinalStage city(String city);

    _FinalStage city(Nullable<String> city);

    _FinalStage country(Optional<String> country);

    _FinalStage country(String country);

    _FinalStage country(Nullable<String> country);

    _FinalStage line1(Optional<String> line1);

    _FinalStage line1(String line1);

    _FinalStage line1(Nullable<String> line1);

    _FinalStage line2(Optional<String> line2);

    _FinalStage line2(String line2);

    _FinalStage line2(Nullable<String> line2);

    _FinalStage phone(Optional<String> phone);

    _FinalStage phone(String phone);

    _FinalStage phone(Nullable<String> phone);

    _FinalStage postalCode(Optional<String> postalCode);

    _FinalStage postalCode(String postalCode);

    _FinalStage postalCode(Nullable<String> postalCode);

    _FinalStage state(Optional<String> state);

    _FinalStage state(String state);

    _FinalStage state(Nullable<String> state);

    /**
     * <p>Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.</p>
     */
    _FinalStage timezone(Optional<String> timezone);

    _FinalStage timezone(String timezone);

    _FinalStage timezone(Nullable<String> timezone);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdempotencyKeyStage, NameStage, _FinalStage {
    private String idempotencyKey;

    private String name;

    private Optional<String> timezone = Optional.empty();

    private Optional<String> state = Optional.empty();

    private Optional<String> postalCode = Optional.empty();

    private Optional<String> phone = Optional.empty();

    private Optional<String> line2 = Optional.empty();

    private Optional<String> line1 = Optional.empty();

    private Optional<String> country = Optional.empty();

    private Optional<String> city = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePracticeLocationRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      city(other.getCity());
      country(other.getCountry());
      line1(other.getLine1());
      line2(other.getLine2());
      name(other.getName());
      phone(other.getPhone());
      postalCode(other.getPostalCode());
      state(other.getState());
      timezone(other.getTimezone());
      return this;
    }

    @java.lang.Override
    public NameStage idempotencyKey(@NotNull String idempotencyKey) {
      this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public _FinalStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timezone(Nullable<String> timezone) {
      if (timezone.isNull()) {
        this.timezone = null;
      }
      else if (timezone.isEmpty()) {
        this.timezone = Optional.empty();
      }
      else {
        this.timezone = Optional.of(timezone.get());
      }
      return this;
    }

    /**
     * <p>Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    /**
     * <p>Optional IANA timezone override. Omit to leave unchanged; null clears it. No timezone is inferred when creating a record.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public _FinalStage timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    @java.lang.Override
    public _FinalStage state(Nullable<String> state) {
      if (state.isNull()) {
        this.state = null;
      }
      else if (state.isEmpty()) {
        this.state = Optional.empty();
      }
      else {
        this.state = Optional.of(state.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage state(String state) {
      this.state = Optional.ofNullable(state);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "state",
        nulls = Nulls.SKIP
    )
    public _FinalStage state(Optional<String> state) {
      this.state = state;
      return this;
    }

    @java.lang.Override
    public _FinalStage postalCode(Nullable<String> postalCode) {
      if (postalCode.isNull()) {
        this.postalCode = null;
      }
      else if (postalCode.isEmpty()) {
        this.postalCode = Optional.empty();
      }
      else {
        this.postalCode = Optional.of(postalCode.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage postalCode(String postalCode) {
      this.postalCode = Optional.ofNullable(postalCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "postalCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage postalCode(Optional<String> postalCode) {
      this.postalCode = postalCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage phone(Nullable<String> phone) {
      if (phone.isNull()) {
        this.phone = null;
      }
      else if (phone.isEmpty()) {
        this.phone = Optional.empty();
      }
      else {
        this.phone = Optional.of(phone.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage phone(String phone) {
      this.phone = Optional.ofNullable(phone);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "phone",
        nulls = Nulls.SKIP
    )
    public _FinalStage phone(Optional<String> phone) {
      this.phone = phone;
      return this;
    }

    @java.lang.Override
    public _FinalStage line2(Nullable<String> line2) {
      if (line2.isNull()) {
        this.line2 = null;
      }
      else if (line2.isEmpty()) {
        this.line2 = Optional.empty();
      }
      else {
        this.line2 = Optional.of(line2.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage line2(String line2) {
      this.line2 = Optional.ofNullable(line2);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "line2",
        nulls = Nulls.SKIP
    )
    public _FinalStage line2(Optional<String> line2) {
      this.line2 = line2;
      return this;
    }

    @java.lang.Override
    public _FinalStage line1(Nullable<String> line1) {
      if (line1.isNull()) {
        this.line1 = null;
      }
      else if (line1.isEmpty()) {
        this.line1 = Optional.empty();
      }
      else {
        this.line1 = Optional.of(line1.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage line1(String line1) {
      this.line1 = Optional.ofNullable(line1);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "line1",
        nulls = Nulls.SKIP
    )
    public _FinalStage line1(Optional<String> line1) {
      this.line1 = line1;
      return this;
    }

    @java.lang.Override
    public _FinalStage country(Nullable<String> country) {
      if (country.isNull()) {
        this.country = null;
      }
      else if (country.isEmpty()) {
        this.country = Optional.empty();
      }
      else {
        this.country = Optional.of(country.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public _FinalStage country(Optional<String> country) {
      this.country = country;
      return this;
    }

    @java.lang.Override
    public _FinalStage city(Nullable<String> city) {
      if (city.isNull()) {
        this.city = null;
      }
      else if (city.isEmpty()) {
        this.city = Optional.empty();
      }
      else {
        this.city = Optional.of(city.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage city(String city) {
      this.city = Optional.ofNullable(city);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "city",
        nulls = Nulls.SKIP
    )
    public _FinalStage city(Optional<String> city) {
      this.city = city;
      return this;
    }

    @java.lang.Override
    public CreatePracticeLocationRequest build() {
      return new CreatePracticeLocationRequest(idempotencyKey, city, country, line1, line2, name, phone, postalCode, state, timezone, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
