/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.catalog.items;

import com.affinity.api.core.AffinityClientApiException;
import com.affinity.api.core.AffinityClientException;
import com.affinity.api.core.AffinityClientHttpResponse;
import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.core.QueryStringMapper;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.core.RetryInterceptor;
import com.affinity.api.errors.BadRequestError;
import com.affinity.api.errors.ConflictError;
import com.affinity.api.errors.ForbiddenError;
import com.affinity.api.errors.NotFoundError;
import com.affinity.api.errors.TooManyRequestsError;
import com.affinity.api.errors.UnauthorizedError;
import com.affinity.api.errors.UnprocessableEntityError;
import com.affinity.api.resources.catalog.items.requests.ListItemsRequest;
import com.affinity.api.types.ListCatalogItemsResponse;
import com.affinity.api.types.Problem;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawItemsClient {
  protected final ClientOptions clientOptions;

  public RawItemsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Lists catalog items for the authenticated account and mode. Use view=medications for priced prescription groups with offer counts, pharmacy counts, and strengths; the default view=offers returns individual offers. Use relatedToCatalogItemId to find offers for the same medication and route. When practiceId is supplied, a practice price overrides the platform price and missing overrides inherit the platform price.
   */
  public AffinityClientHttpResponse<ListCatalogItemsResponse> list() {
    return list(ListItemsRequest.builder().build());
  }

  /**
   * Lists catalog items for the authenticated account and mode. Use view=medications for priced prescription groups with offer counts, pharmacy counts, and strengths; the default view=offers returns individual offers. Use relatedToCatalogItemId to find offers for the same medication and route. When practiceId is supplied, a practice price overrides the platform price and missing overrides inherit the platform price.
   */
  public AffinityClientHttpResponse<ListCatalogItemsResponse> list(RequestOptions requestOptions) {
    return list(ListItemsRequest.builder().build(),requestOptions);
  }

  /**
   * Lists catalog items for the authenticated account and mode. Use view=medications for priced prescription groups with offer counts, pharmacy counts, and strengths; the default view=offers returns individual offers. Use relatedToCatalogItemId to find offers for the same medication and route. When practiceId is supplied, a practice price overrides the platform price and missing overrides inherit the platform price.
   */
  public AffinityClientHttpResponse<ListCatalogItemsResponse> list(ListItemsRequest request) {
    return list(request,null);
  }

  /**
   * Lists catalog items for the authenticated account and mode. Use view=medications for priced prescription groups with offer counts, pharmacy counts, and strengths; the default view=offers returns individual offers. Use relatedToCatalogItemId to find offers for the same medication and route. When practiceId is supplied, a practice price overrides the platform price and missing overrides inherit the platform price.
   */
  public AffinityClientHttpResponse<ListCatalogItemsResponse> list(ListItemsRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/catalog/items");if (request.getView().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "view", request.getView().get(), false);
      }
      if (request.getRelatedToCatalogItemId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "relatedToCatalogItemId", request.getRelatedToCatalogItemId().get(), false);
      }
      if (request.getCatalogKind().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "catalogKind", request.getCatalogKind().get(), false);
      }
      if (request.getSort().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "sort", request.getSort().get(), false);
      }
      if (request.getCatalogItemId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "catalogItemId", request.getCatalogItemId().get(), false);
      }
      if (request.getAvailability().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "availability", request.getAvailability().get(), false);
      }
      if (request.getPharmacyIds().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "pharmacyIds", request.getPharmacyIds().get(), false);
      }
      if (request.getDosageForms().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "dosageForms", request.getDosageForms().get(), false);
      }
      if (request.getEndingBefore().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "endingBefore", request.getEndingBefore().get(), false);
      }
      if (request.getHideControlledSubstances().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "hideControlledSubstances", request.getHideControlledSubstances().get(), false);
      }
      if (request.getHideUnpriced().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "hideUnpriced", request.getHideUnpriced().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getOrgId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "orgId", request.getOrgId().get(), false);
      }
      if (request.getPracticeId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "practiceId", request.getPracticeId().get(), false);
      }
      if (request.getQuery().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "query", request.getQuery().get(), false);
      }
      if (request.getRequirement().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "requirement", request.getRequirement().get(), false);
      }
      if (request.getRoutes().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "routes", request.getRoutes().get(), false);
      }
      if (request.getStartingAfter().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "startingAfter", request.getStartingAfter().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListCatalogItemsResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 403:throw new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 409:throw new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 422:throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new AffinityClientException("Network error executing HTTP request", e);
      }
    }
  }
