/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.errors;

import com.affinity.api.core.AffinityClientApiException;
import com.affinity.api.types.Problem;
import okhttp3.Response;

public final class NotFoundError extends AffinityClientApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Problem body;

  public NotFoundError(Problem body) {
    super("NotFoundError", 404, body);
    this.body = body;
  }

  public NotFoundError(Problem body, Response rawResponse) {
    super("NotFoundError", 404, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Problem body() {
    return this.body;
  }
}
