/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.patients.addresses;

import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.resources.patients.addresses.requests.ArchiveAddressesRequest;
import com.affinity.api.resources.patients.addresses.requests.CreatePatientAddressRequest;
import com.affinity.api.resources.patients.addresses.requests.ListAddressesRequest;
import com.affinity.api.resources.patients.addresses.requests.SetDefaultAddressesRequest;
import com.affinity.api.resources.patients.addresses.requests.UpdatePatientAddressRequest;
import com.affinity.api.types.ArchivePatientAddressResponse;
import com.affinity.api.types.CreatePatientAddressResponse;
import com.affinity.api.types.ListPatientAddressesResponse;
import com.affinity.api.types.SetDefaultPatientAddressResponse;
import com.affinity.api.types.UpdatePatientAddressResponse;
import java.lang.String;

public class AddressesClient {
  protected final ClientOptions clientOptions;

  private final RawAddressesClient rawClient;

  public AddressesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawAddressesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawAddressesClient withRawResponse() {
    return this.rawClient;
  }

  public ListPatientAddressesResponse list(String practiceId, String patientId) {
    return this.rawClient.list(practiceId, patientId).body();
  }

  public ListPatientAddressesResponse list(String practiceId, String patientId,
      RequestOptions requestOptions) {
    return this.rawClient.list(practiceId, patientId, requestOptions).body();
  }

  public ListPatientAddressesResponse list(String practiceId, String patientId,
      ListAddressesRequest request) {
    return this.rawClient.list(practiceId, patientId, request).body();
  }

  public ListPatientAddressesResponse list(String practiceId, String patientId,
      ListAddressesRequest request, RequestOptions requestOptions) {
    return this.rawClient.list(practiceId, patientId, request, requestOptions).body();
  }

  /**
   * Returns the existing active address for a normalized duplicate. The first address becomes the default. API keys require Idempotency-Key.
   */
  public CreatePatientAddressResponse create(String practiceId, String patientId,
      CreatePatientAddressRequest request) {
    return this.rawClient.create(practiceId, patientId, request).body();
  }

  /**
   * Returns the existing active address for a normalized duplicate. The first address becomes the default. API keys require Idempotency-Key.
   */
  public CreatePatientAddressResponse create(String practiceId, String patientId,
      CreatePatientAddressRequest request, RequestOptions requestOptions) {
    return this.rawClient.create(practiceId, patientId, request, requestOptions).body();
  }

  /**
   * Preserves the address ID and history. Archiving the default selects the oldest remaining active address. Existing orders remain unchanged.
   */
  public ArchivePatientAddressResponse archive(String practiceId, String patientId,
      String addressId) {
    return this.rawClient.archive(practiceId, patientId, addressId).body();
  }

  /**
   * Preserves the address ID and history. Archiving the default selects the oldest remaining active address. Existing orders remain unchanged.
   */
  public ArchivePatientAddressResponse archive(String practiceId, String patientId,
      String addressId, RequestOptions requestOptions) {
    return this.rawClient.archive(practiceId, patientId, addressId, requestOptions).body();
  }

  /**
   * Preserves the address ID and history. Archiving the default selects the oldest remaining active address. Existing orders remain unchanged.
   */
  public ArchivePatientAddressResponse archive(String practiceId, String patientId,
      String addressId, ArchiveAddressesRequest request) {
    return this.rawClient.archive(practiceId, patientId, addressId, request).body();
  }

  /**
   * Preserves the address ID and history. Archiving the default selects the oldest remaining active address. Existing orders remain unchanged.
   */
  public ArchivePatientAddressResponse archive(String practiceId, String patientId,
      String addressId, ArchiveAddressesRequest request, RequestOptions requestOptions) {
    return this.rawClient.archive(practiceId, patientId, addressId, request, requestOptions).body();
  }

  public UpdatePatientAddressResponse update(String practiceId, String patientId,
      String addressId) {
    return this.rawClient.update(practiceId, patientId, addressId).body();
  }

  public UpdatePatientAddressResponse update(String practiceId, String patientId, String addressId,
      RequestOptions requestOptions) {
    return this.rawClient.update(practiceId, patientId, addressId, requestOptions).body();
  }

  public UpdatePatientAddressResponse update(String practiceId, String patientId, String addressId,
      UpdatePatientAddressRequest request) {
    return this.rawClient.update(practiceId, patientId, addressId, request).body();
  }

  public UpdatePatientAddressResponse update(String practiceId, String patientId, String addressId,
      UpdatePatientAddressRequest request, RequestOptions requestOptions) {
    return this.rawClient.update(practiceId, patientId, addressId, request, requestOptions).body();
  }

  /**
   * Changes delivery selection for future drafts, without changing patient clinical location or existing signed orders.
   */
  public SetDefaultPatientAddressResponse setDefault(String practiceId, String patientId,
      String addressId) {
    return this.rawClient.setDefault(practiceId, patientId, addressId).body();
  }

  /**
   * Changes delivery selection for future drafts, without changing patient clinical location or existing signed orders.
   */
  public SetDefaultPatientAddressResponse setDefault(String practiceId, String patientId,
      String addressId, RequestOptions requestOptions) {
    return this.rawClient.setDefault(practiceId, patientId, addressId, requestOptions).body();
  }

  /**
   * Changes delivery selection for future drafts, without changing patient clinical location or existing signed orders.
   */
  public SetDefaultPatientAddressResponse setDefault(String practiceId, String patientId,
      String addressId, SetDefaultAddressesRequest request) {
    return this.rawClient.setDefault(practiceId, patientId, addressId, request).body();
  }

  /**
   * Changes delivery selection for future drafts, without changing patient clinical location or existing signed orders.
   */
  public SetDefaultPatientAddressResponse setDefault(String practiceId, String patientId,
      String addressId, SetDefaultAddressesRequest request, RequestOptions requestOptions) {
    return this.rawClient.setDefault(practiceId, patientId, addressId, request, requestOptions).body();
  }
}
