/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.team.prescribers.requests;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.resources.team.prescribers.types.UpdatePracticeTeamPrescriberRequestAddress;
import com.affinity.api.resources.team.prescribers.types.UpdatePracticeTeamPrescriberRequestPracticeStatus;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdatePracticeTeamPrescriberRequest.Builder.class
)
public final class UpdatePracticeTeamPrescriberRequest {
  private final Optional<String> idempotencyKey;

  private final Optional<String> displayName;

  private final Optional<String> legalName;

  private final Optional<String> credentials;

  private final Optional<String> phone;

  private final Optional<UpdatePracticeTeamPrescriberRequestAddress> address;

  private final Optional<UpdatePracticeTeamPrescriberRequestPracticeStatus> practiceStatus;

  private final Map<String, Object> additionalProperties;

  private UpdatePracticeTeamPrescriberRequest(Optional<String> idempotencyKey,
      Optional<String> displayName, Optional<String> legalName, Optional<String> credentials,
      Optional<String> phone, Optional<UpdatePracticeTeamPrescriberRequestAddress> address,
      Optional<UpdatePracticeTeamPrescriberRequestPracticeStatus> practiceStatus,
      Map<String, Object> additionalProperties) {
    this.idempotencyKey = idempotencyKey;
    this.displayName = displayName;
    this.legalName = legalName;
    this.credentials = credentials;
    this.phone = phone;
    this.address = address;
    this.practiceStatus = practiceStatus;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.
   */
  @JsonIgnore
  public Optional<String> getIdempotencyKey() {
    return idempotencyKey;
  }

  @JsonIgnore
  public Optional<String> getDisplayName() {
    if (displayName == null) {
      return Optional.empty();
    }
    return displayName;
  }

  @JsonIgnore
  public Optional<String> getLegalName() {
    if (legalName == null) {
      return Optional.empty();
    }
    return legalName;
  }

  @JsonIgnore
  public Optional<String> getCredentials() {
    if (credentials == null) {
      return Optional.empty();
    }
    return credentials;
  }

  @JsonIgnore
  public Optional<String> getPhone() {
    if (phone == null) {
      return Optional.empty();
    }
    return phone;
  }

  @JsonIgnore
  public Optional<UpdatePracticeTeamPrescriberRequestAddress> getAddress() {
    if (address == null) {
      return Optional.empty();
    }
    return address;
  }

  @JsonProperty("practiceStatus")
  public Optional<UpdatePracticeTeamPrescriberRequestPracticeStatus> getPracticeStatus() {
    return practiceStatus;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("displayName")
  private Optional<String> _getDisplayName() {
    return displayName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("legalName")
  private Optional<String> _getLegalName() {
    return legalName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("credentials")
  private Optional<String> _getCredentials() {
    return credentials;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("phone")
  private Optional<String> _getPhone() {
    return phone;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("address")
  private Optional<UpdatePracticeTeamPrescriberRequestAddress> _getAddress() {
    return address;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdatePracticeTeamPrescriberRequest && equalTo((UpdatePracticeTeamPrescriberRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(UpdatePracticeTeamPrescriberRequest other) {
    return idempotencyKey.equals(other.idempotencyKey) && displayName.equals(other.displayName) && legalName.equals(other.legalName) && credentials.equals(other.credentials) && phone.equals(other.phone) && address.equals(other.address) && practiceStatus.equals(other.practiceStatus);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.idempotencyKey, this.displayName, this.legalName, this.credentials, this.phone, this.address, this.practiceStatus);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> idempotencyKey = Optional.empty();

    private Optional<String> displayName = Optional.empty();

    private Optional<String> legalName = Optional.empty();

    private Optional<String> credentials = Optional.empty();

    private Optional<String> phone = Optional.empty();

    private Optional<UpdatePracticeTeamPrescriberRequestAddress> address = Optional.empty();

    private Optional<UpdatePracticeTeamPrescriberRequestPracticeStatus> practiceStatus = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(UpdatePracticeTeamPrescriberRequest other) {
      idempotencyKey(other.getIdempotencyKey());
      displayName(other.getDisplayName());
      legalName(other.getLegalName());
      credentials(other.getCredentials());
      phone(other.getPhone());
      address(other.getAddress());
      practiceStatus(other.getPracticeStatus());
      return this;
    }

    /**
     * <p>Optional in the SDK. A fresh key is generated once per call when omitted. Supply a stable key to retry across calls.</p>
     */
    public Builder idempotencyKey(Optional<String> idempotencyKey) {
      this.idempotencyKey = idempotencyKey;
      return this;
    }

    public Builder idempotencyKey(String idempotencyKey) {
      this.idempotencyKey = Optional.ofNullable(idempotencyKey);
      return this;
    }

    @JsonSetter(
        value = "displayName",
        nulls = Nulls.SKIP
    )
    public Builder displayName(Optional<String> displayName) {
      this.displayName = displayName;
      return this;
    }

    public Builder displayName(String displayName) {
      this.displayName = Optional.ofNullable(displayName);
      return this;
    }

    public Builder displayName(Nullable<String> displayName) {
      if (displayName.isNull()) {
        this.displayName = null;
      }
      else if (displayName.isEmpty()) {
        this.displayName = Optional.empty();
      }
      else {
        this.displayName = Optional.of(displayName.get());
      }
      return this;
    }

    @JsonSetter(
        value = "legalName",
        nulls = Nulls.SKIP
    )
    public Builder legalName(Optional<String> legalName) {
      this.legalName = legalName;
      return this;
    }

    public Builder legalName(String legalName) {
      this.legalName = Optional.ofNullable(legalName);
      return this;
    }

    public Builder legalName(Nullable<String> legalName) {
      if (legalName.isNull()) {
        this.legalName = null;
      }
      else if (legalName.isEmpty()) {
        this.legalName = Optional.empty();
      }
      else {
        this.legalName = Optional.of(legalName.get());
      }
      return this;
    }

    @JsonSetter(
        value = "credentials",
        nulls = Nulls.SKIP
    )
    public Builder credentials(Optional<String> credentials) {
      this.credentials = credentials;
      return this;
    }

    public Builder credentials(String credentials) {
      this.credentials = Optional.ofNullable(credentials);
      return this;
    }

    public Builder credentials(Nullable<String> credentials) {
      if (credentials.isNull()) {
        this.credentials = null;
      }
      else if (credentials.isEmpty()) {
        this.credentials = Optional.empty();
      }
      else {
        this.credentials = Optional.of(credentials.get());
      }
      return this;
    }

    @JsonSetter(
        value = "phone",
        nulls = Nulls.SKIP
    )
    public Builder phone(Optional<String> phone) {
      this.phone = phone;
      return this;
    }

    public Builder phone(String phone) {
      this.phone = Optional.ofNullable(phone);
      return this;
    }

    public Builder phone(Nullable<String> phone) {
      if (phone.isNull()) {
        this.phone = null;
      }
      else if (phone.isEmpty()) {
        this.phone = Optional.empty();
      }
      else {
        this.phone = Optional.of(phone.get());
      }
      return this;
    }

    @JsonSetter(
        value = "address",
        nulls = Nulls.SKIP
    )
    public Builder address(Optional<UpdatePracticeTeamPrescriberRequestAddress> address) {
      this.address = address;
      return this;
    }

    public Builder address(UpdatePracticeTeamPrescriberRequestAddress address) {
      this.address = Optional.ofNullable(address);
      return this;
    }

    public Builder address(Nullable<UpdatePracticeTeamPrescriberRequestAddress> address) {
      if (address.isNull()) {
        this.address = null;
      }
      else if (address.isEmpty()) {
        this.address = Optional.empty();
      }
      else {
        this.address = Optional.of(address.get());
      }
      return this;
    }

    @JsonSetter(
        value = "practiceStatus",
        nulls = Nulls.SKIP
    )
    public Builder practiceStatus(
        Optional<UpdatePracticeTeamPrescriberRequestPracticeStatus> practiceStatus) {
      this.practiceStatus = practiceStatus;
      return this;
    }

    public Builder practiceStatus(
        UpdatePracticeTeamPrescriberRequestPracticeStatus practiceStatus) {
      this.practiceStatus = Optional.ofNullable(practiceStatus);
      return this;
    }

    public UpdatePracticeTeamPrescriberRequest build() {
      return new UpdatePracticeTeamPrescriberRequest(idempotencyKey, displayName, legalName, credentials, phone, address, practiceStatus, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
