/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AddOrderPrescriptionResponsePrescriptionsItem.Builder.class
)
public final class AddOrderPrescriptionResponsePrescriptionsItem {
  private final String id;

  private final Optional<String> externalPrescriptionId;

  private final int version;

  private final Map<String, Object> additionalProperties;

  private AddOrderPrescriptionResponsePrescriptionsItem(String id,
      Optional<String> externalPrescriptionId, int version,
      Map<String, Object> additionalProperties) {
    this.id = id;
    this.externalPrescriptionId = externalPrescriptionId;
    this.version = version;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonIgnore
  public Optional<String> getExternalPrescriptionId() {
    if (externalPrescriptionId == null) {
      return Optional.empty();
    }
    return externalPrescriptionId;
  }

  @JsonProperty("version")
  public int getVersion() {
    return version;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("externalPrescriptionId")
  private Optional<String> _getExternalPrescriptionId() {
    return externalPrescriptionId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AddOrderPrescriptionResponsePrescriptionsItem && equalTo((AddOrderPrescriptionResponsePrescriptionsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AddOrderPrescriptionResponsePrescriptionsItem other) {
    return id.equals(other.id) && externalPrescriptionId.equals(other.externalPrescriptionId) && version == other.version;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.externalPrescriptionId, this.version);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    VersionStage id(@NotNull String id);

    Builder from(AddOrderPrescriptionResponsePrescriptionsItem other);
  }

  public interface VersionStage {
    _FinalStage version(int version);
  }

  public interface _FinalStage {
    AddOrderPrescriptionResponsePrescriptionsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage externalPrescriptionId(Optional<String> externalPrescriptionId);

    _FinalStage externalPrescriptionId(String externalPrescriptionId);

    _FinalStage externalPrescriptionId(Nullable<String> externalPrescriptionId);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, VersionStage, _FinalStage {
    private String id;

    private int version;

    private Optional<String> externalPrescriptionId = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AddOrderPrescriptionResponsePrescriptionsItem other) {
      id(other.getId());
      externalPrescriptionId(other.getExternalPrescriptionId());
      version(other.getVersion());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public VersionStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("version")
    public _FinalStage version(int version) {
      this.version = version;
      return this;
    }

    @java.lang.Override
    public _FinalStage externalPrescriptionId(Nullable<String> externalPrescriptionId) {
      if (externalPrescriptionId.isNull()) {
        this.externalPrescriptionId = null;
      }
      else if (externalPrescriptionId.isEmpty()) {
        this.externalPrescriptionId = Optional.empty();
      }
      else {
        this.externalPrescriptionId = Optional.of(externalPrescriptionId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage externalPrescriptionId(String externalPrescriptionId) {
      this.externalPrescriptionId = Optional.ofNullable(externalPrescriptionId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "externalPrescriptionId",
        nulls = Nulls.SKIP
    )
    public _FinalStage externalPrescriptionId(Optional<String> externalPrescriptionId) {
      this.externalPrescriptionId = externalPrescriptionId;
      return this;
    }

    @java.lang.Override
    public AddOrderPrescriptionResponsePrescriptionsItem build() {
      return new AddOrderPrescriptionResponsePrescriptionsItem(id, externalPrescriptionId, version, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public String id() { return getId(); }

  public Optional<String> externalPrescriptionId() { return getExternalPrescriptionId(); }

  public int version() { return getVersion(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
