/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CancelOrderResponsePrescriptionsItemDispensing.Builder.class
)
public final class CancelOrderResponsePrescriptionsItemDispensing {
  private final boolean dispenseUponAcceptance;

  private final boolean substitutionPermitted;

  private final Optional<String> pharmacyNotes;

  private final Optional<String> requestedFillDate;

  private final Optional<String> shippingOptionId;

  private final Optional<Integer> shippingAmountCents;

  private final Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType;

  private final Map<String, Object> additionalProperties;

  private CancelOrderResponsePrescriptionsItemDispensing(boolean dispenseUponAcceptance,
      boolean substitutionPermitted, Optional<String> pharmacyNotes,
      Optional<String> requestedFillDate, Optional<String> shippingOptionId,
      Optional<Integer> shippingAmountCents,
      Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType,
      Map<String, Object> additionalProperties) {
    this.dispenseUponAcceptance = dispenseUponAcceptance;
    this.substitutionPermitted = substitutionPermitted;
    this.pharmacyNotes = pharmacyNotes;
    this.requestedFillDate = requestedFillDate;
    this.shippingOptionId = shippingOptionId;
    this.shippingAmountCents = shippingAmountCents;
    this.shippingDestinationType = shippingDestinationType;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("dispenseUponAcceptance")
  public boolean getDispenseUponAcceptance() {
    return dispenseUponAcceptance;
  }

  @JsonProperty("substitutionPermitted")
  public boolean getSubstitutionPermitted() {
    return substitutionPermitted;
  }

  @JsonIgnore
  public Optional<String> getPharmacyNotes() {
    if (pharmacyNotes == null) {
      return Optional.empty();
    }
    return pharmacyNotes;
  }

  @JsonIgnore
  public Optional<String> getRequestedFillDate() {
    if (requestedFillDate == null) {
      return Optional.empty();
    }
    return requestedFillDate;
  }

  @JsonIgnore
  public Optional<String> getShippingOptionId() {
    if (shippingOptionId == null) {
      return Optional.empty();
    }
    return shippingOptionId;
  }

  @JsonIgnore
  public Optional<Integer> getShippingAmountCents() {
    if (shippingAmountCents == null) {
      return Optional.empty();
    }
    return shippingAmountCents;
  }

  @JsonIgnore
  public Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> getShippingDestinationType(
      ) {
    if (shippingDestinationType == null) {
      return Optional.empty();
    }
    return shippingDestinationType;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("pharmacyNotes")
  private Optional<String> _getPharmacyNotes() {
    return pharmacyNotes;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("requestedFillDate")
  private Optional<String> _getRequestedFillDate() {
    return requestedFillDate;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("shippingOptionId")
  private Optional<String> _getShippingOptionId() {
    return shippingOptionId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("shippingAmountCents")
  private Optional<Integer> _getShippingAmountCents() {
    return shippingAmountCents;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("shippingDestinationType")
  private Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> _getShippingDestinationType(
      ) {
    return shippingDestinationType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CancelOrderResponsePrescriptionsItemDispensing && equalTo((CancelOrderResponsePrescriptionsItemDispensing) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CancelOrderResponsePrescriptionsItemDispensing other) {
    return dispenseUponAcceptance == other.dispenseUponAcceptance && substitutionPermitted == other.substitutionPermitted && pharmacyNotes.equals(other.pharmacyNotes) && requestedFillDate.equals(other.requestedFillDate) && shippingOptionId.equals(other.shippingOptionId) && shippingAmountCents.equals(other.shippingAmountCents) && shippingDestinationType.equals(other.shippingDestinationType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.dispenseUponAcceptance, this.substitutionPermitted, this.pharmacyNotes, this.requestedFillDate, this.shippingOptionId, this.shippingAmountCents, this.shippingDestinationType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DispenseUponAcceptanceStage builder() {
    return new Builder();
  }

  public interface DispenseUponAcceptanceStage {
    SubstitutionPermittedStage dispenseUponAcceptance(boolean dispenseUponAcceptance);

    Builder from(CancelOrderResponsePrescriptionsItemDispensing other);
  }

  public interface SubstitutionPermittedStage {
    _FinalStage substitutionPermitted(boolean substitutionPermitted);
  }

  public interface _FinalStage {
    CancelOrderResponsePrescriptionsItemDispensing build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage pharmacyNotes(Optional<String> pharmacyNotes);

    _FinalStage pharmacyNotes(String pharmacyNotes);

    _FinalStage pharmacyNotes(Nullable<String> pharmacyNotes);

    _FinalStage requestedFillDate(Optional<String> requestedFillDate);

    _FinalStage requestedFillDate(String requestedFillDate);

    _FinalStage requestedFillDate(Nullable<String> requestedFillDate);

    _FinalStage shippingOptionId(Optional<String> shippingOptionId);

    _FinalStage shippingOptionId(String shippingOptionId);

    _FinalStage shippingOptionId(Nullable<String> shippingOptionId);

    _FinalStage shippingAmountCents(Optional<Integer> shippingAmountCents);

    _FinalStage shippingAmountCents(Integer shippingAmountCents);

    _FinalStage shippingAmountCents(Nullable<Integer> shippingAmountCents);

    _FinalStage shippingDestinationType(
        Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType);

    _FinalStage shippingDestinationType(
        CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType shippingDestinationType);

    _FinalStage shippingDestinationType(
        Nullable<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DispenseUponAcceptanceStage, SubstitutionPermittedStage, _FinalStage {
    private boolean dispenseUponAcceptance;

    private boolean substitutionPermitted;

    private Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType = Optional.empty();

    private Optional<Integer> shippingAmountCents = Optional.empty();

    private Optional<String> shippingOptionId = Optional.empty();

    private Optional<String> requestedFillDate = Optional.empty();

    private Optional<String> pharmacyNotes = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CancelOrderResponsePrescriptionsItemDispensing other) {
      dispenseUponAcceptance(other.getDispenseUponAcceptance());
      substitutionPermitted(other.getSubstitutionPermitted());
      pharmacyNotes(other.getPharmacyNotes());
      requestedFillDate(other.getRequestedFillDate());
      shippingOptionId(other.getShippingOptionId());
      shippingAmountCents(other.getShippingAmountCents());
      shippingDestinationType(other.getShippingDestinationType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("dispenseUponAcceptance")
    public SubstitutionPermittedStage dispenseUponAcceptance(boolean dispenseUponAcceptance) {
      this.dispenseUponAcceptance = dispenseUponAcceptance;
      return this;
    }

    @java.lang.Override
    @JsonSetter("substitutionPermitted")
    public _FinalStage substitutionPermitted(boolean substitutionPermitted) {
      this.substitutionPermitted = substitutionPermitted;
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingDestinationType(
        Nullable<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType) {
      if (shippingDestinationType.isNull()) {
        this.shippingDestinationType = null;
      }
      else if (shippingDestinationType.isEmpty()) {
        this.shippingDestinationType = Optional.empty();
      }
      else {
        this.shippingDestinationType = Optional.of(shippingDestinationType.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingDestinationType(
        CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType shippingDestinationType) {
      this.shippingDestinationType = Optional.ofNullable(shippingDestinationType);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "shippingDestinationType",
        nulls = Nulls.SKIP
    )
    public _FinalStage shippingDestinationType(
        Optional<CancelOrderResponsePrescriptionsItemDispensingShippingDestinationType> shippingDestinationType) {
      this.shippingDestinationType = shippingDestinationType;
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingAmountCents(Nullable<Integer> shippingAmountCents) {
      if (shippingAmountCents.isNull()) {
        this.shippingAmountCents = null;
      }
      else if (shippingAmountCents.isEmpty()) {
        this.shippingAmountCents = Optional.empty();
      }
      else {
        this.shippingAmountCents = Optional.of(shippingAmountCents.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingAmountCents(Integer shippingAmountCents) {
      this.shippingAmountCents = Optional.ofNullable(shippingAmountCents);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "shippingAmountCents",
        nulls = Nulls.SKIP
    )
    public _FinalStage shippingAmountCents(Optional<Integer> shippingAmountCents) {
      this.shippingAmountCents = shippingAmountCents;
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingOptionId(Nullable<String> shippingOptionId) {
      if (shippingOptionId.isNull()) {
        this.shippingOptionId = null;
      }
      else if (shippingOptionId.isEmpty()) {
        this.shippingOptionId = Optional.empty();
      }
      else {
        this.shippingOptionId = Optional.of(shippingOptionId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage shippingOptionId(String shippingOptionId) {
      this.shippingOptionId = Optional.ofNullable(shippingOptionId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "shippingOptionId",
        nulls = Nulls.SKIP
    )
    public _FinalStage shippingOptionId(Optional<String> shippingOptionId) {
      this.shippingOptionId = shippingOptionId;
      return this;
    }

    @java.lang.Override
    public _FinalStage requestedFillDate(Nullable<String> requestedFillDate) {
      if (requestedFillDate.isNull()) {
        this.requestedFillDate = null;
      }
      else if (requestedFillDate.isEmpty()) {
        this.requestedFillDate = Optional.empty();
      }
      else {
        this.requestedFillDate = Optional.of(requestedFillDate.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage requestedFillDate(String requestedFillDate) {
      this.requestedFillDate = Optional.ofNullable(requestedFillDate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "requestedFillDate",
        nulls = Nulls.SKIP
    )
    public _FinalStage requestedFillDate(Optional<String> requestedFillDate) {
      this.requestedFillDate = requestedFillDate;
      return this;
    }

    @java.lang.Override
    public _FinalStage pharmacyNotes(Nullable<String> pharmacyNotes) {
      if (pharmacyNotes.isNull()) {
        this.pharmacyNotes = null;
      }
      else if (pharmacyNotes.isEmpty()) {
        this.pharmacyNotes = Optional.empty();
      }
      else {
        this.pharmacyNotes = Optional.of(pharmacyNotes.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage pharmacyNotes(String pharmacyNotes) {
      this.pharmacyNotes = Optional.ofNullable(pharmacyNotes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "pharmacyNotes",
        nulls = Nulls.SKIP
    )
    public _FinalStage pharmacyNotes(Optional<String> pharmacyNotes) {
      this.pharmacyNotes = pharmacyNotes;
      return this;
    }

    @java.lang.Override
    public CancelOrderResponsePrescriptionsItemDispensing build() {
      return new CancelOrderResponsePrescriptionsItemDispensing(dispenseUponAcceptance, substitutionPermitted, pharmacyNotes, requestedFillDate, shippingOptionId, shippingAmountCents, shippingDestinationType, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public boolean dispenseUponAcceptance() { return getDispenseUponAcceptance(); }

  public boolean substitutionPermitted() { return getSubstitutionPermitted(); }

  public Optional<String> pharmacyNotes() { return getPharmacyNotes(); }

  public Optional<String> requestedFillDate() { return getRequestedFillDate(); }

  public Optional<String> shippingOptionId() { return getShippingOptionId(); }

  public Optional<Integer> shippingAmountCents() { return getShippingAmountCents(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
