/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CancelOrderResponsePrescriptionsItemClinicalMedicationsItem.Builder.class
)
public final class CancelOrderResponsePrescriptionsItemClinicalMedicationsItem {
  private final String display;

  private final Optional<String> ndc;

  private final Optional<String> rxNormCui;

  private final Optional<String> source;

  private final Map<String, Object> additionalProperties;

  private CancelOrderResponsePrescriptionsItemClinicalMedicationsItem(String display,
      Optional<String> ndc, Optional<String> rxNormCui, Optional<String> source,
      Map<String, Object> additionalProperties) {
    this.display = display;
    this.ndc = ndc;
    this.rxNormCui = rxNormCui;
    this.source = source;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("display")
  public String getDisplay() {
    return display;
  }

  @JsonIgnore
  public Optional<String> getNdc() {
    if (ndc == null) {
      return Optional.empty();
    }
    return ndc;
  }

  @JsonIgnore
  public Optional<String> getRxNormCui() {
    if (rxNormCui == null) {
      return Optional.empty();
    }
    return rxNormCui;
  }

  @JsonIgnore
  public Optional<String> getSource() {
    if (source == null) {
      return Optional.empty();
    }
    return source;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("ndc")
  private Optional<String> _getNdc() {
    return ndc;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("rxNormCui")
  private Optional<String> _getRxNormCui() {
    return rxNormCui;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("source")
  private Optional<String> _getSource() {
    return source;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CancelOrderResponsePrescriptionsItemClinicalMedicationsItem && equalTo((CancelOrderResponsePrescriptionsItemClinicalMedicationsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CancelOrderResponsePrescriptionsItemClinicalMedicationsItem other) {
    return display.equals(other.display) && ndc.equals(other.ndc) && rxNormCui.equals(other.rxNormCui) && source.equals(other.source);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.display, this.ndc, this.rxNormCui, this.source);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DisplayStage builder() {
    return new Builder();
  }

  public interface DisplayStage {
    _FinalStage display(@NotNull String display);

    Builder from(CancelOrderResponsePrescriptionsItemClinicalMedicationsItem other);
  }

  public interface _FinalStage {
    CancelOrderResponsePrescriptionsItemClinicalMedicationsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage ndc(Optional<String> ndc);

    _FinalStage ndc(String ndc);

    _FinalStage ndc(Nullable<String> ndc);

    _FinalStage rxNormCui(Optional<String> rxNormCui);

    _FinalStage rxNormCui(String rxNormCui);

    _FinalStage rxNormCui(Nullable<String> rxNormCui);

    _FinalStage source(Optional<String> source);

    _FinalStage source(String source);

    _FinalStage source(Nullable<String> source);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DisplayStage, _FinalStage {
    private String display;

    private Optional<String> source = Optional.empty();

    private Optional<String> rxNormCui = Optional.empty();

    private Optional<String> ndc = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CancelOrderResponsePrescriptionsItemClinicalMedicationsItem other) {
      display(other.getDisplay());
      ndc(other.getNdc());
      rxNormCui(other.getRxNormCui());
      source(other.getSource());
      return this;
    }

    @java.lang.Override
    @JsonSetter("display")
    public _FinalStage display(@NotNull String display) {
      this.display = Objects.requireNonNull(display, "display must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage source(Nullable<String> source) {
      if (source.isNull()) {
        this.source = null;
      }
      else if (source.isEmpty()) {
        this.source = Optional.empty();
      }
      else {
        this.source = Optional.of(source.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage source(String source) {
      this.source = Optional.ofNullable(source);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "source",
        nulls = Nulls.SKIP
    )
    public _FinalStage source(Optional<String> source) {
      this.source = source;
      return this;
    }

    @java.lang.Override
    public _FinalStage rxNormCui(Nullable<String> rxNormCui) {
      if (rxNormCui.isNull()) {
        this.rxNormCui = null;
      }
      else if (rxNormCui.isEmpty()) {
        this.rxNormCui = Optional.empty();
      }
      else {
        this.rxNormCui = Optional.of(rxNormCui.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage rxNormCui(String rxNormCui) {
      this.rxNormCui = Optional.ofNullable(rxNormCui);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "rxNormCui",
        nulls = Nulls.SKIP
    )
    public _FinalStage rxNormCui(Optional<String> rxNormCui) {
      this.rxNormCui = rxNormCui;
      return this;
    }

    @java.lang.Override
    public _FinalStage ndc(Nullable<String> ndc) {
      if (ndc.isNull()) {
        this.ndc = null;
      }
      else if (ndc.isEmpty()) {
        this.ndc = Optional.empty();
      }
      else {
        this.ndc = Optional.of(ndc.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage ndc(String ndc) {
      this.ndc = Optional.ofNullable(ndc);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "ndc",
        nulls = Nulls.SKIP
    )
    public _FinalStage ndc(Optional<String> ndc) {
      this.ndc = ndc;
      return this;
    }

    @java.lang.Override
    public CancelOrderResponsePrescriptionsItemClinicalMedicationsItem build() {
      return new CancelOrderResponsePrescriptionsItemClinicalMedicationsItem(display, ndc, rxNormCui, source, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
