/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CancelOrderResponseFulfillmentsItemShippingDestinationType {
  public static final CancelOrderResponseFulfillmentsItemShippingDestinationType PRACTICE = new CancelOrderResponseFulfillmentsItemShippingDestinationType(Value.PRACTICE, "practice");

  public static final CancelOrderResponseFulfillmentsItemShippingDestinationType PATIENT = new CancelOrderResponseFulfillmentsItemShippingDestinationType(Value.PATIENT, "patient");

  private final Value value;

  private final String string;

  CancelOrderResponseFulfillmentsItemShippingDestinationType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CancelOrderResponseFulfillmentsItemShippingDestinationType && this.string.equals(((CancelOrderResponseFulfillmentsItemShippingDestinationType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PRACTICE:
        return visitor.visitPractice();
      case PATIENT:
        return visitor.visitPatient();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CancelOrderResponseFulfillmentsItemShippingDestinationType valueOf(String value) {
    switch (value) {
      case "practice":
        return PRACTICE;
      case "patient":
        return PATIENT;
      default:
        return new CancelOrderResponseFulfillmentsItemShippingDestinationType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PATIENT,

    PRACTICE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPatient();

    T visitPractice();

    T visitUnknown(String unknownType);
  }
}
