/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CancelOrderResponseLifecycleEventsItemSource {
  public static final CancelOrderResponseLifecycleEventsItemSource SHIPMENT = new CancelOrderResponseLifecycleEventsItemSource(Value.SHIPMENT, "shipment");

  public static final CancelOrderResponseLifecycleEventsItemSource EXCEPTION = new CancelOrderResponseLifecycleEventsItemSource(Value.EXCEPTION, "exception");

  public static final CancelOrderResponseLifecycleEventsItemSource WEBHOOK = new CancelOrderResponseLifecycleEventsItemSource(Value.WEBHOOK, "webhook");

  public static final CancelOrderResponseLifecycleEventsItemSource FULFILLMENT = new CancelOrderResponseLifecycleEventsItemSource(Value.FULFILLMENT, "fulfillment");

  public static final CancelOrderResponseLifecycleEventsItemSource CANCELLATION = new CancelOrderResponseLifecycleEventsItemSource(Value.CANCELLATION, "cancellation");

  public static final CancelOrderResponseLifecycleEventsItemSource INTEGRATION = new CancelOrderResponseLifecycleEventsItemSource(Value.INTEGRATION, "integration");

  private final Value value;

  private final String string;

  CancelOrderResponseLifecycleEventsItemSource(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CancelOrderResponseLifecycleEventsItemSource && this.string.equals(((CancelOrderResponseLifecycleEventsItemSource) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SHIPMENT:
        return visitor.visitShipment();
      case EXCEPTION:
        return visitor.visitException();
      case WEBHOOK:
        return visitor.visitWebhook();
      case FULFILLMENT:
        return visitor.visitFulfillment();
      case CANCELLATION:
        return visitor.visitCancellation();
      case INTEGRATION:
        return visitor.visitIntegration();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CancelOrderResponseLifecycleEventsItemSource valueOf(String value) {
    switch (value) {
      case "shipment":
        return SHIPMENT;
      case "exception":
        return EXCEPTION;
      case "webhook":
        return WEBHOOK;
      case "fulfillment":
        return FULFILLMENT;
      case "cancellation":
        return CANCELLATION;
      case "integration":
        return INTEGRATION;
      default:
        return new CancelOrderResponseLifecycleEventsItemSource(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CANCELLATION,

    EXCEPTION,

    FULFILLMENT,

    INTEGRATION,

    SHIPMENT,

    WEBHOOK,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCancellation();

    T visitException();

    T visitFulfillment();

    T visitIntegration();

    T visitShipment();

    T visitWebhook();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
