/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CancelOrderResponseFulfillmentsItemShipping.Builder.class
)
public final class CancelOrderResponseFulfillmentsItemShipping {
  private final CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType;

  private final CancelOrderResponseFulfillmentsItemShippingMethod method;

  private final Optional<CancelOrderResponseFulfillmentsItemShippingOption> option;

  private final Map<String, Object> additionalProperties;

  private CancelOrderResponseFulfillmentsItemShipping(
      CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType,
      CancelOrderResponseFulfillmentsItemShippingMethod method,
      Optional<CancelOrderResponseFulfillmentsItemShippingOption> option,
      Map<String, Object> additionalProperties) {
    this.destinationType = destinationType;
    this.method = method;
    this.option = option;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("destinationType")
  public CancelOrderResponseFulfillmentsItemShippingDestinationType getDestinationType() {
    return destinationType;
  }

  @JsonProperty("method")
  public CancelOrderResponseFulfillmentsItemShippingMethod getMethod() {
    return method;
  }

  @JsonIgnore
  public Optional<CancelOrderResponseFulfillmentsItemShippingOption> getOption() {
    if (option == null) {
      return Optional.empty();
    }
    return option;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("option")
  private Optional<CancelOrderResponseFulfillmentsItemShippingOption> _getOption() {
    return option;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CancelOrderResponseFulfillmentsItemShipping && equalTo((CancelOrderResponseFulfillmentsItemShipping) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CancelOrderResponseFulfillmentsItemShipping other) {
    return destinationType.equals(other.destinationType) && method.equals(other.method) && option.equals(other.option);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.destinationType, this.method, this.option);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DestinationTypeStage builder() {
    return new Builder();
  }

  public interface DestinationTypeStage {
    MethodStage destinationType(
        @NotNull CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType);

    Builder from(CancelOrderResponseFulfillmentsItemShipping other);
  }

  public interface MethodStage {
    _FinalStage method(@NotNull CancelOrderResponseFulfillmentsItemShippingMethod method);
  }

  public interface _FinalStage {
    CancelOrderResponseFulfillmentsItemShipping build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage option(Optional<CancelOrderResponseFulfillmentsItemShippingOption> option);

    _FinalStage option(CancelOrderResponseFulfillmentsItemShippingOption option);

    _FinalStage option(Nullable<CancelOrderResponseFulfillmentsItemShippingOption> option);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DestinationTypeStage, MethodStage, _FinalStage {
    private CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType;

    private CancelOrderResponseFulfillmentsItemShippingMethod method;

    private Optional<CancelOrderResponseFulfillmentsItemShippingOption> option = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CancelOrderResponseFulfillmentsItemShipping other) {
      destinationType(other.getDestinationType());
      method(other.getMethod());
      option(other.getOption());
      return this;
    }

    @java.lang.Override
    @JsonSetter("destinationType")
    public MethodStage destinationType(
        @NotNull CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType) {
      this.destinationType = Objects.requireNonNull(destinationType, "destinationType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("method")
    public _FinalStage method(@NotNull CancelOrderResponseFulfillmentsItemShippingMethod method) {
      this.method = Objects.requireNonNull(method, "method must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage option(Nullable<CancelOrderResponseFulfillmentsItemShippingOption> option) {
      if (option.isNull()) {
        this.option = null;
      }
      else if (option.isEmpty()) {
        this.option = Optional.empty();
      }
      else {
        this.option = Optional.of(option.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage option(CancelOrderResponseFulfillmentsItemShippingOption option) {
      this.option = Optional.ofNullable(option);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "option",
        nulls = Nulls.SKIP
    )
    public _FinalStage option(Optional<CancelOrderResponseFulfillmentsItemShippingOption> option) {
      this.option = option;
      return this;
    }

    @java.lang.Override
    public CancelOrderResponseFulfillmentsItemShipping build() {
      return new CancelOrderResponseFulfillmentsItemShipping(destinationType, method, option, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public CancelOrderResponseFulfillmentsItemShippingDestinationType destinationType() { return getDestinationType(); }

  public CancelOrderResponseFulfillmentsItemShippingMethod method() { return getMethod(); }

  public Optional<CancelOrderResponseFulfillmentsItemShippingOption> option() { return getOption(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
