/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreatePlatformPracticeApiKeyResponseServiceAccount.Builder.class
)
public final class CreatePlatformPracticeApiKeyResponseServiceAccount {
  private final CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion;

  private final String displayName;

  private final String id;

  private final List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes;

  private final String organizationId;

  private final CreatePlatformPracticeApiKeyResponseServiceAccountStatus status;

  private final String subjectId;

  private final CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType;

  private final Map<String, Object> additionalProperties;

  private CreatePlatformPracticeApiKeyResponseServiceAccount(
      CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion, String displayName,
      String id, List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes,
      String organizationId, CreatePlatformPracticeApiKeyResponseServiceAccountStatus status,
      String subjectId, CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType,
      Map<String, Object> additionalProperties) {
    this.apiVersion = apiVersion;
    this.displayName = displayName;
    this.id = id;
    this.maxScopes = maxScopes;
    this.organizationId = organizationId;
    this.status = status;
    this.subjectId = subjectId;
    this.subjectType = subjectType;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("apiVersion")
  public CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion getApiVersion() {
    return apiVersion;
  }

  @JsonProperty("displayName")
  public String getDisplayName() {
    return displayName;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("maxScopes")
  public List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> getMaxScopes() {
    return maxScopes;
  }

  @JsonProperty("organizationId")
  public String getOrganizationId() {
    return organizationId;
  }

  @JsonProperty("status")
  public CreatePlatformPracticeApiKeyResponseServiceAccountStatus getStatus() {
    return status;
  }

  @JsonProperty("subjectId")
  public String getSubjectId() {
    return subjectId;
  }

  @JsonProperty("subjectType")
  public CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType getSubjectType() {
    return subjectType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreatePlatformPracticeApiKeyResponseServiceAccount && equalTo((CreatePlatformPracticeApiKeyResponseServiceAccount) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreatePlatformPracticeApiKeyResponseServiceAccount other) {
    return apiVersion.equals(other.apiVersion) && displayName.equals(other.displayName) && id.equals(other.id) && maxScopes.equals(other.maxScopes) && organizationId.equals(other.organizationId) && status.equals(other.status) && subjectId.equals(other.subjectId) && subjectType.equals(other.subjectType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiVersion, this.displayName, this.id, this.maxScopes, this.organizationId, this.status, this.subjectId, this.subjectType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiVersionStage builder() {
    return new Builder();
  }

  public interface ApiVersionStage {
    DisplayNameStage apiVersion(
        @NotNull CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion);

    Builder from(CreatePlatformPracticeApiKeyResponseServiceAccount other);
  }

  public interface DisplayNameStage {
    IdStage displayName(@NotNull String displayName);
  }

  public interface IdStage {
    OrganizationIdStage id(@NotNull String id);
  }

  public interface OrganizationIdStage {
    StatusStage organizationId(@NotNull String organizationId);
  }

  public interface StatusStage {
    SubjectIdStage status(@NotNull CreatePlatformPracticeApiKeyResponseServiceAccountStatus status);
  }

  public interface SubjectIdStage {
    SubjectTypeStage subjectId(@NotNull String subjectId);
  }

  public interface SubjectTypeStage {
    _FinalStage subjectType(
        @NotNull CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType);
  }

  public interface _FinalStage {
    CreatePlatformPracticeApiKeyResponseServiceAccount build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage maxScopes(
        List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes);

    _FinalStage addMaxScopes(
        CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem maxScopes);

    _FinalStage addAllMaxScopes(
        List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiVersionStage, DisplayNameStage, IdStage, OrganizationIdStage, StatusStage, SubjectIdStage, SubjectTypeStage, _FinalStage {
    private CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion;

    private String displayName;

    private String id;

    private String organizationId;

    private CreatePlatformPracticeApiKeyResponseServiceAccountStatus status;

    private String subjectId;

    private CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType;

    private List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreatePlatformPracticeApiKeyResponseServiceAccount other) {
      apiVersion(other.getApiVersion());
      displayName(other.getDisplayName());
      id(other.getId());
      maxScopes(other.getMaxScopes());
      organizationId(other.getOrganizationId());
      status(other.getStatus());
      subjectId(other.getSubjectId());
      subjectType(other.getSubjectType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("apiVersion")
    public DisplayNameStage apiVersion(
        @NotNull CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion) {
      this.apiVersion = Objects.requireNonNull(apiVersion, "apiVersion must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("displayName")
    public IdStage displayName(@NotNull String displayName) {
      this.displayName = Objects.requireNonNull(displayName, "displayName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public OrganizationIdStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("organizationId")
    public StatusStage organizationId(@NotNull String organizationId) {
      this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public SubjectIdStage status(
        @NotNull CreatePlatformPracticeApiKeyResponseServiceAccountStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("subjectId")
    public SubjectTypeStage subjectId(@NotNull String subjectId) {
      this.subjectId = Objects.requireNonNull(subjectId, "subjectId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("subjectType")
    public _FinalStage subjectType(
        @NotNull CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType) {
      this.subjectType = Objects.requireNonNull(subjectType, "subjectType must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllMaxScopes(
        List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes) {
      if (maxScopes != null) {
        this.maxScopes.addAll(maxScopes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addMaxScopes(
        CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem maxScopes) {
      this.maxScopes.add(maxScopes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "maxScopes",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxScopes(
        List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes) {
      this.maxScopes.clear();
      if (maxScopes != null) {
        this.maxScopes.addAll(maxScopes);
      }
      return this;
    }

    @java.lang.Override
    public CreatePlatformPracticeApiKeyResponseServiceAccount build() {
      return new CreatePlatformPracticeApiKeyResponseServiceAccount(apiVersion, displayName, id, maxScopes, organizationId, status, subjectId, subjectType, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public CreatePlatformPracticeApiKeyResponseServiceAccountApiVersion apiVersion() { return getApiVersion(); }

  public String displayName() { return getDisplayName(); }

  public String id() { return getId(); }

  public List<CreatePlatformPracticeApiKeyResponseServiceAccountMaxScopesItem> maxScopes() { return getMaxScopes(); }

  public String organizationId() { return getOrganizationId(); }

  public CreatePlatformPracticeApiKeyResponseServiceAccountStatus status() { return getStatus(); }

  public String subjectId() { return getSubjectId(); }

  public CreatePlatformPracticeApiKeyResponseServiceAccountSubjectType subjectType() { return getSubjectType(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
