/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetAccountResponse.Builder.class
)
public final class GetAccountResponse {
  private final GetAccountResponseAccount account;

  private final boolean livemode;

  private final Optional<List<String>> scopes;

  private final GetAccountResponseMembership membership;

  private final GetAccountResponseOperatingMode operatingMode;

  private final GetAccountResponseUser user;

  private final Map<String, Object> additionalProperties;

  private GetAccountResponse(GetAccountResponseAccount account, boolean livemode,
      Optional<List<String>> scopes, GetAccountResponseMembership membership,
      GetAccountResponseOperatingMode operatingMode, GetAccountResponseUser user,
      Map<String, Object> additionalProperties) {
    this.account = account;
    this.livemode = livemode;
    this.scopes = scopes;
    this.membership = membership;
    this.operatingMode = operatingMode;
    this.user = user;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("account")
  public GetAccountResponseAccount getAccount() {
    return account;
  }

  /**
   * @return True for a Live request; false for a Test request.
   */
  @JsonProperty("livemode")
  public boolean getLivemode() {
    return livemode;
  }

  /**
   * @return Effective scopes of the authenticated API key. Null for a dashboard session; use membership.permissions for that session.
   */
  @JsonIgnore
  public Optional<List<String>> getScopes() {
    if (scopes == null) {
      return Optional.empty();
    }
    return scopes;
  }

  @JsonProperty("membership")
  public GetAccountResponseMembership getMembership() {
    return membership;
  }

  /**
   * @return The organization's Live-access status, independent of this request's livemode.
   */
  @JsonProperty("operatingMode")
  public GetAccountResponseOperatingMode getOperatingMode() {
    return operatingMode;
  }

  @JsonProperty("user")
  public GetAccountResponseUser getUser() {
    return user;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("scopes")
  private Optional<List<String>> _getScopes() {
    return scopes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetAccountResponse && equalTo((GetAccountResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetAccountResponse other) {
    return account.equals(other.account) && livemode == other.livemode && scopes.equals(other.scopes) && membership.equals(other.membership) && operatingMode.equals(other.operatingMode) && user.equals(other.user);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.account, this.livemode, this.scopes, this.membership, this.operatingMode, this.user);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AccountStage builder() {
    return new Builder();
  }

  public interface AccountStage {
    LivemodeStage account(@NotNull GetAccountResponseAccount account);

    Builder from(GetAccountResponse other);
  }

  public interface LivemodeStage {
    /**
     * <p>True for a Live request; false for a Test request.</p>
     */
    MembershipStage livemode(boolean livemode);
  }

  public interface MembershipStage {
    OperatingModeStage membership(@NotNull GetAccountResponseMembership membership);
  }

  public interface OperatingModeStage {
    /**
     * <p>The organization's Live-access status, independent of this request's livemode.</p>
     */
    UserStage operatingMode(@NotNull GetAccountResponseOperatingMode operatingMode);
  }

  public interface UserStage {
    _FinalStage user(@NotNull GetAccountResponseUser user);
  }

  public interface _FinalStage {
    GetAccountResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Effective scopes of the authenticated API key. Null for a dashboard session; use membership.permissions for that session.</p>
     */
    _FinalStage scopes(Optional<List<String>> scopes);

    _FinalStage scopes(List<String> scopes);

    _FinalStage scopes(Nullable<List<String>> scopes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AccountStage, LivemodeStage, MembershipStage, OperatingModeStage, UserStage, _FinalStage {
    private GetAccountResponseAccount account;

    private boolean livemode;

    private GetAccountResponseMembership membership;

    private GetAccountResponseOperatingMode operatingMode;

    private GetAccountResponseUser user;

    private Optional<List<String>> scopes = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetAccountResponse other) {
      account(other.getAccount());
      livemode(other.getLivemode());
      scopes(other.getScopes());
      membership(other.getMembership());
      operatingMode(other.getOperatingMode());
      user(other.getUser());
      return this;
    }

    @java.lang.Override
    @JsonSetter("account")
    public LivemodeStage account(@NotNull GetAccountResponseAccount account) {
      this.account = Objects.requireNonNull(account, "account must not be null");
      return this;
    }

    /**
     * <p>True for a Live request; false for a Test request.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("livemode")
    public MembershipStage livemode(boolean livemode) {
      this.livemode = livemode;
      return this;
    }

    @java.lang.Override
    @JsonSetter("membership")
    public OperatingModeStage membership(@NotNull GetAccountResponseMembership membership) {
      this.membership = Objects.requireNonNull(membership, "membership must not be null");
      return this;
    }

    /**
     * <p>The organization's Live-access status, independent of this request's livemode.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("operatingMode")
    public UserStage operatingMode(@NotNull GetAccountResponseOperatingMode operatingMode) {
      this.operatingMode = Objects.requireNonNull(operatingMode, "operatingMode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("user")
    public _FinalStage user(@NotNull GetAccountResponseUser user) {
      this.user = Objects.requireNonNull(user, "user must not be null");
      return this;
    }

    /**
     * <p>Effective scopes of the authenticated API key. Null for a dashboard session; use membership.permissions for that session.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scopes(Nullable<List<String>> scopes) {
      if (scopes.isNull()) {
        this.scopes = null;
      }
      else if (scopes.isEmpty()) {
        this.scopes = Optional.empty();
      }
      else {
        this.scopes = Optional.of(scopes.get());
      }
      return this;
    }

    /**
     * <p>Effective scopes of the authenticated API key. Null for a dashboard session; use membership.permissions for that session.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scopes(List<String> scopes) {
      this.scopes = Optional.ofNullable(scopes);
      return this;
    }

    /**
     * <p>Effective scopes of the authenticated API key. Null for a dashboard session; use membership.permissions for that session.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scopes",
        nulls = Nulls.SKIP
    )
    public _FinalStage scopes(Optional<List<String>> scopes) {
      this.scopes = scopes;
      return this;
    }

    @java.lang.Override
    public GetAccountResponse build() {
      return new GetAccountResponse(account, livemode, scopes, membership, operatingMode, user, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public GetAccountResponseAccount account() { return getAccount(); }

  public boolean livemode() { return getLivemode(); }

  public Optional<List<String>> scopes() { return getScopes(); }

  public GetAccountResponseMembership membership() { return getMembership(); }

  public GetAccountResponseOperatingMode operatingMode() { return getOperatingMode(); }

  public GetAccountResponseUser user() { return getUser(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
