/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetOrderResponseReviewStatus {
  public static final GetOrderResponseReviewStatus COMPLETED = new GetOrderResponseReviewStatus(Value.COMPLETED, "completed");

  public static final GetOrderResponseReviewStatus REJECTED = new GetOrderResponseReviewStatus(Value.REJECTED, "rejected");

  private final Value value;

  private final String string;

  GetOrderResponseReviewStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetOrderResponseReviewStatus && this.string.equals(((GetOrderResponseReviewStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case COMPLETED:
        return visitor.visitCompleted();
      case REJECTED:
        return visitor.visitRejected();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetOrderResponseReviewStatus valueOf(String value) {
    switch (value) {
      case "completed":
        return COMPLETED;
      case "rejected":
        return REJECTED;
      default:
        return new GetOrderResponseReviewStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    COMPLETED,

    REJECTED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCompleted();

    T visitRejected();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
