/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetOrderResponseObject {
  public static final GetOrderResponseObject ORDER = new GetOrderResponseObject(Value.ORDER, "order");

  private final Value value;

  private final String string;

  GetOrderResponseObject(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetOrderResponseObject && this.string.equals(((GetOrderResponseObject) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ORDER:
        return visitor.visitOrder();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetOrderResponseObject valueOf(String value) {
    switch (value) {
      case "order":
        return ORDER;
      default:
        return new GetOrderResponseObject(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ORDER,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitOrder();

    T visitUnknown(String unknownType);
  }
}
