/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetOrderResponseFulfillmentsItemExceptionsItemStatus {
  public static final GetOrderResponseFulfillmentsItemExceptionsItemStatus ACKNOWLEDGED = new GetOrderResponseFulfillmentsItemExceptionsItemStatus(Value.ACKNOWLEDGED, "acknowledged");

  public static final GetOrderResponseFulfillmentsItemExceptionsItemStatus OPEN = new GetOrderResponseFulfillmentsItemExceptionsItemStatus(Value.OPEN, "open");

  public static final GetOrderResponseFulfillmentsItemExceptionsItemStatus RESOLVED = new GetOrderResponseFulfillmentsItemExceptionsItemStatus(Value.RESOLVED, "resolved");

  private final Value value;

  private final String string;

  GetOrderResponseFulfillmentsItemExceptionsItemStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetOrderResponseFulfillmentsItemExceptionsItemStatus && this.string.equals(((GetOrderResponseFulfillmentsItemExceptionsItemStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case ACKNOWLEDGED:
        return visitor.visitAcknowledged();
      case OPEN:
        return visitor.visitOpen();
      case RESOLVED:
        return visitor.visitResolved();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetOrderResponseFulfillmentsItemExceptionsItemStatus valueOf(String value) {
    switch (value) {
      case "acknowledged":
        return ACKNOWLEDGED;
      case "open":
        return OPEN;
      case "resolved":
        return RESOLVED;
      default:
        return new GetOrderResponseFulfillmentsItemExceptionsItemStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    OPEN,

    ACKNOWLEDGED,

    RESOLVED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitOpen();

    T visitAcknowledged();

    T visitResolved();

    T visitUnknown(String unknownType);
  }
}
