/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetOrderResponse.Builder.class
)
public final class GetOrderResponse {
  private final String revision;

  private final List<GetOrderResponseOtcItemsItem> otcItems;

  private final Optional<Integer> practiceMedicationTotalCents;

  private final Optional<String> externalOrderId;

  private final GetOrderResponseMetadata metadata;

  private final String createdAt;

  private final List<GetOrderResponseFulfillmentsItem> fulfillments;

  private final String id;

  private final List<GetOrderResponseLifecycleEventsItem> lifecycleEvents;

  private final boolean livemode;

  private final GetOrderResponseObject object;

  private final Optional<String> patientExternalId;

  private final String patientId;

  private final String patientName;

  private final String patientState;

  private final String practiceId;

  private final Optional<String> prescriberName;

  private final Optional<String> prescriberNpi;

  private final Optional<GetOrderResponseReview> review;

  private final List<GetOrderResponsePrescriptionsItem> prescriptions;

  private final GetOrderResponseStatus status;

  private final String updatedAt;

  private final Map<String, Object> additionalProperties;

  private GetOrderResponse(String revision, List<GetOrderResponseOtcItemsItem> otcItems,
      Optional<Integer> practiceMedicationTotalCents, Optional<String> externalOrderId,
      GetOrderResponseMetadata metadata, String createdAt,
      List<GetOrderResponseFulfillmentsItem> fulfillments, String id,
      List<GetOrderResponseLifecycleEventsItem> lifecycleEvents, boolean livemode,
      GetOrderResponseObject object, Optional<String> patientExternalId, String patientId,
      String patientName, String patientState, String practiceId, Optional<String> prescriberName,
      Optional<String> prescriberNpi, Optional<GetOrderResponseReview> review,
      List<GetOrderResponsePrescriptionsItem> prescriptions, GetOrderResponseStatus status,
      String updatedAt, Map<String, Object> additionalProperties) {
    this.revision = revision;
    this.otcItems = otcItems;
    this.practiceMedicationTotalCents = practiceMedicationTotalCents;
    this.externalOrderId = externalOrderId;
    this.metadata = metadata;
    this.createdAt = createdAt;
    this.fulfillments = fulfillments;
    this.id = id;
    this.lifecycleEvents = lifecycleEvents;
    this.livemode = livemode;
    this.object = object;
    this.patientExternalId = patientExternalId;
    this.patientId = patientId;
    this.patientName = patientName;
    this.patientState = patientState;
    this.practiceId = practiceId;
    this.prescriberName = prescriberName;
    this.prescriberNpi = prescriberNpi;
    this.review = review;
    this.prescriptions = prescriptions;
    this.status = status;
    this.updatedAt = updatedAt;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Opaque revision of the complete order prescription set. Send the revision you reviewed as expectedRevision; never replace it automatically after a conflict.
   */
  @JsonProperty("revision")
  public String getRevision() {
    return revision;
  }

  @JsonProperty("otcItems")
  public List<GetOrderResponseOtcItemsItem> getOtcItems() {
    return otcItems;
  }

  /**
   * @return Snapshot of the practice-facing medication total. Null until every prescription has recorded submission pricing. Excludes shipping and supplies.
   */
  @JsonIgnore
  public Optional<Integer> getPracticeMedicationTotalCents() {
    if (practiceMedicationTotalCents == null) {
      return Optional.empty();
    }
    return practiceMedicationTotalCents;
  }

  @JsonIgnore
  public Optional<String> getExternalOrderId() {
    if (externalOrderId == null) {
      return Optional.empty();
    }
    return externalOrderId;
  }

  @JsonProperty("metadata")
  public GetOrderResponseMetadata getMetadata() {
    return metadata;
  }

  @JsonProperty("createdAt")
  public String getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("fulfillments")
  public List<GetOrderResponseFulfillmentsItem> getFulfillments() {
    return fulfillments;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("lifecycleEvents")
  public List<GetOrderResponseLifecycleEventsItem> getLifecycleEvents() {
    return lifecycleEvents;
  }

  @JsonProperty("livemode")
  public boolean getLivemode() {
    return livemode;
  }

  @JsonProperty("object")
  public GetOrderResponseObject getObject() {
    return object;
  }

  @JsonIgnore
  public Optional<String> getPatientExternalId() {
    if (patientExternalId == null) {
      return Optional.empty();
    }
    return patientExternalId;
  }

  @JsonProperty("patientId")
  public String getPatientId() {
    return patientId;
  }

  @JsonProperty("patientName")
  public String getPatientName() {
    return patientName;
  }

  /**
   * @return The patient's current clinical state. This is not the saved delivery state; use each prescription's deliveryAddress for shipping.
   */
  @JsonProperty("patientState")
  public String getPatientState() {
    return patientState;
  }

  @JsonProperty("practiceId")
  public String getPracticeId() {
    return practiceId;
  }

  @JsonIgnore
  public Optional<String> getPrescriberName() {
    if (prescriberName == null) {
      return Optional.empty();
    }
    return prescriberName;
  }

  @JsonIgnore
  public Optional<String> getPrescriberNpi() {
    if (prescriberNpi == null) {
      return Optional.empty();
    }
    return prescriberNpi;
  }

  @JsonIgnore
  public Optional<GetOrderResponseReview> getReview() {
    if (review == null) {
      return Optional.empty();
    }
    return review;
  }

  @JsonProperty("prescriptions")
  public List<GetOrderResponsePrescriptionsItem> getPrescriptions() {
    return prescriptions;
  }

  @JsonProperty("status")
  public GetOrderResponseStatus getStatus() {
    return status;
  }

  @JsonProperty("updatedAt")
  public String getUpdatedAt() {
    return updatedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("practiceMedicationTotalCents")
  private Optional<Integer> _getPracticeMedicationTotalCents() {
    return practiceMedicationTotalCents;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("externalOrderId")
  private Optional<String> _getExternalOrderId() {
    return externalOrderId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("patientExternalId")
  private Optional<String> _getPatientExternalId() {
    return patientExternalId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("prescriberName")
  private Optional<String> _getPrescriberName() {
    return prescriberName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("prescriberNpi")
  private Optional<String> _getPrescriberNpi() {
    return prescriberNpi;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("review")
  private Optional<GetOrderResponseReview> _getReview() {
    return review;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetOrderResponse && equalTo((GetOrderResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetOrderResponse other) {
    return revision.equals(other.revision) && otcItems.equals(other.otcItems) && practiceMedicationTotalCents.equals(other.practiceMedicationTotalCents) && externalOrderId.equals(other.externalOrderId) && metadata.equals(other.metadata) && createdAt.equals(other.createdAt) && fulfillments.equals(other.fulfillments) && id.equals(other.id) && lifecycleEvents.equals(other.lifecycleEvents) && livemode == other.livemode && object.equals(other.object) && patientExternalId.equals(other.patientExternalId) && patientId.equals(other.patientId) && patientName.equals(other.patientName) && patientState.equals(other.patientState) && practiceId.equals(other.practiceId) && prescriberName.equals(other.prescriberName) && prescriberNpi.equals(other.prescriberNpi) && review.equals(other.review) && prescriptions.equals(other.prescriptions) && status.equals(other.status) && updatedAt.equals(other.updatedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.revision, this.otcItems, this.practiceMedicationTotalCents, this.externalOrderId, this.metadata, this.createdAt, this.fulfillments, this.id, this.lifecycleEvents, this.livemode, this.object, this.patientExternalId, this.patientId, this.patientName, this.patientState, this.practiceId, this.prescriberName, this.prescriberNpi, this.review, this.prescriptions, this.status, this.updatedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RevisionStage builder() {
    return new Builder();
  }

  public interface RevisionStage {
    /**
     * <p>Opaque revision of the complete order prescription set. Send the revision you reviewed as expectedRevision; never replace it automatically after a conflict.</p>
     */
    MetadataStage revision(@NotNull String revision);

    Builder from(GetOrderResponse other);
  }

  public interface MetadataStage {
    CreatedAtStage metadata(@NotNull GetOrderResponseMetadata metadata);
  }

  public interface CreatedAtStage {
    IdStage createdAt(@NotNull String createdAt);
  }

  public interface IdStage {
    LivemodeStage id(@NotNull String id);
  }

  public interface LivemodeStage {
    ObjectStage livemode(boolean livemode);
  }

  public interface ObjectStage {
    PatientIdStage object(@NotNull GetOrderResponseObject object);
  }

  public interface PatientIdStage {
    PatientNameStage patientId(@NotNull String patientId);
  }

  public interface PatientNameStage {
    PatientStateStage patientName(@NotNull String patientName);
  }

  public interface PatientStateStage {
    /**
     * <p>The patient's current clinical state. This is not the saved delivery state; use each prescription's deliveryAddress for shipping.</p>
     */
    PracticeIdStage patientState(@NotNull String patientState);
  }

  public interface PracticeIdStage {
    StatusStage practiceId(@NotNull String practiceId);
  }

  public interface StatusStage {
    UpdatedAtStage status(@NotNull GetOrderResponseStatus status);
  }

  public interface UpdatedAtStage {
    _FinalStage updatedAt(@NotNull String updatedAt);
  }

  public interface _FinalStage {
    GetOrderResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage otcItems(List<GetOrderResponseOtcItemsItem> otcItems);

    _FinalStage addOtcItems(GetOrderResponseOtcItemsItem otcItems);

    _FinalStage addAllOtcItems(List<GetOrderResponseOtcItemsItem> otcItems);

    /**
     * <p>Snapshot of the practice-facing medication total. Null until every prescription has recorded submission pricing. Excludes shipping and supplies.</p>
     */
    _FinalStage practiceMedicationTotalCents(Optional<Integer> practiceMedicationTotalCents);

    _FinalStage practiceMedicationTotalCents(Integer practiceMedicationTotalCents);

    _FinalStage practiceMedicationTotalCents(Nullable<Integer> practiceMedicationTotalCents);

    _FinalStage externalOrderId(Optional<String> externalOrderId);

    _FinalStage externalOrderId(String externalOrderId);

    _FinalStage externalOrderId(Nullable<String> externalOrderId);

    _FinalStage fulfillments(List<GetOrderResponseFulfillmentsItem> fulfillments);

    _FinalStage addFulfillments(GetOrderResponseFulfillmentsItem fulfillments);

    _FinalStage addAllFulfillments(List<GetOrderResponseFulfillmentsItem> fulfillments);

    _FinalStage lifecycleEvents(List<GetOrderResponseLifecycleEventsItem> lifecycleEvents);

    _FinalStage addLifecycleEvents(GetOrderResponseLifecycleEventsItem lifecycleEvents);

    _FinalStage addAllLifecycleEvents(List<GetOrderResponseLifecycleEventsItem> lifecycleEvents);

    _FinalStage patientExternalId(Optional<String> patientExternalId);

    _FinalStage patientExternalId(String patientExternalId);

    _FinalStage patientExternalId(Nullable<String> patientExternalId);

    _FinalStage prescriberName(Optional<String> prescriberName);

    _FinalStage prescriberName(String prescriberName);

    _FinalStage prescriberName(Nullable<String> prescriberName);

    _FinalStage prescriberNpi(Optional<String> prescriberNpi);

    _FinalStage prescriberNpi(String prescriberNpi);

    _FinalStage prescriberNpi(Nullable<String> prescriberNpi);

    _FinalStage review(Optional<GetOrderResponseReview> review);

    _FinalStage review(GetOrderResponseReview review);

    _FinalStage review(Nullable<GetOrderResponseReview> review);

    _FinalStage prescriptions(List<GetOrderResponsePrescriptionsItem> prescriptions);

    _FinalStage addPrescriptions(GetOrderResponsePrescriptionsItem prescriptions);

    _FinalStage addAllPrescriptions(List<GetOrderResponsePrescriptionsItem> prescriptions);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RevisionStage, MetadataStage, CreatedAtStage, IdStage, LivemodeStage, ObjectStage, PatientIdStage, PatientNameStage, PatientStateStage, PracticeIdStage, StatusStage, UpdatedAtStage, _FinalStage {
    private String revision;

    private GetOrderResponseMetadata metadata;

    private String createdAt;

    private String id;

    private boolean livemode;

    private GetOrderResponseObject object;

    private String patientId;

    private String patientName;

    private String patientState;

    private String practiceId;

    private GetOrderResponseStatus status;

    private String updatedAt;

    private List<GetOrderResponsePrescriptionsItem> prescriptions = new ArrayList<>();

    private Optional<GetOrderResponseReview> review = Optional.empty();

    private Optional<String> prescriberNpi = Optional.empty();

    private Optional<String> prescriberName = Optional.empty();

    private Optional<String> patientExternalId = Optional.empty();

    private List<GetOrderResponseLifecycleEventsItem> lifecycleEvents = new ArrayList<>();

    private List<GetOrderResponseFulfillmentsItem> fulfillments = new ArrayList<>();

    private Optional<String> externalOrderId = Optional.empty();

    private Optional<Integer> practiceMedicationTotalCents = Optional.empty();

    private List<GetOrderResponseOtcItemsItem> otcItems = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetOrderResponse other) {
      revision(other.getRevision());
      otcItems(other.getOtcItems());
      practiceMedicationTotalCents(other.getPracticeMedicationTotalCents());
      externalOrderId(other.getExternalOrderId());
      metadata(other.getMetadata());
      createdAt(other.getCreatedAt());
      fulfillments(other.getFulfillments());
      id(other.getId());
      lifecycleEvents(other.getLifecycleEvents());
      livemode(other.getLivemode());
      object(other.getObject());
      patientExternalId(other.getPatientExternalId());
      patientId(other.getPatientId());
      patientName(other.getPatientName());
      patientState(other.getPatientState());
      practiceId(other.getPracticeId());
      prescriberName(other.getPrescriberName());
      prescriberNpi(other.getPrescriberNpi());
      review(other.getReview());
      prescriptions(other.getPrescriptions());
      status(other.getStatus());
      updatedAt(other.getUpdatedAt());
      return this;
    }

    /**
     * <p>Opaque revision of the complete order prescription set. Send the revision you reviewed as expectedRevision; never replace it automatically after a conflict.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("revision")
    public MetadataStage revision(@NotNull String revision) {
      this.revision = Objects.requireNonNull(revision, "revision must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("metadata")
    public CreatedAtStage metadata(@NotNull GetOrderResponseMetadata metadata) {
      this.metadata = Objects.requireNonNull(metadata, "metadata must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public IdStage createdAt(@NotNull String createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public LivemodeStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("livemode")
    public ObjectStage livemode(boolean livemode) {
      this.livemode = livemode;
      return this;
    }

    @java.lang.Override
    @JsonSetter("object")
    public PatientIdStage object(@NotNull GetOrderResponseObject object) {
      this.object = Objects.requireNonNull(object, "object must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("patientId")
    public PatientNameStage patientId(@NotNull String patientId) {
      this.patientId = Objects.requireNonNull(patientId, "patientId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("patientName")
    public PatientStateStage patientName(@NotNull String patientName) {
      this.patientName = Objects.requireNonNull(patientName, "patientName must not be null");
      return this;
    }

    /**
     * <p>The patient's current clinical state. This is not the saved delivery state; use each prescription's deliveryAddress for shipping.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("patientState")
    public PracticeIdStage patientState(@NotNull String patientState) {
      this.patientState = Objects.requireNonNull(patientState, "patientState must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("practiceId")
    public StatusStage practiceId(@NotNull String practiceId) {
      this.practiceId = Objects.requireNonNull(practiceId, "practiceId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public UpdatedAtStage status(@NotNull GetOrderResponseStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("updatedAt")
    public _FinalStage updatedAt(@NotNull String updatedAt) {
      this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllPrescriptions(List<GetOrderResponsePrescriptionsItem> prescriptions) {
      if (prescriptions != null) {
        this.prescriptions.addAll(prescriptions);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addPrescriptions(GetOrderResponsePrescriptionsItem prescriptions) {
      this.prescriptions.add(prescriptions);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "prescriptions",
        nulls = Nulls.SKIP
    )
    public _FinalStage prescriptions(List<GetOrderResponsePrescriptionsItem> prescriptions) {
      this.prescriptions.clear();
      if (prescriptions != null) {
        this.prescriptions.addAll(prescriptions);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage review(Nullable<GetOrderResponseReview> review) {
      if (review.isNull()) {
        this.review = null;
      }
      else if (review.isEmpty()) {
        this.review = Optional.empty();
      }
      else {
        this.review = Optional.of(review.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage review(GetOrderResponseReview review) {
      this.review = Optional.ofNullable(review);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "review",
        nulls = Nulls.SKIP
    )
    public _FinalStage review(Optional<GetOrderResponseReview> review) {
      this.review = review;
      return this;
    }

    @java.lang.Override
    public _FinalStage prescriberNpi(Nullable<String> prescriberNpi) {
      if (prescriberNpi.isNull()) {
        this.prescriberNpi = null;
      }
      else if (prescriberNpi.isEmpty()) {
        this.prescriberNpi = Optional.empty();
      }
      else {
        this.prescriberNpi = Optional.of(prescriberNpi.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage prescriberNpi(String prescriberNpi) {
      this.prescriberNpi = Optional.ofNullable(prescriberNpi);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "prescriberNpi",
        nulls = Nulls.SKIP
    )
    public _FinalStage prescriberNpi(Optional<String> prescriberNpi) {
      this.prescriberNpi = prescriberNpi;
      return this;
    }

    @java.lang.Override
    public _FinalStage prescriberName(Nullable<String> prescriberName) {
      if (prescriberName.isNull()) {
        this.prescriberName = null;
      }
      else if (prescriberName.isEmpty()) {
        this.prescriberName = Optional.empty();
      }
      else {
        this.prescriberName = Optional.of(prescriberName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage prescriberName(String prescriberName) {
      this.prescriberName = Optional.ofNullable(prescriberName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "prescriberName",
        nulls = Nulls.SKIP
    )
    public _FinalStage prescriberName(Optional<String> prescriberName) {
      this.prescriberName = prescriberName;
      return this;
    }

    @java.lang.Override
    public _FinalStage patientExternalId(Nullable<String> patientExternalId) {
      if (patientExternalId.isNull()) {
        this.patientExternalId = null;
      }
      else if (patientExternalId.isEmpty()) {
        this.patientExternalId = Optional.empty();
      }
      else {
        this.patientExternalId = Optional.of(patientExternalId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage patientExternalId(String patientExternalId) {
      this.patientExternalId = Optional.ofNullable(patientExternalId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "patientExternalId",
        nulls = Nulls.SKIP
    )
    public _FinalStage patientExternalId(Optional<String> patientExternalId) {
      this.patientExternalId = patientExternalId;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLifecycleEvents(
        List<GetOrderResponseLifecycleEventsItem> lifecycleEvents) {
      if (lifecycleEvents != null) {
        this.lifecycleEvents.addAll(lifecycleEvents);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addLifecycleEvents(GetOrderResponseLifecycleEventsItem lifecycleEvents) {
      this.lifecycleEvents.add(lifecycleEvents);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lifecycleEvents",
        nulls = Nulls.SKIP
    )
    public _FinalStage lifecycleEvents(List<GetOrderResponseLifecycleEventsItem> lifecycleEvents) {
      this.lifecycleEvents.clear();
      if (lifecycleEvents != null) {
        this.lifecycleEvents.addAll(lifecycleEvents);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllFulfillments(List<GetOrderResponseFulfillmentsItem> fulfillments) {
      if (fulfillments != null) {
        this.fulfillments.addAll(fulfillments);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addFulfillments(GetOrderResponseFulfillmentsItem fulfillments) {
      this.fulfillments.add(fulfillments);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "fulfillments",
        nulls = Nulls.SKIP
    )
    public _FinalStage fulfillments(List<GetOrderResponseFulfillmentsItem> fulfillments) {
      this.fulfillments.clear();
      if (fulfillments != null) {
        this.fulfillments.addAll(fulfillments);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage externalOrderId(Nullable<String> externalOrderId) {
      if (externalOrderId.isNull()) {
        this.externalOrderId = null;
      }
      else if (externalOrderId.isEmpty()) {
        this.externalOrderId = Optional.empty();
      }
      else {
        this.externalOrderId = Optional.of(externalOrderId.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage externalOrderId(String externalOrderId) {
      this.externalOrderId = Optional.ofNullable(externalOrderId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "externalOrderId",
        nulls = Nulls.SKIP
    )
    public _FinalStage externalOrderId(Optional<String> externalOrderId) {
      this.externalOrderId = externalOrderId;
      return this;
    }

    /**
     * <p>Snapshot of the practice-facing medication total. Null until every prescription has recorded submission pricing. Excludes shipping and supplies.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage practiceMedicationTotalCents(
        Nullable<Integer> practiceMedicationTotalCents) {
      if (practiceMedicationTotalCents.isNull()) {
        this.practiceMedicationTotalCents = null;
      }
      else if (practiceMedicationTotalCents.isEmpty()) {
        this.practiceMedicationTotalCents = Optional.empty();
      }
      else {
        this.practiceMedicationTotalCents = Optional.of(practiceMedicationTotalCents.get());
      }
      return this;
    }

    /**
     * <p>Snapshot of the practice-facing medication total. Null until every prescription has recorded submission pricing. Excludes shipping and supplies.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage practiceMedicationTotalCents(Integer practiceMedicationTotalCents) {
      this.practiceMedicationTotalCents = Optional.ofNullable(practiceMedicationTotalCents);
      return this;
    }

    /**
     * <p>Snapshot of the practice-facing medication total. Null until every prescription has recorded submission pricing. Excludes shipping and supplies.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "practiceMedicationTotalCents",
        nulls = Nulls.SKIP
    )
    public _FinalStage practiceMedicationTotalCents(
        Optional<Integer> practiceMedicationTotalCents) {
      this.practiceMedicationTotalCents = practiceMedicationTotalCents;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllOtcItems(List<GetOrderResponseOtcItemsItem> otcItems) {
      if (otcItems != null) {
        this.otcItems.addAll(otcItems);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addOtcItems(GetOrderResponseOtcItemsItem otcItems) {
      this.otcItems.add(otcItems);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "otcItems",
        nulls = Nulls.SKIP
    )
    public _FinalStage otcItems(List<GetOrderResponseOtcItemsItem> otcItems) {
      this.otcItems.clear();
      if (otcItems != null) {
        this.otcItems.addAll(otcItems);
      }
      return this;
    }

    @java.lang.Override
    public GetOrderResponse build() {
      return new GetOrderResponse(revision, otcItems, practiceMedicationTotalCents, externalOrderId, metadata, createdAt, fulfillments, id, lifecycleEvents, livemode, object, patientExternalId, patientId, patientName, patientState, practiceId, prescriberName, prescriberNpi, review, prescriptions, status, updatedAt, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public String revision() { return getRevision(); }

  public List<GetOrderResponseOtcItemsItem> otcItems() { return getOtcItems(); }

  public Optional<Integer> practiceMedicationTotalCents() { return getPracticeMedicationTotalCents(); }

  public Optional<String> externalOrderId() { return getExternalOrderId(); }

  public GetOrderResponseMetadata metadata() { return getMetadata(); }

  public String createdAt() { return getCreatedAt(); }

  public List<GetOrderResponseFulfillmentsItem> fulfillments() { return getFulfillments(); }

  public String id() { return getId(); }

  public List<GetOrderResponseLifecycleEventsItem> lifecycleEvents() { return getLifecycleEvents(); }

  public boolean livemode() { return getLivemode(); }

  public GetOrderResponseObject object() { return getObject(); }

  public Optional<String> patientExternalId() { return getPatientExternalId(); }

  public String patientId() { return getPatientId(); }

  public String patientName() { return getPatientName(); }

  public String patientState() { return getPatientState(); }

  public String practiceId() { return getPracticeId(); }

  public Optional<String> prescriberName() { return getPrescriberName(); }

  public Optional<String> prescriberNpi() { return getPrescriberNpi(); }

  public Optional<GetOrderResponseReview> review() { return getReview(); }

  public List<GetOrderResponsePrescriptionsItem> prescriptions() { return getPrescriptions(); }

  public GetOrderResponseStatus status() { return getStatus(); }

  public String updatedAt() { return getUpdatedAt(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
