/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetPracticeTeamInvitationResponsePersonAccountRolesItem.Builder.class
)
public final class GetPracticeTeamInvitationResponsePersonAccountRolesItem {
  private final String id;

  private final String name;

  private final Optional<String> key;

  private final Map<String, Object> additionalProperties;

  private GetPracticeTeamInvitationResponsePersonAccountRolesItem(String id, String name,
      Optional<String> key, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.key = key;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonIgnore
  public Optional<String> getKey() {
    if (key == null) {
      return Optional.empty();
    }
    return key;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("key")
  private Optional<String> _getKey() {
    return key;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetPracticeTeamInvitationResponsePersonAccountRolesItem && equalTo((GetPracticeTeamInvitationResponsePersonAccountRolesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetPracticeTeamInvitationResponsePersonAccountRolesItem other) {
    return id.equals(other.id) && name.equals(other.name) && key.equals(other.key);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.key);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    NameStage id(@NotNull String id);

    Builder from(GetPracticeTeamInvitationResponsePersonAccountRolesItem other);
  }

  public interface NameStage {
    _FinalStage name(@NotNull String name);
  }

  public interface _FinalStage {
    GetPracticeTeamInvitationResponsePersonAccountRolesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage key(Optional<String> key);

    _FinalStage key(String key);

    _FinalStage key(Nullable<String> key);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, NameStage, _FinalStage {
    private String id;

    private String name;

    private Optional<String> key = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetPracticeTeamInvitationResponsePersonAccountRolesItem other) {
      id(other.getId());
      name(other.getName());
      key(other.getKey());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public _FinalStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage key(Nullable<String> key) {
      if (key.isNull()) {
        this.key = null;
      }
      else if (key.isEmpty()) {
        this.key = Optional.empty();
      }
      else {
        this.key = Optional.of(key.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage key(String key) {
      this.key = Optional.ofNullable(key);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "key",
        nulls = Nulls.SKIP
    )
    public _FinalStage key(Optional<String> key) {
      this.key = key;
      return this;
    }

    @java.lang.Override
    public GetPracticeTeamInvitationResponsePersonAccountRolesItem build() {
      return new GetPracticeTeamInvitationResponsePersonAccountRolesItem(id, name, key, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public String id() { return getId(); }

  public String name() { return getName(); }

  public Optional<String> key() { return getKey(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
