/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetPatientAllergiesResponseAllergiesItemSource {
  public static final GetPatientAllergiesResponseAllergiesItemSource DOCTOR = new GetPatientAllergiesResponseAllergiesItemSource(Value.DOCTOR, "Doctor");

  public static final GetPatientAllergiesResponseAllergiesItemSource PHARMACIST = new GetPatientAllergiesResponseAllergiesItemSource(Value.PHARMACIST, "Pharmacist");

  public static final GetPatientAllergiesResponseAllergiesItemSource PATIENT = new GetPatientAllergiesResponseAllergiesItemSource(Value.PATIENT, "Patient");

  public static final GetPatientAllergiesResponseAllergiesItemSource PATIENT_AGENT_GUARDIAN = new GetPatientAllergiesResponseAllergiesItemSource(Value.PATIENT_AGENT_GUARDIAN, "Patient Agent/Guardian");

  private final Value value;

  private final String string;

  GetPatientAllergiesResponseAllergiesItemSource(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetPatientAllergiesResponseAllergiesItemSource && this.string.equals(((GetPatientAllergiesResponseAllergiesItemSource) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DOCTOR:
        return visitor.visitDoctor();
      case PHARMACIST:
        return visitor.visitPharmacist();
      case PATIENT:
        return visitor.visitPatient();
      case PATIENT_AGENT_GUARDIAN:
        return visitor.visitPatientAgentGuardian();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetPatientAllergiesResponseAllergiesItemSource valueOf(String value) {
    switch (value) {
      case "Doctor":
        return DOCTOR;
      case "Pharmacist":
        return PHARMACIST;
      case "Patient":
        return PATIENT;
      case "Patient Agent/Guardian":
        return PATIENT_AGENT_GUARDIAN;
      default:
        return new GetPatientAllergiesResponseAllergiesItemSource(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DOCTOR,

    PATIENT,

    PATIENT_AGENT_GUARDIAN,

    PHARMACIST,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDoctor();

    T visitPatient();

    T visitPatientAgentGuardian();

    T visitPharmacist();

    T visitUnknown(String unknownType);
  }
}
