/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetPatientResponseMeasurementsItem.Builder.class
)
public final class GetPatientResponseMeasurementsItem {
  private final Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters;

  private final String recordedAt;

  private final String source;

  private final Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms;

  private final Map<String, Object> additionalProperties;

  private GetPatientResponseMeasurementsItem(
      Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters,
      String recordedAt, String source,
      Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms,
      Map<String, Object> additionalProperties) {
    this.heightCentimeters = heightCentimeters;
    this.recordedAt = recordedAt;
    this.source = source;
    this.weightKilograms = weightKilograms;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<GetPatientResponseMeasurementsItemHeightCentimeters> getHeightCentimeters() {
    if (heightCentimeters == null) {
      return Optional.empty();
    }
    return heightCentimeters;
  }

  @JsonProperty("recordedAt")
  public String getRecordedAt() {
    return recordedAt;
  }

  @JsonProperty("source")
  public String getSource() {
    return source;
  }

  @JsonIgnore
  public Optional<GetPatientResponseMeasurementsItemWeightKilograms> getWeightKilograms() {
    if (weightKilograms == null) {
      return Optional.empty();
    }
    return weightKilograms;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("heightCentimeters")
  private Optional<GetPatientResponseMeasurementsItemHeightCentimeters> _getHeightCentimeters() {
    return heightCentimeters;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("weightKilograms")
  private Optional<GetPatientResponseMeasurementsItemWeightKilograms> _getWeightKilograms() {
    return weightKilograms;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetPatientResponseMeasurementsItem && equalTo((GetPatientResponseMeasurementsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetPatientResponseMeasurementsItem other) {
    return heightCentimeters.equals(other.heightCentimeters) && recordedAt.equals(other.recordedAt) && source.equals(other.source) && weightKilograms.equals(other.weightKilograms);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.heightCentimeters, this.recordedAt, this.source, this.weightKilograms);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RecordedAtStage builder() {
    return new Builder();
  }

  public interface RecordedAtStage {
    SourceStage recordedAt(@NotNull String recordedAt);

    Builder from(GetPatientResponseMeasurementsItem other);
  }

  public interface SourceStage {
    _FinalStage source(@NotNull String source);
  }

  public interface _FinalStage {
    GetPatientResponseMeasurementsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage heightCentimeters(
        Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters);

    _FinalStage heightCentimeters(
        GetPatientResponseMeasurementsItemHeightCentimeters heightCentimeters);

    _FinalStage heightCentimeters(
        Nullable<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters);

    _FinalStage weightKilograms(
        Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms);

    _FinalStage weightKilograms(GetPatientResponseMeasurementsItemWeightKilograms weightKilograms);

    _FinalStage weightKilograms(
        Nullable<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RecordedAtStage, SourceStage, _FinalStage {
    private String recordedAt;

    private String source;

    private Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms = Optional.empty();

    private Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetPatientResponseMeasurementsItem other) {
      heightCentimeters(other.getHeightCentimeters());
      recordedAt(other.getRecordedAt());
      source(other.getSource());
      weightKilograms(other.getWeightKilograms());
      return this;
    }

    @java.lang.Override
    @JsonSetter("recordedAt")
    public SourceStage recordedAt(@NotNull String recordedAt) {
      this.recordedAt = Objects.requireNonNull(recordedAt, "recordedAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("source")
    public _FinalStage source(@NotNull String source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage weightKilograms(
        Nullable<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms) {
      if (weightKilograms.isNull()) {
        this.weightKilograms = null;
      }
      else if (weightKilograms.isEmpty()) {
        this.weightKilograms = Optional.empty();
      }
      else {
        this.weightKilograms = Optional.of(weightKilograms.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage weightKilograms(
        GetPatientResponseMeasurementsItemWeightKilograms weightKilograms) {
      this.weightKilograms = Optional.ofNullable(weightKilograms);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "weightKilograms",
        nulls = Nulls.SKIP
    )
    public _FinalStage weightKilograms(
        Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms) {
      this.weightKilograms = weightKilograms;
      return this;
    }

    @java.lang.Override
    public _FinalStage heightCentimeters(
        Nullable<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters) {
      if (heightCentimeters.isNull()) {
        this.heightCentimeters = null;
      }
      else if (heightCentimeters.isEmpty()) {
        this.heightCentimeters = Optional.empty();
      }
      else {
        this.heightCentimeters = Optional.of(heightCentimeters.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage heightCentimeters(
        GetPatientResponseMeasurementsItemHeightCentimeters heightCentimeters) {
      this.heightCentimeters = Optional.ofNullable(heightCentimeters);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "heightCentimeters",
        nulls = Nulls.SKIP
    )
    public _FinalStage heightCentimeters(
        Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters) {
      this.heightCentimeters = heightCentimeters;
      return this;
    }

    @java.lang.Override
    public GetPatientResponseMeasurementsItem build() {
      return new GetPatientResponseMeasurementsItem(heightCentimeters, recordedAt, source, weightKilograms, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public Optional<GetPatientResponseMeasurementsItemHeightCentimeters> heightCentimeters() { return getHeightCentimeters(); }

  public String recordedAt() { return getRecordedAt(); }

  public String source() { return getSource(); }

  public Optional<GetPatientResponseMeasurementsItemWeightKilograms> weightKilograms() { return getWeightKilograms(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
