/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListPracticeTeamMembersResponseObject {
  public static final ListPracticeTeamMembersResponseObject LIST = new ListPracticeTeamMembersResponseObject(Value.LIST, "list");

  private final Value value;

  private final String string;

  ListPracticeTeamMembersResponseObject(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListPracticeTeamMembersResponseObject && this.string.equals(((ListPracticeTeamMembersResponseObject) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LIST:
        return visitor.visitList();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListPracticeTeamMembersResponseObject valueOf(String value) {
    switch (value) {
      case "list":
        return LIST;
      default:
        return new ListPracticeTeamMembersResponseObject(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    LIST,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitList();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
