/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCatalogItemsResponseDataItemComposition.Builder.class
)
public final class ListCatalogItemsResponseDataItemComposition {
  private final ListCatalogItemsResponseDataItemCompositionStatus status;

  private final List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients;

  private final Map<String, Object> additionalProperties;

  private ListCatalogItemsResponseDataItemComposition(
      ListCatalogItemsResponseDataItemCompositionStatus status,
      List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.ingredients = ingredients;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public ListCatalogItemsResponseDataItemCompositionStatus getStatus() {
    return status;
  }

  @JsonProperty("ingredients")
  public List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> getIngredients() {
    return ingredients;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCatalogItemsResponseDataItemComposition && equalTo((ListCatalogItemsResponseDataItemComposition) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCatalogItemsResponseDataItemComposition other) {
    return status.equals(other.status) && ingredients.equals(other.ingredients);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.ingredients);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    _FinalStage status(@NotNull ListCatalogItemsResponseDataItemCompositionStatus status);

    Builder from(ListCatalogItemsResponseDataItemComposition other);
  }

  public interface _FinalStage {
    ListCatalogItemsResponseDataItemComposition build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage ingredients(
        List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients);

    _FinalStage addIngredients(
        ListCatalogItemsResponseDataItemCompositionIngredientsItem ingredients);

    _FinalStage addAllIngredients(
        List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, _FinalStage {
    private ListCatalogItemsResponseDataItemCompositionStatus status;

    private List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListCatalogItemsResponseDataItemComposition other) {
      status(other.getStatus());
      ingredients(other.getIngredients());
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public _FinalStage status(@NotNull ListCatalogItemsResponseDataItemCompositionStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllIngredients(
        List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients) {
      if (ingredients != null) {
        this.ingredients.addAll(ingredients);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addIngredients(
        ListCatalogItemsResponseDataItemCompositionIngredientsItem ingredients) {
      this.ingredients.add(ingredients);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "ingredients",
        nulls = Nulls.SKIP
    )
    public _FinalStage ingredients(
        List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients) {
      this.ingredients.clear();
      if (ingredients != null) {
        this.ingredients.addAll(ingredients);
      }
      return this;
    }

    @java.lang.Override
    public ListCatalogItemsResponseDataItemComposition build() {
      return new ListCatalogItemsResponseDataItemComposition(status, ingredients, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public ListCatalogItemsResponseDataItemCompositionStatus status() { return getStatus(); }

  public List<ListCatalogItemsResponseDataItemCompositionIngredientsItem> ingredients() { return getIngredients(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
