/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListPatientsResponse.Builder.class
)
public final class ListPatientsResponse {
  private final List<ListPatientsResponseDataItem> data;

  private final boolean hasMore;

  private final ListPatientsResponseObject object;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private ListPatientsResponse(List<ListPatientsResponseDataItem> data, boolean hasMore,
      ListPatientsResponseObject object, String url, Map<String, Object> additionalProperties) {
    this.data = data;
    this.hasMore = hasMore;
    this.object = object;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("data")
  public List<ListPatientsResponseDataItem> getData() {
    return data;
  }

  @JsonProperty("hasMore")
  public boolean getHasMore() {
    return hasMore;
  }

  @JsonProperty("object")
  public ListPatientsResponseObject getObject() {
    return object;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListPatientsResponse && equalTo((ListPatientsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListPatientsResponse other) {
    return data.equals(other.data) && hasMore == other.hasMore && object.equals(other.object) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.hasMore, this.object, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static HasMoreStage builder() {
    return new Builder();
  }

  public interface HasMoreStage {
    ObjectStage hasMore(boolean hasMore);

    Builder from(ListPatientsResponse other);
  }

  public interface ObjectStage {
    UrlStage object(@NotNull ListPatientsResponseObject object);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    ListPatientsResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage data(List<ListPatientsResponseDataItem> data);

    _FinalStage addData(ListPatientsResponseDataItem data);

    _FinalStage addAllData(List<ListPatientsResponseDataItem> data);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements HasMoreStage, ObjectStage, UrlStage, _FinalStage {
    private boolean hasMore;

    private ListPatientsResponseObject object;

    private String url;

    private List<ListPatientsResponseDataItem> data = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListPatientsResponse other) {
      data(other.getData());
      hasMore(other.getHasMore());
      object(other.getObject());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("hasMore")
    public ObjectStage hasMore(boolean hasMore) {
      this.hasMore = hasMore;
      return this;
    }

    @java.lang.Override
    @JsonSetter("object")
    public UrlStage object(@NotNull ListPatientsResponseObject object) {
      this.object = Objects.requireNonNull(object, "object must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllData(List<ListPatientsResponseDataItem> data) {
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addData(ListPatientsResponseDataItem data) {
      this.data.add(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(List<ListPatientsResponseDataItem> data) {
      this.data.clear();
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public ListPatientsResponse build() {
      return new ListPatientsResponse(data, hasMore, object, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public List<ListPatientsResponseDataItem> data() { return getData(); }

  public boolean hasMore() { return getHasMore(); }

  public ListPatientsResponseObject object() { return getObject(); }

  public String url() { return getUrl(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
