/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview {
  public static final ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview REQUIRED = new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview(Value.REQUIRED, "required");

  public static final ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview OPTIONAL = new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview(Value.OPTIONAL, "optional");

  private final Value value;

  private final String string;

  ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview(Value value,
      String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview && this.string.equals(((ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case REQUIRED:
        return visitor.visitRequired();
      case OPTIONAL:
        return visitor.visitOptional();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview valueOf(
      String value) {
    switch (value) {
      case "required":
        return REQUIRED;
      case "optional":
        return OPTIONAL;
      default:
        return new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosisReview(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    OPTIONAL,

    REQUIRED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitOptional();

    T visitRequired();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
