/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis {
  public static final ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis NOT_REQUIRED = new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis(Value.NOT_REQUIRED, "not_required");

  public static final ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis REQUIRED = new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis(Value.REQUIRED, "required");

  public static final ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis OPTIONAL = new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis(Value.OPTIONAL, "optional");

  private final Value value;

  private final String string;

  ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis && this.string.equals(((ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case NOT_REQUIRED:
        return visitor.visitNotRequired();
      case REQUIRED:
        return visitor.visitRequired();
      case OPTIONAL:
        return visitor.visitOptional();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis valueOf(
      String value) {
    switch (value) {
      case "not_required":
        return NOT_REQUIRED;
      case "required":
        return REQUIRED;
      case "optional":
        return OPTIONAL;
      default:
        return new ListCatalogItemsResponseDataItemPrescriptionRequirementsDiagnosis(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NOT_REQUIRED,

    OPTIONAL,

    REQUIRED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNotRequired();

    T visitOptional();

    T visitRequired();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
