/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity {
  public static final ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity CRITICAL = new ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity(Value.CRITICAL, "critical");

  public static final ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity WARNING = new ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity(Value.WARNING, "warning");

  private final Value value;

  private final String string;

  ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity && this.string.equals(((ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CRITICAL:
        return visitor.visitCritical();
      case WARNING:
        return visitor.visitWarning();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity valueOf(
      String value) {
    switch (value) {
      case "critical":
        return CRITICAL;
      case "warning":
        return WARNING;
      default:
        return new ListOrdersResponseDataItemFulfillmentsItemExceptionsItemSeverity(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    WARNING,

    CRITICAL,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitWarning();

    T visitCritical();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
