/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCatalogItemsResponseDataItemQuantityConstraintChoices.Builder.class
)
public final class ListCatalogItemsResponseDataItemQuantityConstraintChoices {
  private final List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> quantities;

  private final Map<String, Object> additionalProperties;

  private ListCatalogItemsResponseDataItemQuantityConstraintChoices(
      List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> quantities,
      Map<String, Object> additionalProperties) {
    this.quantities = quantities;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("quantities")
  public List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> getQuantities(
      ) {
    return quantities;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCatalogItemsResponseDataItemQuantityConstraintChoices && equalTo((ListCatalogItemsResponseDataItemQuantityConstraintChoices) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCatalogItemsResponseDataItemQuantityConstraintChoices other) {
    return quantities.equals(other.quantities);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.quantities);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> quantities = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListCatalogItemsResponseDataItemQuantityConstraintChoices other) {
      quantities(other.getQuantities());
      return this;
    }

    @JsonSetter(
        value = "quantities",
        nulls = Nulls.SKIP
    )
    public Builder quantities(
        List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> quantities) {
      this.quantities.clear();
      if (quantities != null) {
        this.quantities.addAll(quantities);
      }
      return this;
    }

    public Builder addQuantities(
        ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem quantities) {
      this.quantities.add(quantities);
      return this;
    }

    public Builder addAllQuantities(
        List<ListCatalogItemsResponseDataItemQuantityConstraintChoicesQuantitiesItem> quantities) {
      if (quantities != null) {
        this.quantities.addAll(quantities);
      }
      return this;
    }

    public ListCatalogItemsResponseDataItemQuantityConstraintChoices build() {
      return new ListCatalogItemsResponseDataItemQuantityConstraintChoices(quantities, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
