/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListCatalogItemsResponseDataItemPricing.Builder.class
)
public final class ListCatalogItemsResponseDataItemPricing {
  private final int amountCents;

  private final ListCatalogItemsResponseDataItemPricingBasis basis;

  private final ListCatalogItemsResponseDataItemPricingCurrency currency;

  private final int medicationSubtotalCents;

  private final Map<String, Object> additionalProperties;

  private ListCatalogItemsResponseDataItemPricing(int amountCents,
      ListCatalogItemsResponseDataItemPricingBasis basis,
      ListCatalogItemsResponseDataItemPricingCurrency currency, int medicationSubtotalCents,
      Map<String, Object> additionalProperties) {
    this.amountCents = amountCents;
    this.basis = basis;
    this.currency = currency;
    this.medicationSubtotalCents = medicationSubtotalCents;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("amountCents")
  public int getAmountCents() {
    return amountCents;
  }

  @JsonProperty("basis")
  public ListCatalogItemsResponseDataItemPricingBasis getBasis() {
    return basis;
  }

  @JsonProperty("currency")
  public ListCatalogItemsResponseDataItemPricingCurrency getCurrency() {
    return currency;
  }

  @JsonProperty("medicationSubtotalCents")
  public int getMedicationSubtotalCents() {
    return medicationSubtotalCents;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListCatalogItemsResponseDataItemPricing && equalTo((ListCatalogItemsResponseDataItemPricing) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListCatalogItemsResponseDataItemPricing other) {
    return amountCents == other.amountCents && basis.equals(other.basis) && currency.equals(other.currency) && medicationSubtotalCents == other.medicationSubtotalCents;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.amountCents, this.basis, this.currency, this.medicationSubtotalCents);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static AmountCentsStage builder() {
    return new Builder();
  }

  public interface AmountCentsStage {
    BasisStage amountCents(int amountCents);

    Builder from(ListCatalogItemsResponseDataItemPricing other);
  }

  public interface BasisStage {
    CurrencyStage basis(@NotNull ListCatalogItemsResponseDataItemPricingBasis basis);
  }

  public interface CurrencyStage {
    MedicationSubtotalCentsStage currency(
        @NotNull ListCatalogItemsResponseDataItemPricingCurrency currency);
  }

  public interface MedicationSubtotalCentsStage {
    _FinalStage medicationSubtotalCents(int medicationSubtotalCents);
  }

  public interface _FinalStage {
    ListCatalogItemsResponseDataItemPricing build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements AmountCentsStage, BasisStage, CurrencyStage, MedicationSubtotalCentsStage, _FinalStage {
    private int amountCents;

    private ListCatalogItemsResponseDataItemPricingBasis basis;

    private ListCatalogItemsResponseDataItemPricingCurrency currency;

    private int medicationSubtotalCents;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListCatalogItemsResponseDataItemPricing other) {
      amountCents(other.getAmountCents());
      basis(other.getBasis());
      currency(other.getCurrency());
      medicationSubtotalCents(other.getMedicationSubtotalCents());
      return this;
    }

    @java.lang.Override
    @JsonSetter("amountCents")
    public BasisStage amountCents(int amountCents) {
      this.amountCents = amountCents;
      return this;
    }

    @java.lang.Override
    @JsonSetter("basis")
    public CurrencyStage basis(@NotNull ListCatalogItemsResponseDataItemPricingBasis basis) {
      this.basis = Objects.requireNonNull(basis, "basis must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("currency")
    public MedicationSubtotalCentsStage currency(
        @NotNull ListCatalogItemsResponseDataItemPricingCurrency currency) {
      this.currency = Objects.requireNonNull(currency, "currency must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("medicationSubtotalCents")
    public _FinalStage medicationSubtotalCents(int medicationSubtotalCents) {
      this.medicationSubtotalCents = medicationSubtotalCents;
      return this;
    }

    @java.lang.Override
    public ListCatalogItemsResponseDataItemPricing build() {
      return new ListCatalogItemsResponseDataItemPricing(amountCents, basis, currency, medicationSubtotalCents, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public int amountCents() { return getAmountCents(); }

  public ListCatalogItemsResponseDataItemPricingBasis basis() { return getBasis(); }

  public ListCatalogItemsResponseDataItemPricingCurrency currency() { return getCurrency(); }

  public int medicationSubtotalCents() { return getMedicationSubtotalCents(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
