/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent {
  public static final ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent SHIPPING = new ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent(Value.SHIPPING, "shipping");

  private final Value value;

  private final String string;

  ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent(Value value,
      String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent && this.string.equals(((ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SHIPPING:
        return visitor.visitShipping();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent valueOf(
      String value) {
    switch (value) {
      case "shipping":
        return SHIPPING;
      default:
        return new ListCatalogItemsResponseDataItemFulfillmentInclusionsItemPriceComponent(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    SHIPPING,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitShipping();

    T visitUnknown(String unknownType);
  }
}
