/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PreviewOrderResponseTotalsCurrency {
  public static final PreviewOrderResponseTotalsCurrency USD = new PreviewOrderResponseTotalsCurrency(Value.USD, "USD");

  private final Value value;

  private final String string;

  PreviewOrderResponseTotalsCurrency(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PreviewOrderResponseTotalsCurrency && this.string.equals(((PreviewOrderResponseTotalsCurrency) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case USD:
        return visitor.visitUsd();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PreviewOrderResponseTotalsCurrency valueOf(String value) {
    switch (value) {
      case "USD":
        return USD;
      default:
        return new PreviewOrderResponseTotalsCurrency(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    USD,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUsd();

    T visitUnknown(String unknownType);
  }
}
