/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PreviewOrderResponseStatus {
  public static final PreviewOrderResponseStatus COMPLETE = new PreviewOrderResponseStatus(Value.COMPLETE, "complete");

  public static final PreviewOrderResponseStatus INCOMPLETE = new PreviewOrderResponseStatus(Value.INCOMPLETE, "incomplete");

  private final Value value;

  private final String string;

  PreviewOrderResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PreviewOrderResponseStatus && this.string.equals(((PreviewOrderResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case COMPLETE:
        return visitor.visitComplete();
      case INCOMPLETE:
        return visitor.visitIncomplete();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PreviewOrderResponseStatus valueOf(String value) {
    switch (value) {
      case "complete":
        return COMPLETE;
      case "incomplete":
        return INCOMPLETE;
      default:
        return new PreviewOrderResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    COMPLETE,

    INCOMPLETE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitComplete();

    T visitIncomplete();

    T visitUnknown(String unknownType);
  }
}
