/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PreviewOrderResponseIssuesItem.Builder.class
)
public final class PreviewOrderResponseIssuesItem {
  private final String code;

  private final String path;

  private final String message;

  private final Map<String, Object> additionalProperties;

  private PreviewOrderResponseIssuesItem(String code, String path, String message,
      Map<String, Object> additionalProperties) {
    this.code = code;
    this.path = path;
    this.message = message;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("code")
  public String getCode() {
    return code;
  }

  @JsonProperty("path")
  public String getPath() {
    return path;
  }

  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PreviewOrderResponseIssuesItem && equalTo((PreviewOrderResponseIssuesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PreviewOrderResponseIssuesItem other) {
    return code.equals(other.code) && path.equals(other.path) && message.equals(other.message);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.path, this.message);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CodeStage builder() {
    return new Builder();
  }

  public interface CodeStage {
    PathStage code(@NotNull String code);

    Builder from(PreviewOrderResponseIssuesItem other);
  }

  public interface PathStage {
    MessageStage path(@NotNull String path);
  }

  public interface MessageStage {
    _FinalStage message(@NotNull String message);
  }

  public interface _FinalStage {
    PreviewOrderResponseIssuesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CodeStage, PathStage, MessageStage, _FinalStage {
    private String code;

    private String path;

    private String message;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PreviewOrderResponseIssuesItem other) {
      code(other.getCode());
      path(other.getPath());
      message(other.getMessage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("code")
    public PathStage code(@NotNull String code) {
      this.code = Objects.requireNonNull(code, "code must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("path")
    public MessageStage path(@NotNull String path) {
      this.path = Objects.requireNonNull(path, "path must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("message")
    public _FinalStage message(@NotNull String message) {
      this.message = Objects.requireNonNull(message, "message must not be null");
      return this;
    }

    @java.lang.Override
    public PreviewOrderResponseIssuesItem build() {
      return new PreviewOrderResponseIssuesItem(code, path, message, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public String code() { return getCode(); }

  public String path() { return getPath(); }

  public String message() { return getMessage(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
