/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PreviewOrderResponseClinicalRequirementsItemStatus {
  public static final PreviewOrderResponseClinicalRequirementsItemStatus MISSING = new PreviewOrderResponseClinicalRequirementsItemStatus(Value.MISSING, "missing");

  public static final PreviewOrderResponseClinicalRequirementsItemStatus SATISFIED = new PreviewOrderResponseClinicalRequirementsItemStatus(Value.SATISFIED, "satisfied");

  private final Value value;

  private final String string;

  PreviewOrderResponseClinicalRequirementsItemStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PreviewOrderResponseClinicalRequirementsItemStatus && this.string.equals(((PreviewOrderResponseClinicalRequirementsItemStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MISSING:
        return visitor.visitMissing();
      case SATISFIED:
        return visitor.visitSatisfied();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PreviewOrderResponseClinicalRequirementsItemStatus valueOf(String value) {
    switch (value) {
      case "missing":
        return MISSING;
      case "satisfied":
        return SATISFIED;
      default:
        return new PreviewOrderResponseClinicalRequirementsItemStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MISSING,

    SATISFIED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMissing();

    T visitSatisfied();

    T visitUnknown(String unknownType);
  }
}
