/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PreviewOrderResponseShippingGroupsItem.Builder.class
)
public final class PreviewOrderResponseShippingGroupsItem {
  private final String key;

  private final String pharmacy;

  private final String label;

  private final PreviewOrderResponseShippingGroupsItemTemperature temperature;

  private final int amountCents;

  private final int itemCount;

  private final List<Integer> prescriptionIndexes;

  private final Map<String, Object> additionalProperties;

  private PreviewOrderResponseShippingGroupsItem(String key, String pharmacy, String label,
      PreviewOrderResponseShippingGroupsItemTemperature temperature, int amountCents, int itemCount,
      List<Integer> prescriptionIndexes, Map<String, Object> additionalProperties) {
    this.key = key;
    this.pharmacy = pharmacy;
    this.label = label;
    this.temperature = temperature;
    this.amountCents = amountCents;
    this.itemCount = itemCount;
    this.prescriptionIndexes = prescriptionIndexes;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  @JsonProperty("pharmacy")
  public String getPharmacy() {
    return pharmacy;
  }

  @JsonProperty("label")
  public String getLabel() {
    return label;
  }

  @JsonProperty("temperature")
  public PreviewOrderResponseShippingGroupsItemTemperature getTemperature() {
    return temperature;
  }

  @JsonProperty("amountCents")
  public int getAmountCents() {
    return amountCents;
  }

  @JsonProperty("itemCount")
  public int getItemCount() {
    return itemCount;
  }

  /**
   * @return Zero-based indexes into the preview prescriptions array. This is an estimated shipping charge group, not a guarantee of one physical package.
   */
  @JsonProperty("prescriptionIndexes")
  public List<Integer> getPrescriptionIndexes() {
    return prescriptionIndexes;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PreviewOrderResponseShippingGroupsItem && equalTo((PreviewOrderResponseShippingGroupsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PreviewOrderResponseShippingGroupsItem other) {
    return key.equals(other.key) && pharmacy.equals(other.pharmacy) && label.equals(other.label) && temperature.equals(other.temperature) && amountCents == other.amountCents && itemCount == other.itemCount && prescriptionIndexes.equals(other.prescriptionIndexes);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.key, this.pharmacy, this.label, this.temperature, this.amountCents, this.itemCount, this.prescriptionIndexes);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static KeyStage builder() {
    return new Builder();
  }

  public interface KeyStage {
    PharmacyStage key(@NotNull String key);

    Builder from(PreviewOrderResponseShippingGroupsItem other);
  }

  public interface PharmacyStage {
    LabelStage pharmacy(@NotNull String pharmacy);
  }

  public interface LabelStage {
    TemperatureStage label(@NotNull String label);
  }

  public interface TemperatureStage {
    AmountCentsStage temperature(
        @NotNull PreviewOrderResponseShippingGroupsItemTemperature temperature);
  }

  public interface AmountCentsStage {
    ItemCountStage amountCents(int amountCents);
  }

  public interface ItemCountStage {
    _FinalStage itemCount(int itemCount);
  }

  public interface _FinalStage {
    PreviewOrderResponseShippingGroupsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Zero-based indexes into the preview prescriptions array. This is an estimated shipping charge group, not a guarantee of one physical package.</p>
     */
    _FinalStage prescriptionIndexes(List<Integer> prescriptionIndexes);

    _FinalStage addPrescriptionIndexes(Integer prescriptionIndexes);

    _FinalStage addAllPrescriptionIndexes(List<Integer> prescriptionIndexes);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements KeyStage, PharmacyStage, LabelStage, TemperatureStage, AmountCentsStage, ItemCountStage, _FinalStage {
    private String key;

    private String pharmacy;

    private String label;

    private PreviewOrderResponseShippingGroupsItemTemperature temperature;

    private int amountCents;

    private int itemCount;

    private List<Integer> prescriptionIndexes = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PreviewOrderResponseShippingGroupsItem other) {
      key(other.getKey());
      pharmacy(other.getPharmacy());
      label(other.getLabel());
      temperature(other.getTemperature());
      amountCents(other.getAmountCents());
      itemCount(other.getItemCount());
      prescriptionIndexes(other.getPrescriptionIndexes());
      return this;
    }

    @java.lang.Override
    @JsonSetter("key")
    public PharmacyStage key(@NotNull String key) {
      this.key = Objects.requireNonNull(key, "key must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("pharmacy")
    public LabelStage pharmacy(@NotNull String pharmacy) {
      this.pharmacy = Objects.requireNonNull(pharmacy, "pharmacy must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("label")
    public TemperatureStage label(@NotNull String label) {
      this.label = Objects.requireNonNull(label, "label must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("temperature")
    public AmountCentsStage temperature(
        @NotNull PreviewOrderResponseShippingGroupsItemTemperature temperature) {
      this.temperature = Objects.requireNonNull(temperature, "temperature must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("amountCents")
    public ItemCountStage amountCents(int amountCents) {
      this.amountCents = amountCents;
      return this;
    }

    @java.lang.Override
    @JsonSetter("itemCount")
    public _FinalStage itemCount(int itemCount) {
      this.itemCount = itemCount;
      return this;
    }

    /**
     * <p>Zero-based indexes into the preview prescriptions array. This is an estimated shipping charge group, not a guarantee of one physical package.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllPrescriptionIndexes(List<Integer> prescriptionIndexes) {
      if (prescriptionIndexes != null) {
        this.prescriptionIndexes.addAll(prescriptionIndexes);
      }
      return this;
    }

    /**
     * <p>Zero-based indexes into the preview prescriptions array. This is an estimated shipping charge group, not a guarantee of one physical package.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addPrescriptionIndexes(Integer prescriptionIndexes) {
      this.prescriptionIndexes.add(prescriptionIndexes);
      return this;
    }

    /**
     * <p>Zero-based indexes into the preview prescriptions array. This is an estimated shipping charge group, not a guarantee of one physical package.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "prescriptionIndexes",
        nulls = Nulls.SKIP
    )
    public _FinalStage prescriptionIndexes(List<Integer> prescriptionIndexes) {
      this.prescriptionIndexes.clear();
      if (prescriptionIndexes != null) {
        this.prescriptionIndexes.addAll(prescriptionIndexes);
      }
      return this;
    }

    @java.lang.Override
    public PreviewOrderResponseShippingGroupsItem build() {
      return new PreviewOrderResponseShippingGroupsItem(key, pharmacy, label, temperature, amountCents, itemCount, prescriptionIndexes, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
