/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus {
  public static final ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus DECLINED = new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.DECLINED, "declined");

  public static final ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus REVOKED = new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.REVOKED, "revoked");

  public static final ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus PENDING = new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.PENDING, "pending");

  public static final ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus EXPIRED = new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.EXPIRED, "expired");

  public static final ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus ACCEPTED = new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.ACCEPTED, "accepted");

  private final Value value;

  private final String string;

  ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus && this.string.equals(((ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DECLINED:
        return visitor.visitDeclined();
      case REVOKED:
        return visitor.visitRevoked();
      case PENDING:
        return visitor.visitPending();
      case EXPIRED:
        return visitor.visitExpired();
      case ACCEPTED:
        return visitor.visitAccepted();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus valueOf(
      String value) {
    switch (value) {
      case "declined":
        return DECLINED;
      case "revoked":
        return REVOKED;
      case "pending":
        return PENDING;
      case "expired":
        return EXPIRED;
      case "accepted":
        return ACCEPTED;
      default:
        return new ResendPracticeTeamInvitationResponseInvitationPersonInvitationStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACCEPTED,

    DECLINED,

    PENDING,

    EXPIRED,

    REVOKED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAccepted();

    T visitDeclined();

    T visitPending();

    T visitExpired();

    T visitRevoked();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
