/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RetrievePrescribingOptionsResponseCatalogMedicationGroup.Builder.class
)
public final class RetrievePrescribingOptionsResponseCatalogMedicationGroup {
  private final RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount offerCount;

  private final RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount pharmacyCount;

  private final List<String> strengths;

  private final Map<String, Object> additionalProperties;

  private RetrievePrescribingOptionsResponseCatalogMedicationGroup(
      RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount offerCount,
      RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount pharmacyCount,
      List<String> strengths, Map<String, Object> additionalProperties) {
    this.offerCount = offerCount;
    this.pharmacyCount = pharmacyCount;
    this.strengths = strengths;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("offerCount")
  public RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount getOfferCount() {
    return offerCount;
  }

  @JsonProperty("pharmacyCount")
  public RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount getPharmacyCount() {
    return pharmacyCount;
  }

  @JsonProperty("strengths")
  public List<String> getStrengths() {
    return strengths;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RetrievePrescribingOptionsResponseCatalogMedicationGroup && equalTo((RetrievePrescribingOptionsResponseCatalogMedicationGroup) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RetrievePrescribingOptionsResponseCatalogMedicationGroup other) {
    return offerCount.equals(other.offerCount) && pharmacyCount.equals(other.pharmacyCount) && strengths.equals(other.strengths);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.offerCount, this.pharmacyCount, this.strengths);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static OfferCountStage builder() {
    return new Builder();
  }

  public interface OfferCountStage {
    PharmacyCountStage offerCount(
        @NotNull RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount offerCount);

    Builder from(RetrievePrescribingOptionsResponseCatalogMedicationGroup other);
  }

  public interface PharmacyCountStage {
    _FinalStage pharmacyCount(
        @NotNull RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount pharmacyCount);
  }

  public interface _FinalStage {
    RetrievePrescribingOptionsResponseCatalogMedicationGroup build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage strengths(List<String> strengths);

    _FinalStage addStrengths(String strengths);

    _FinalStage addAllStrengths(List<String> strengths);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements OfferCountStage, PharmacyCountStage, _FinalStage {
    private RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount offerCount;

    private RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount pharmacyCount;

    private List<String> strengths = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RetrievePrescribingOptionsResponseCatalogMedicationGroup other) {
      offerCount(other.getOfferCount());
      pharmacyCount(other.getPharmacyCount());
      strengths(other.getStrengths());
      return this;
    }

    @java.lang.Override
    @JsonSetter("offerCount")
    public PharmacyCountStage offerCount(
        @NotNull RetrievePrescribingOptionsResponseCatalogMedicationGroupOfferCount offerCount) {
      this.offerCount = Objects.requireNonNull(offerCount, "offerCount must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("pharmacyCount")
    public _FinalStage pharmacyCount(
        @NotNull RetrievePrescribingOptionsResponseCatalogMedicationGroupPharmacyCount pharmacyCount) {
      this.pharmacyCount = Objects.requireNonNull(pharmacyCount, "pharmacyCount must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllStrengths(List<String> strengths) {
      if (strengths != null) {
        this.strengths.addAll(strengths);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addStrengths(String strengths) {
      this.strengths.add(strengths);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "strengths",
        nulls = Nulls.SKIP
    )
    public _FinalStage strengths(List<String> strengths) {
      this.strengths.clear();
      if (strengths != null) {
        this.strengths.addAll(strengths);
      }
      return this;
    }

    @java.lang.Override
    public RetrievePrescribingOptionsResponseCatalogMedicationGroup build() {
      return new RetrievePrescribingOptionsResponseCatalogMedicationGroup(offerCount, pharmacyCount, strengths, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
