/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RetrievePrescribingOptionsResponseCatalogOrdering.Builder.class
)
public final class RetrievePrescribingOptionsResponseCatalogOrdering {
  private final boolean requiresPrescription;

  private final boolean requiresAccompanyingPrescription;

  private final RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping;

  private final Map<String, Object> additionalProperties;

  private RetrievePrescribingOptionsResponseCatalogOrdering(boolean requiresPrescription,
      boolean requiresAccompanyingPrescription,
      RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping,
      Map<String, Object> additionalProperties) {
    this.requiresPrescription = requiresPrescription;
    this.requiresAccompanyingPrescription = requiresAccompanyingPrescription;
    this.shipping = shipping;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("requiresPrescription")
  public boolean getRequiresPrescription() {
    return requiresPrescription;
  }

  @JsonProperty("requiresAccompanyingPrescription")
  public boolean getRequiresAccompanyingPrescription() {
    return requiresAccompanyingPrescription;
  }

  @JsonProperty("shipping")
  public RetrievePrescribingOptionsResponseCatalogOrderingShipping getShipping() {
    return shipping;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RetrievePrescribingOptionsResponseCatalogOrdering && equalTo((RetrievePrescribingOptionsResponseCatalogOrdering) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RetrievePrescribingOptionsResponseCatalogOrdering other) {
    return requiresPrescription == other.requiresPrescription && requiresAccompanyingPrescription == other.requiresAccompanyingPrescription && shipping.equals(other.shipping);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.requiresPrescription, this.requiresAccompanyingPrescription, this.shipping);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RequiresPrescriptionStage builder() {
    return new Builder();
  }

  public interface RequiresPrescriptionStage {
    RequiresAccompanyingPrescriptionStage requiresPrescription(boolean requiresPrescription);

    Builder from(RetrievePrescribingOptionsResponseCatalogOrdering other);
  }

  public interface RequiresAccompanyingPrescriptionStage {
    ShippingStage requiresAccompanyingPrescription(boolean requiresAccompanyingPrescription);
  }

  public interface ShippingStage {
    _FinalStage shipping(
        @NotNull RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping);
  }

  public interface _FinalStage {
    RetrievePrescribingOptionsResponseCatalogOrdering build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RequiresPrescriptionStage, RequiresAccompanyingPrescriptionStage, ShippingStage, _FinalStage {
    private boolean requiresPrescription;

    private boolean requiresAccompanyingPrescription;

    private RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RetrievePrescribingOptionsResponseCatalogOrdering other) {
      requiresPrescription(other.getRequiresPrescription());
      requiresAccompanyingPrescription(other.getRequiresAccompanyingPrescription());
      shipping(other.getShipping());
      return this;
    }

    @java.lang.Override
    @JsonSetter("requiresPrescription")
    public RequiresAccompanyingPrescriptionStage requiresPrescription(
        boolean requiresPrescription) {
      this.requiresPrescription = requiresPrescription;
      return this;
    }

    @java.lang.Override
    @JsonSetter("requiresAccompanyingPrescription")
    public ShippingStage requiresAccompanyingPrescription(
        boolean requiresAccompanyingPrescription) {
      this.requiresAccompanyingPrescription = requiresAccompanyingPrescription;
      return this;
    }

    @java.lang.Override
    @JsonSetter("shipping")
    public _FinalStage shipping(
        @NotNull RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping) {
      this.shipping = Objects.requireNonNull(shipping, "shipping must not be null");
      return this;
    }

    @java.lang.Override
    public RetrievePrescribingOptionsResponseCatalogOrdering build() {
      return new RetrievePrescribingOptionsResponseCatalogOrdering(requiresPrescription, requiresAccompanyingPrescription, shipping, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }

  public boolean requiresPrescription() { return getRequiresPrescription(); }

  public boolean requiresAccompanyingPrescription() { return getRequiresAccompanyingPrescription(); }

  public RetrievePrescribingOptionsResponseCatalogOrderingShipping shipping() { return getShipping(); }

  public Map<String, Object> additionalProperties() { return getAdditionalProperties(); }
}
