/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SignOrderResponseStatus {
  public static final SignOrderResponseStatus READY = new SignOrderResponseStatus(Value.READY, "ready");

  private final Value value;

  private final String string;

  SignOrderResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SignOrderResponseStatus && this.string.equals(((SignOrderResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case READY:
        return visitor.visitReady();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SignOrderResponseStatus valueOf(String value) {
    switch (value) {
      case "ready":
        return READY;
      default:
        return new SignOrderResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    READY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitReady();

    T visitUnknown(String unknownType);
  }
}
