/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class UpdateWebhookEndpointResponsePayloadStyle {
  public static final UpdateWebhookEndpointResponsePayloadStyle THIN = new UpdateWebhookEndpointResponsePayloadStyle(Value.THIN, "thin");

  public static final UpdateWebhookEndpointResponsePayloadStyle SNAPSHOT = new UpdateWebhookEndpointResponsePayloadStyle(Value.SNAPSHOT, "snapshot");

  private final Value value;

  private final String string;

  UpdateWebhookEndpointResponsePayloadStyle(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof UpdateWebhookEndpointResponsePayloadStyle && this.string.equals(((UpdateWebhookEndpointResponsePayloadStyle) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case THIN:
        return visitor.visitThin();
      case SNAPSHOT:
        return visitor.visitSnapshot();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static UpdateWebhookEndpointResponsePayloadStyle valueOf(String value) {
    switch (value) {
      case "thin":
        return THIN;
      case "snapshot":
        return SNAPSHOT;
      default:
        return new UpdateWebhookEndpointResponsePayloadStyle(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    THIN,

    SNAPSHOT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitThin();

    T visitSnapshot();

    T visitUnknown(String unknownType);
  }

  public Value enumValue() { return getEnumValue(); }
}
