/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.team.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem.Builder.class
)
public final class InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem {
  private final String name;

  private final String credentials;

  private final String type;

  private final Map<String, Object> additionalProperties;

  private InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem(String name,
      String credentials, String type, Map<String, Object> additionalProperties) {
    this.name = name;
    this.credentials = credentials;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("credentials")
  public String getCredentials() {
    return credentials;
  }

  @JsonProperty("type")
  public String getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem && equalTo((InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem other) {
    return name.equals(other.name) && credentials.equals(other.credentials) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.credentials, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    CredentialsStage name(@NotNull String name);

    Builder from(InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem other);
  }

  public interface CredentialsStage {
    TypeStage credentials(@NotNull String credentials);
  }

  public interface TypeStage {
    _FinalStage type(@NotNull String type);
  }

  public interface _FinalStage {
    InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, CredentialsStage, TypeStage, _FinalStage {
    private String name;

    private String credentials;

    private String type;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem other) {
      name(other.getName());
      credentials(other.getCredentials());
      type(other.getType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public CredentialsStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("credentials")
    public TypeStage credentials(@NotNull String credentials) {
      this.credentials = Objects.requireNonNull(credentials, "credentials must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull String type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem build() {
      return new InvitePracticeTeamPersonRequestProfileDetailsOtherNamesItem(name, credentials, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
