/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.batches.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig.Builder.class
)
public final class CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig {
  private final String dose;

  private final String doseUnit;

  private final Optional<String> duration;

  private final String frequency;

  private final Optional<String> indication;

  private final Optional<String> maxDailyUse;

  private final Optional<Boolean> prn;

  private final String route;

  private final Optional<String> titrationSchedule;

  private final Map<String, Object> additionalProperties;

  private CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig(String dose,
      String doseUnit, Optional<String> duration, String frequency, Optional<String> indication,
      Optional<String> maxDailyUse, Optional<Boolean> prn, String route,
      Optional<String> titrationSchedule, Map<String, Object> additionalProperties) {
    this.dose = dose;
    this.doseUnit = doseUnit;
    this.duration = duration;
    this.frequency = frequency;
    this.indication = indication;
    this.maxDailyUse = maxDailyUse;
    this.prn = prn;
    this.route = route;
    this.titrationSchedule = titrationSchedule;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("dose")
  public String getDose() {
    return dose;
  }

  @JsonProperty("doseUnit")
  public String getDoseUnit() {
    return doseUnit;
  }

  @JsonIgnore
  public Optional<String> getDuration() {
    if (duration == null) {
      return Optional.empty();
    }
    return duration;
  }

  @JsonProperty("frequency")
  public String getFrequency() {
    return frequency;
  }

  @JsonIgnore
  public Optional<String> getIndication() {
    if (indication == null) {
      return Optional.empty();
    }
    return indication;
  }

  @JsonIgnore
  public Optional<String> getMaxDailyUse() {
    if (maxDailyUse == null) {
      return Optional.empty();
    }
    return maxDailyUse;
  }

  @JsonIgnore
  public Optional<Boolean> getPrn() {
    if (prn == null) {
      return Optional.empty();
    }
    return prn;
  }

  @JsonProperty("route")
  public String getRoute() {
    return route;
  }

  @JsonIgnore
  public Optional<String> getTitrationSchedule() {
    if (titrationSchedule == null) {
      return Optional.empty();
    }
    return titrationSchedule;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("duration")
  private Optional<String> _getDuration() {
    return duration;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("indication")
  private Optional<String> _getIndication() {
    return indication;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("maxDailyUse")
  private Optional<String> _getMaxDailyUse() {
    return maxDailyUse;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("prn")
  private Optional<Boolean> _getPrn() {
    return prn;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("titrationSchedule")
  private Optional<String> _getTitrationSchedule() {
    return titrationSchedule;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig && equalTo((CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig other) {
    return dose.equals(other.dose) && doseUnit.equals(other.doseUnit) && duration.equals(other.duration) && frequency.equals(other.frequency) && indication.equals(other.indication) && maxDailyUse.equals(other.maxDailyUse) && prn.equals(other.prn) && route.equals(other.route) && titrationSchedule.equals(other.titrationSchedule);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.dose, this.doseUnit, this.duration, this.frequency, this.indication, this.maxDailyUse, this.prn, this.route, this.titrationSchedule);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DoseStage builder() {
    return new Builder();
  }

  public interface DoseStage {
    DoseUnitStage dose(@NotNull String dose);

    Builder from(CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig other);
  }

  public interface DoseUnitStage {
    FrequencyStage doseUnit(@NotNull String doseUnit);
  }

  public interface FrequencyStage {
    RouteStage frequency(@NotNull String frequency);
  }

  public interface RouteStage {
    _FinalStage route(@NotNull String route);
  }

  public interface _FinalStage {
    CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage duration(Optional<String> duration);

    _FinalStage duration(String duration);

    _FinalStage duration(Nullable<String> duration);

    _FinalStage indication(Optional<String> indication);

    _FinalStage indication(String indication);

    _FinalStage indication(Nullable<String> indication);

    _FinalStage maxDailyUse(Optional<String> maxDailyUse);

    _FinalStage maxDailyUse(String maxDailyUse);

    _FinalStage maxDailyUse(Nullable<String> maxDailyUse);

    _FinalStage prn(Optional<Boolean> prn);

    _FinalStage prn(Boolean prn);

    _FinalStage prn(Nullable<Boolean> prn);

    _FinalStage titrationSchedule(Optional<String> titrationSchedule);

    _FinalStage titrationSchedule(String titrationSchedule);

    _FinalStage titrationSchedule(Nullable<String> titrationSchedule);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DoseStage, DoseUnitStage, FrequencyStage, RouteStage, _FinalStage {
    private String dose;

    private String doseUnit;

    private String frequency;

    private String route;

    private Optional<String> titrationSchedule = Optional.empty();

    private Optional<Boolean> prn = Optional.empty();

    private Optional<String> maxDailyUse = Optional.empty();

    private Optional<String> indication = Optional.empty();

    private Optional<String> duration = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig other) {
      dose(other.getDose());
      doseUnit(other.getDoseUnit());
      duration(other.getDuration());
      frequency(other.getFrequency());
      indication(other.getIndication());
      maxDailyUse(other.getMaxDailyUse());
      prn(other.getPrn());
      route(other.getRoute());
      titrationSchedule(other.getTitrationSchedule());
      return this;
    }

    @java.lang.Override
    @JsonSetter("dose")
    public DoseUnitStage dose(@NotNull String dose) {
      this.dose = Objects.requireNonNull(dose, "dose must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("doseUnit")
    public FrequencyStage doseUnit(@NotNull String doseUnit) {
      this.doseUnit = Objects.requireNonNull(doseUnit, "doseUnit must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("frequency")
    public RouteStage frequency(@NotNull String frequency) {
      this.frequency = Objects.requireNonNull(frequency, "frequency must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("route")
    public _FinalStage route(@NotNull String route) {
      this.route = Objects.requireNonNull(route, "route must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage titrationSchedule(Nullable<String> titrationSchedule) {
      if (titrationSchedule.isNull()) {
        this.titrationSchedule = null;
      }
      else if (titrationSchedule.isEmpty()) {
        this.titrationSchedule = Optional.empty();
      }
      else {
        this.titrationSchedule = Optional.of(titrationSchedule.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage titrationSchedule(String titrationSchedule) {
      this.titrationSchedule = Optional.ofNullable(titrationSchedule);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "titrationSchedule",
        nulls = Nulls.SKIP
    )
    public _FinalStage titrationSchedule(Optional<String> titrationSchedule) {
      this.titrationSchedule = titrationSchedule;
      return this;
    }

    @java.lang.Override
    public _FinalStage prn(Nullable<Boolean> prn) {
      if (prn.isNull()) {
        this.prn = null;
      }
      else if (prn.isEmpty()) {
        this.prn = Optional.empty();
      }
      else {
        this.prn = Optional.of(prn.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage prn(Boolean prn) {
      this.prn = Optional.ofNullable(prn);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "prn",
        nulls = Nulls.SKIP
    )
    public _FinalStage prn(Optional<Boolean> prn) {
      this.prn = prn;
      return this;
    }

    @java.lang.Override
    public _FinalStage maxDailyUse(Nullable<String> maxDailyUse) {
      if (maxDailyUse.isNull()) {
        this.maxDailyUse = null;
      }
      else if (maxDailyUse.isEmpty()) {
        this.maxDailyUse = Optional.empty();
      }
      else {
        this.maxDailyUse = Optional.of(maxDailyUse.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage maxDailyUse(String maxDailyUse) {
      this.maxDailyUse = Optional.ofNullable(maxDailyUse);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "maxDailyUse",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxDailyUse(Optional<String> maxDailyUse) {
      this.maxDailyUse = maxDailyUse;
      return this;
    }

    @java.lang.Override
    public _FinalStage indication(Nullable<String> indication) {
      if (indication.isNull()) {
        this.indication = null;
      }
      else if (indication.isEmpty()) {
        this.indication = Optional.empty();
      }
      else {
        this.indication = Optional.of(indication.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage indication(String indication) {
      this.indication = Optional.ofNullable(indication);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "indication",
        nulls = Nulls.SKIP
    )
    public _FinalStage indication(Optional<String> indication) {
      this.indication = indication;
      return this;
    }

    @java.lang.Override
    public _FinalStage duration(Nullable<String> duration) {
      if (duration.isNull()) {
        this.duration = null;
      }
      else if (duration.isEmpty()) {
        this.duration = Optional.empty();
      }
      else {
        this.duration = Optional.of(duration.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage duration(String duration) {
      this.duration = Optional.ofNullable(duration);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "duration",
        nulls = Nulls.SKIP
    )
    public _FinalStage duration(Optional<String> duration) {
      this.duration = duration;
      return this;
    }

    @java.lang.Override
    public CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig build() {
      return new CreateOrderBatchRequestOrdersItemPrescriptionsItemStructuredSig(dose, doseUnit, duration, frequency, indication, maxDailyUse, prn, route, titrationSchedule, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
