package com.affinity.api.models;
import java.util.*;import com.fasterxml.jackson.annotation.JsonValue;
public final class TeamInvitationCreateParamsProfileDetailsAddressesItem{private final Map<String,Object> values;private TeamInvitationCreateParamsProfileDetailsAddressesItem(Map<String,Object> values){this.values=Collections.unmodifiableMap(new LinkedHashMap<>(values));}@JsonValue public Map<String,Object> values(){return values;}public static Builder builder(){return new Builder();}public static final class Builder {private final Map<String,Object> values=new LinkedHashMap<>();public Builder purpose(String value){values.put("purpose",value);return this;}
public Builder line1(String value){values.put("line1",value);return this;}
public Builder line2(String value){values.put("line2",value);return this;}
public Builder city(String value){values.put("city",value);return this;}
public Builder state(String value){values.put("state",value);return this;}
public Builder postalCode(String value){values.put("postalCode",value);return this;}
public Builder country(String value){values.put("country",value);return this;}
public Builder phone(String value){values.put("phone",value);return this;}
public Builder fax(String value){values.put("fax",value);return this;}public TeamInvitationCreateParamsProfileDetailsAddressesItem build(){if(!values.containsKey("purpose")||values.get("purpose")==null)throw new IllegalArgumentException("purpose is required");if(!values.containsKey("line1")||values.get("line1")==null)throw new IllegalArgumentException("line1 is required");if(!values.containsKey("line2")||values.get("line2")==null)throw new IllegalArgumentException("line2 is required");if(!values.containsKey("city")||values.get("city")==null)throw new IllegalArgumentException("city is required");if(!values.containsKey("state")||values.get("state")==null)throw new IllegalArgumentException("state is required");if(!values.containsKey("postalCode")||values.get("postalCode")==null)throw new IllegalArgumentException("postalCode is required");if(!values.containsKey("country")||values.get("country")==null)throw new IllegalArgumentException("country is required");if(!values.containsKey("phone")||values.get("phone")==null)throw new IllegalArgumentException("phone is required");if(!values.containsKey("fax")||values.get("fax")==null)throw new IllegalArgumentException("fax is required");return new TeamInvitationCreateParamsProfileDetailsAddressesItem(values);}}}