/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.events;

import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.resources.orders.events.requests.ListEventsRequest;
import com.affinity.api.types.ListOrderEventsResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncEventsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawEventsClient rawClient;

  public AsyncEventsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawEventsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawEventsClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<ListOrderEventsResponse> list(String orderId) {
    return this.rawClient.list(orderId).thenApply(response -> response.body());
  }

  public CompletableFuture<ListOrderEventsResponse> list(String orderId,
      RequestOptions requestOptions) {
    return this.rawClient.list(orderId, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<ListOrderEventsResponse> list(String orderId,
      ListEventsRequest request) {
    return this.rawClient.list(orderId, request).thenApply(response -> response.body());
  }

  public CompletableFuture<ListOrderEventsResponse> list(String orderId, ListEventsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(orderId, request, requestOptions).thenApply(response -> response.body());
  }
}
