/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.events;

import com.affinity.api.core.AffinityClientApiException;
import com.affinity.api.core.AffinityClientException;
import com.affinity.api.core.AffinityClientHttpResponse;
import com.affinity.api.core.ClientOptions;
import com.affinity.api.core.ObjectMappers;
import com.affinity.api.core.QueryStringMapper;
import com.affinity.api.core.RequestOptions;
import com.affinity.api.core.RetryInterceptor;
import com.affinity.api.errors.BadRequestError;
import com.affinity.api.errors.ConflictError;
import com.affinity.api.errors.ForbiddenError;
import com.affinity.api.errors.NotFoundError;
import com.affinity.api.errors.TooManyRequestsError;
import com.affinity.api.errors.UnauthorizedError;
import com.affinity.api.errors.UnprocessableEntityError;
import com.affinity.api.resources.orders.events.requests.ListEventsRequest;
import com.affinity.api.types.ListOrderEventsResponse;
import com.affinity.api.types.Problem;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEventsClient {
  protected final ClientOptions clientOptions;

  public RawEventsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public AffinityClientHttpResponse<ListOrderEventsResponse> list(String orderId) {
    return list(orderId,ListEventsRequest.builder().build());
  }

  public AffinityClientHttpResponse<ListOrderEventsResponse> list(String orderId,
      RequestOptions requestOptions) {
    return list(orderId,ListEventsRequest.builder().build(),requestOptions);
  }

  public AffinityClientHttpResponse<ListOrderEventsResponse> list(String orderId,
      ListEventsRequest request) {
    return list(orderId,request,null);
  }

  public AffinityClientHttpResponse<ListOrderEventsResponse> list(String orderId,
      ListEventsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/orders")
      .addPathSegment(orderId)
      .addPathSegments("events");if (request.getEndingBefore().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "endingBefore", request.getEndingBefore().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getStartingAfter().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "startingAfter", request.getStartingAfter().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      if (request.getAffinityActorId().isPresent()) {
        _requestBuilder.addHeader("Affinity-Actor-Id", request.getAffinityActorId().get());
      }
      if (request.getAffinityActorType().isPresent()) {
        _requestBuilder.addHeader("Affinity-Actor-Type", request.getAffinityActorType().get());
      }
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new AffinityClientHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListOrderEventsResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 403:throw new ForbiddenError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 409:throw new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 422:throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
            case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Problem.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new AffinityClientApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new AffinityClientException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new AffinityClientException("Network error executing HTTP request", e);
      }
    }
  }
