/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.catalog.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListCatalogItemsRequestSort {
  public static final ListCatalogItemsRequestSort NAME_DESC = new ListCatalogItemsRequestSort(Value.NAME_DESC, "name_desc");

  public static final ListCatalogItemsRequestSort RELEVANCE = new ListCatalogItemsRequestSort(Value.RELEVANCE, "relevance");

  public static final ListCatalogItemsRequestSort NAME_ASC = new ListCatalogItemsRequestSort(Value.NAME_ASC, "name_asc");

  private final Value value;

  private final String string;

  ListCatalogItemsRequestSort(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListCatalogItemsRequestSort && this.string.equals(((ListCatalogItemsRequestSort) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case NAME_DESC:
        return visitor.visitNameDesc();
      case RELEVANCE:
        return visitor.visitRelevance();
      case NAME_ASC:
        return visitor.visitNameAsc();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListCatalogItemsRequestSort valueOf(String value) {
    switch (value) {
      case "name_desc":
        return NAME_DESC;
      case "relevance":
        return RELEVANCE;
      case "name_asc":
        return NAME_ASC;
      default:
        return new ListCatalogItemsRequestSort(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RELEVANCE,

    NAME_ASC,

    NAME_DESC,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRelevance();

    T visitNameAsc();

    T visitNameDesc();

    T visitUnknown(String unknownType);
  }
}
