/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.patients.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListPatientsRequestGender {
  public static final ListPatientsRequestGender U = new ListPatientsRequestGender(Value.U, "u");

  public static final ListPatientsRequestGender O = new ListPatientsRequestGender(Value.O, "o");

  public static final ListPatientsRequestGender F = new ListPatientsRequestGender(Value.F, "f");

  public static final ListPatientsRequestGender M = new ListPatientsRequestGender(Value.M, "m");

  private final Value value;

  private final String string;

  ListPatientsRequestGender(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListPatientsRequestGender && this.string.equals(((ListPatientsRequestGender) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case U:
        return visitor.visitU();
      case O:
        return visitor.visitO();
      case F:
        return visitor.visitF();
      case M:
        return visitor.visitM();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListPatientsRequestGender valueOf(String value) {
    switch (value) {
      case "u":
        return U;
      case "o":
        return O;
      case "f":
        return F;
      case "m":
        return M;
      default:
        return new ListPatientsRequestGender(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    F,

    M,

    O,

    U,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitF();

    T visitM();

    T visitO();

    T visitU();

    T visitUnknown(String unknownType);
  }
}
