/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.patients.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ReplacePatientAllergiesRequestReviewStatus {
  public static final ReplacePatientAllergiesRequestReviewStatus NOT_REVIEWED = new ReplacePatientAllergiesRequestReviewStatus(Value.NOT_REVIEWED, "not_reviewed");

  public static final ReplacePatientAllergiesRequestReviewStatus RECORDED = new ReplacePatientAllergiesRequestReviewStatus(Value.RECORDED, "recorded");

  public static final ReplacePatientAllergiesRequestReviewStatus NO_KNOWN = new ReplacePatientAllergiesRequestReviewStatus(Value.NO_KNOWN, "no_known");

  private final Value value;

  private final String string;

  ReplacePatientAllergiesRequestReviewStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ReplacePatientAllergiesRequestReviewStatus && this.string.equals(((ReplacePatientAllergiesRequestReviewStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case NOT_REVIEWED:
        return visitor.visitNotReviewed();
      case RECORDED:
        return visitor.visitRecorded();
      case NO_KNOWN:
        return visitor.visitNoKnown();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ReplacePatientAllergiesRequestReviewStatus valueOf(String value) {
    switch (value) {
      case "not_reviewed":
        return NOT_REVIEWED;
      case "recorded":
        return RECORDED;
      case "no_known":
        return NO_KNOWN;
      default:
        return new ReplacePatientAllergiesRequestReviewStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NOT_REVIEWED,

    NO_KNOWN,

    RECORDED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNotReviewed();

    T visitNoKnown();

    T visitRecorded();

    T visitUnknown(String unknownType);
  }
}
