/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.catalog.requests;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RetrievePrescribingOptionsRequest.Builder.class
)
public final class RetrievePrescribingOptionsRequest {
  private final String practiceId;

  private final Map<String, Object> additionalProperties;

  private RetrievePrescribingOptionsRequest(String practiceId,
      Map<String, Object> additionalProperties) {
    this.practiceId = practiceId;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("practiceId")
  public String getPracticeId() {
    return practiceId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RetrievePrescribingOptionsRequest && equalTo((RetrievePrescribingOptionsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RetrievePrescribingOptionsRequest other) {
    return practiceId.equals(other.practiceId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.practiceId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PracticeIdStage builder() {
    return new Builder();
  }

  public interface PracticeIdStage {
    _FinalStage practiceId(@NotNull String practiceId);

    Builder from(RetrievePrescribingOptionsRequest other);
  }

  public interface _FinalStage {
    RetrievePrescribingOptionsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PracticeIdStage, _FinalStage {
    private String practiceId;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(RetrievePrescribingOptionsRequest other) {
      practiceId(other.getPracticeId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("practiceId")
    public _FinalStage practiceId(@NotNull String practiceId) {
      this.practiceId = Objects.requireNonNull(practiceId, "practiceId must not be null");
      return this;
    }

    @java.lang.Override
    public RetrievePrescribingOptionsRequest build() {
      return new RetrievePrescribingOptionsRequest(practiceId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
