/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CreateOrderRequestPatientClinicalProfileWeightPoundsOne {
  public static final CreateOrderRequestPatientClinicalProfileWeightPoundsOne INFINITY = new CreateOrderRequestPatientClinicalProfileWeightPoundsOne(Value.INFINITY, "Infinity");

  public static final CreateOrderRequestPatientClinicalProfileWeightPoundsOne NA_N = new CreateOrderRequestPatientClinicalProfileWeightPoundsOne(Value.NA_N, "NaN");

  private final Value value;

  private final String string;

  CreateOrderRequestPatientClinicalProfileWeightPoundsOne(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CreateOrderRequestPatientClinicalProfileWeightPoundsOne && this.string.equals(((CreateOrderRequestPatientClinicalProfileWeightPoundsOne) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INFINITY:
        return visitor.visitInfinity();
      case NA_N:
        return visitor.visitNaN();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CreateOrderRequestPatientClinicalProfileWeightPoundsOne valueOf(String value) {
    switch (value) {
      case "Infinity":
        return INFINITY;
      case "NaN":
        return NA_N;
      default:
        return new CreateOrderRequestPatientClinicalProfileWeightPoundsOne(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INFINITY,

    NA_N,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInfinity();

    T visitNaN();

    T visitUnknown(String unknownType);
  }
}
