/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.types;

import com.affinity.api.core.Nullable;
import com.affinity.api.core.NullableNonemptyFilter;
import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PreviewOrderRequestPrescriptionsItemOverridesClinical.Builder.class
)
public final class PreviewOrderRequestPrescriptionsItemOverridesClinical {
  private final Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> compoundingReason;

  private final Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> medicationReviewStatus;

  private final Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> diagnosisReviewStatus;

  private final Optional<List<String>> currentMedications;

  private final Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> diagnoses;

  private final Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> observations;

  private final Map<String, Object> additionalProperties;

  private PreviewOrderRequestPrescriptionsItemOverridesClinical(
      Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> compoundingReason,
      Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> medicationReviewStatus,
      Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> diagnosisReviewStatus,
      Optional<List<String>> currentMedications,
      Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> diagnoses,
      Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> observations,
      Map<String, Object> additionalProperties) {
    this.compoundingReason = compoundingReason;
    this.medicationReviewStatus = medicationReviewStatus;
    this.diagnosisReviewStatus = diagnosisReviewStatus;
    this.currentMedications = currentMedications;
    this.diagnoses = diagnoses;
    this.observations = observations;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> getCompoundingReason(
      ) {
    if (compoundingReason == null) {
      return Optional.empty();
    }
    return compoundingReason;
  }

  @JsonIgnore
  public Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> getMedicationReviewStatus(
      ) {
    if (medicationReviewStatus == null) {
      return Optional.empty();
    }
    return medicationReviewStatus;
  }

  @JsonIgnore
  public Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> getDiagnosisReviewStatus(
      ) {
    if (diagnosisReviewStatus == null) {
      return Optional.empty();
    }
    return diagnosisReviewStatus;
  }

  @JsonIgnore
  public Optional<List<String>> getCurrentMedications() {
    if (currentMedications == null) {
      return Optional.empty();
    }
    return currentMedications;
  }

  @JsonIgnore
  public Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> getDiagnoses(
      ) {
    if (diagnoses == null) {
      return Optional.empty();
    }
    return diagnoses;
  }

  @JsonIgnore
  public Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> getObservations(
      ) {
    if (observations == null) {
      return Optional.empty();
    }
    return observations;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("compoundingReason")
  private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> _getCompoundingReason(
      ) {
    return compoundingReason;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("medicationReviewStatus")
  private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> _getMedicationReviewStatus(
      ) {
    return medicationReviewStatus;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("diagnosisReviewStatus")
  private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> _getDiagnosisReviewStatus(
      ) {
    return diagnosisReviewStatus;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("currentMedications")
  private Optional<List<String>> _getCurrentMedications() {
    return currentMedications;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("diagnoses")
  private Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> _getDiagnoses(
      ) {
    return diagnoses;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("observations")
  private Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> _getObservations(
      ) {
    return observations;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PreviewOrderRequestPrescriptionsItemOverridesClinical && equalTo((PreviewOrderRequestPrescriptionsItemOverridesClinical) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PreviewOrderRequestPrescriptionsItemOverridesClinical other) {
    return compoundingReason.equals(other.compoundingReason) && medicationReviewStatus.equals(other.medicationReviewStatus) && diagnosisReviewStatus.equals(other.diagnosisReviewStatus) && currentMedications.equals(other.currentMedications) && diagnoses.equals(other.diagnoses) && observations.equals(other.observations);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.compoundingReason, this.medicationReviewStatus, this.diagnosisReviewStatus, this.currentMedications, this.diagnoses, this.observations);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> compoundingReason = Optional.empty();

    private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> medicationReviewStatus = Optional.empty();

    private Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> diagnosisReviewStatus = Optional.empty();

    private Optional<List<String>> currentMedications = Optional.empty();

    private Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> diagnoses = Optional.empty();

    private Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> observations = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PreviewOrderRequestPrescriptionsItemOverridesClinical other) {
      compoundingReason(other.getCompoundingReason());
      medicationReviewStatus(other.getMedicationReviewStatus());
      diagnosisReviewStatus(other.getDiagnosisReviewStatus());
      currentMedications(other.getCurrentMedications());
      diagnoses(other.getDiagnoses());
      observations(other.getObservations());
      return this;
    }

    @JsonSetter(
        value = "compoundingReason",
        nulls = Nulls.SKIP
    )
    public Builder compoundingReason(
        Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> compoundingReason) {
      this.compoundingReason = compoundingReason;
      return this;
    }

    public Builder compoundingReason(
        PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason compoundingReason) {
      this.compoundingReason = Optional.ofNullable(compoundingReason);
      return this;
    }

    public Builder compoundingReason(
        Nullable<PreviewOrderRequestPrescriptionsItemOverridesClinicalCompoundingReason> compoundingReason) {
      if (compoundingReason.isNull()) {
        this.compoundingReason = null;
      }
      else if (compoundingReason.isEmpty()) {
        this.compoundingReason = Optional.empty();
      }
      else {
        this.compoundingReason = Optional.of(compoundingReason.get());
      }
      return this;
    }

    @JsonSetter(
        value = "medicationReviewStatus",
        nulls = Nulls.SKIP
    )
    public Builder medicationReviewStatus(
        Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> medicationReviewStatus) {
      this.medicationReviewStatus = medicationReviewStatus;
      return this;
    }

    public Builder medicationReviewStatus(
        PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus medicationReviewStatus) {
      this.medicationReviewStatus = Optional.ofNullable(medicationReviewStatus);
      return this;
    }

    public Builder medicationReviewStatus(
        Nullable<PreviewOrderRequestPrescriptionsItemOverridesClinicalMedicationReviewStatus> medicationReviewStatus) {
      if (medicationReviewStatus.isNull()) {
        this.medicationReviewStatus = null;
      }
      else if (medicationReviewStatus.isEmpty()) {
        this.medicationReviewStatus = Optional.empty();
      }
      else {
        this.medicationReviewStatus = Optional.of(medicationReviewStatus.get());
      }
      return this;
    }

    @JsonSetter(
        value = "diagnosisReviewStatus",
        nulls = Nulls.SKIP
    )
    public Builder diagnosisReviewStatus(
        Optional<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> diagnosisReviewStatus) {
      this.diagnosisReviewStatus = diagnosisReviewStatus;
      return this;
    }

    public Builder diagnosisReviewStatus(
        PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus diagnosisReviewStatus) {
      this.diagnosisReviewStatus = Optional.ofNullable(diagnosisReviewStatus);
      return this;
    }

    public Builder diagnosisReviewStatus(
        Nullable<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosisReviewStatus> diagnosisReviewStatus) {
      if (diagnosisReviewStatus.isNull()) {
        this.diagnosisReviewStatus = null;
      }
      else if (diagnosisReviewStatus.isEmpty()) {
        this.diagnosisReviewStatus = Optional.empty();
      }
      else {
        this.diagnosisReviewStatus = Optional.of(diagnosisReviewStatus.get());
      }
      return this;
    }

    @JsonSetter(
        value = "currentMedications",
        nulls = Nulls.SKIP
    )
    public Builder currentMedications(Optional<List<String>> currentMedications) {
      this.currentMedications = currentMedications;
      return this;
    }

    public Builder currentMedications(List<String> currentMedications) {
      this.currentMedications = Optional.ofNullable(currentMedications);
      return this;
    }

    public Builder currentMedications(Nullable<List<String>> currentMedications) {
      if (currentMedications.isNull()) {
        this.currentMedications = null;
      }
      else if (currentMedications.isEmpty()) {
        this.currentMedications = Optional.empty();
      }
      else {
        this.currentMedications = Optional.of(currentMedications.get());
      }
      return this;
    }

    @JsonSetter(
        value = "diagnoses",
        nulls = Nulls.SKIP
    )
    public Builder diagnoses(
        Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> diagnoses) {
      this.diagnoses = diagnoses;
      return this;
    }

    public Builder diagnoses(
        List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem> diagnoses) {
      this.diagnoses = Optional.ofNullable(diagnoses);
      return this;
    }

    public Builder diagnoses(
        Nullable<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalDiagnosesItem>> diagnoses) {
      if (diagnoses.isNull()) {
        this.diagnoses = null;
      }
      else if (diagnoses.isEmpty()) {
        this.diagnoses = Optional.empty();
      }
      else {
        this.diagnoses = Optional.of(diagnoses.get());
      }
      return this;
    }

    @JsonSetter(
        value = "observations",
        nulls = Nulls.SKIP
    )
    public Builder observations(
        Optional<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> observations) {
      this.observations = observations;
      return this;
    }

    public Builder observations(
        List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem> observations) {
      this.observations = Optional.ofNullable(observations);
      return this;
    }

    public Builder observations(
        Nullable<List<PreviewOrderRequestPrescriptionsItemOverridesClinicalObservationsItem>> observations) {
      if (observations.isNull()) {
        this.observations = null;
      }
      else if (observations.isEmpty()) {
        this.observations = Optional.empty();
      }
      else {
        this.observations = Optional.of(observations.get());
      }
      return this;
    }

    public PreviewOrderRequestPrescriptionsItemOverridesClinical build() {
      return new PreviewOrderRequestPrescriptionsItemOverridesClinical(compoundingReason, medicationReviewStatus, diagnosisReviewStatus, currentMedications, diagnoses, observations, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
