/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.affinity.api.resources.orders.types;

import com.affinity.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem.Builder.class
)
public final class UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem {
  private final String display;

  private final String unit;

  private final UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue value;

  private final Map<String, Object> additionalProperties;

  private UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem(String display,
      String unit, UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue value,
      Map<String, Object> additionalProperties) {
    this.display = display;
    this.unit = unit;
    this.value = value;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("display")
  public String getDisplay() {
    return display;
  }

  @JsonProperty("unit")
  public String getUnit() {
    return unit;
  }

  @JsonProperty("value")
  public UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem && equalTo((UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(
      UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem other) {
    return display.equals(other.display) && unit.equals(other.unit) && value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.display, this.unit, this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DisplayStage builder() {
    return new Builder();
  }

  public interface DisplayStage {
    UnitStage display(@NotNull String display);

    Builder from(UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem other);
  }

  public interface UnitStage {
    ValueStage unit(@NotNull String unit);
  }

  public interface ValueStage {
    _FinalStage value(
        @NotNull UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue value);
  }

  public interface _FinalStage {
    UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DisplayStage, UnitStage, ValueStage, _FinalStage {
    private String display;

    private String unit;

    private UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue value;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem other) {
      display(other.getDisplay());
      unit(other.getUnit());
      value(other.getValue());
      return this;
    }

    @java.lang.Override
    @JsonSetter("display")
    public UnitStage display(@NotNull String display) {
      this.display = Objects.requireNonNull(display, "display must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("unit")
    public ValueStage unit(@NotNull String unit) {
      this.unit = Objects.requireNonNull(unit, "unit must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("value")
    public _FinalStage value(
        @NotNull UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItemValue value) {
      this.value = Objects.requireNonNull(value, "value must not be null");
      return this;
    }

    @java.lang.Override
    public UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem build() {
      return new UpdateOrderPrescriptionRequestPrescriptionClinicalObservationsItem(display, unit, value, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
